// ==========================================
// 人教版PEP小学英语 3-6年级 完整词汇库
// 提取自 english.html LOCAL_VOCAB
// 格式: {en, cn, ph, unit}
// 总计: 483 词
// 生成时间: 2026-04-29
// ==========================================

var LOCAL_VOCAB = {
    "3-1": [
        {en:"hello",cn:"你好",ph:"/həˈləʊ/",unit:1},
        {en:"hi",cn:"你好",ph:"/haɪ/",unit:1},
        {en:"name",cn:"名字",ph:"/neɪm/",unit:1},
        {en:"goodbye",cn:"再见",ph:"/ˌɡʊdˈbaɪ/",unit:1},
        {en:"bye",cn:"再见",ph:"/baɪ/",unit:1},
        {en:"I'm",cn:"我是",ph:"/aɪm/",unit:1},
        {en:"Ms",cn:"女士",ph:"/mɪz/",unit:1},
        {en:"new",cn:"新的",ph:"/njuː/",unit:1},
        {en:"year",cn:"岁；年",ph:"/jɪə(r)/",unit:1},
        {en:"old",cn:"……岁的",ph:"/əʊld/",unit:1},
        {en:"how old",cn:"几岁",ph:"/haʊ əʊld/",unit:1},
        {en:"too",cn:"也",ph:"/tuː/",unit:1},
        {en:"friend",cn:"朋友",ph:"/frend/",unit:1},
        {en:"our",cn:"我们的",ph:"/ˈaʊə(r)/",unit:1},
        {en:"school",cn:"学校",ph:"/skuːl/",unit:1},
        {en:"morning",cn:"早晨",ph:"/ˈmɔːnɪŋ/",unit:1},
        {en:"afternoon",cn:"下午",ph:"/ˌɑːftəˈnuːn/",unit:1},
        {en:"great",cn:"太棒了",ph:"/ɡreɪt/",unit:1},
        {en:"nice",cn:"令人愉快的",ph:"/naɪs/",unit:1},
        {en:"meet",cn:"遇见",ph:"/miːt/",unit:1},
        {en:"family",cn:"家庭",ph:"/ˈfæməli/",unit:2},
        {en:"who",cn:"谁",ph:"/huː/",unit:2},
        {en:"father",cn:"父亲",ph:"/ˈfɑːðə(r)/",unit:2},
        {en:"mother",cn:"母亲",ph:"/ˈmʌðə(r)/",unit:2},
        {en:"dad",cn:"爸爸",ph:"/dæd/",unit:2},
        {en:"mum",cn:"妈妈",ph:"/mʌm/",unit:2},
        {en:"grandfather",cn:"爷爷；外公",ph:"/ˈɡrænfɑːðə(r)/",unit:2},
        {en:"grandmother",cn:"奶奶；外婆",ph:"/ˈɡrænmʌðə(r)/",unit:2},
        {en:"grandpa",cn:"爷爷；外公",ph:"/ˈɡrænpɑː/",unit:2},
        {en:"grandma",cn:"奶奶；外婆",ph:"/ˈɡrænmɑː/",unit:2},
        {en:"baby",cn:"婴儿",ph:"/ˈbeɪbi/",unit:2},
        {en:"me",cn:"我(宾格)",ph:"/miː/",unit:2},
        {en:"sister",cn:"姐；妹",ph:"/ˈsɪstə(r)/",unit:2},
        {en:"brother",cn:"兄；弟",ph:"/ˈbrʌðə(r)/",unit:2},
        {en:"have",cn:"有",ph:"/hæv/",unit:2},
        {en:"big",cn:"大的",ph:"/bɪɡ/",unit:2},
        {en:"small",cn:"小的",ph:"/smɔːl/",unit:2},
        {en:"love",cn:"爱",ph:"/lʌv/",unit:2},
        {en:"pet",cn:"宠物",ph:"/pet/",unit:3},
        {en:"look at",cn:"看……",ph:"/lʊk æt/",unit:3},
        {en:"it",cn:"它",ph:"/ɪt/",unit:3},
        {en:"cat",cn:"猫",ph:"/kæt/",unit:3},
        {en:"dog",cn:"狗",ph:"/dɒɡ/",unit:3},
        {en:"fish",cn:"鱼",ph:"/fɪʃ/",unit:3},
        {en:"bird",cn:"鸟",ph:"/bɜːd/",unit:3},
        {en:"rabbit",cn:"兔子",ph:"/ˈræbɪt/",unit:3},
        {en:"listen",cn:"听",ph:"/ˈlɪsn/",unit:3},
        {en:"sing",cn:"唱",ph:"/sɪŋ/",unit:3},
        {en:"dance",cn:"跳舞",ph:"/dɑːns/",unit:3},
        {en:"what",cn:"什么",ph:"/wɒt/",unit:3},
        {en:"cute",cn:"可爱的",ph:"/kjuːt/",unit:3},
        {en:"plant",cn:"植物",ph:"/plɑːnt/",unit:4},
        {en:"flower",cn:"花",ph:"/ˈflaʊə(r)/",unit:4},
        {en:"grass",cn:"草",ph:"/ɡrɑːs/",unit:4},
        {en:"tree",cn:"树",ph:"/triː/",unit:4},
        {en:"sun",cn:"太阳",ph:"/sʌn/",unit:4},
        {en:"water",cn:"水；浇水",ph:"/ˈwɔːtə(r)/",unit:4},
        {en:"see",cn:"看见",ph:"/siː/",unit:4},
        {en:"many",cn:"许多",ph:"/ˈmeni/",unit:4},
        {en:"how many",cn:"多少",ph:"/haʊ /ˈmeni/",unit:4},
        {en:"colour",cn:"颜色",ph:"/ˈkʌlə(r)/",unit:4},
        {en:"everywhere",cn:"到处",ph:"/ˈevriweə(r)/",unit:4},
        {en:"fruit",cn:"水果",ph:"/fruːt/",unit:5},
        {en:"apple",cn:"苹果",ph:"/ˈæpl/",unit:5},
        {en:"banana",cn:"香蕉",ph:"/bəˈnɑːnə/",unit:5},
        {en:"orange",cn:"橙子",ph:"/ˈɒrɪndʒ/",unit:5},
        {en:"pear",cn:"梨",ph:"/peə(r)/",unit:5},
        {en:"grape",cn:"葡萄",ph:"/ɡreɪp/",unit:5},
        {en:"some",cn:"一些",ph:"/sʌm/",unit:5},
        {en:"box",cn:"盒子",ph:"/bɒks/",unit:5},
        {en:"yum",cn:"味道好",ph:"/jʌm/",unit:5},
        {en:"healthy",cn:"健康的",ph:"/ˈhelθi/",unit:5},
        {en:"share",cn:"分享",ph:"/ʃeə(r)/",unit:5},
        {en:"count",cn:"数数",ph:"/kaʊnt/",unit:6},
        {en:"table",cn:"桌子",ph:"/ˈteɪbl/",unit:6},
        {en:"desk",cn:"书桌",ph:"/desk/",unit:6},
        {en:"chair",cn:"椅子",ph:"/tʃeə(r)/",unit:6},
        {en:"pencil",cn:"铅笔",ph:"/ˈpensl/",unit:6},
        {en:"pen",cn:"钢笔",ph:"/pen/",unit:6},
        {en:"ruler",cn:"直尺",ph:"/ˈruːlə(r)/",unit:6},
        {en:"eraser",cn:"橡皮",ph:"/ɪˈreɪzə(r)/",unit:6},
        {en:"crayon",cn:"蜡笔",ph:"/ˈkreɪən/",unit:6},
        {en:"bag",cn:"包",ph:"/bæɡ/",unit:6},
        {en:"help",cn:"帮助",ph:"/help/",unit:6},
    ],
    "3-2": [
        {en:"boy",cn:"男孩",ph:"/bɔɪ/",unit:1},
        {en:"girl",cn:"女孩",ph:"/ɡɜːl/",unit:1},
        {en:"today",cn:"今天",ph:"/təˈdeɪ/",unit:1},
        {en:"from",cn:"来自",ph:"/frəm/",unit:1},
        {en:"welcome",cn:"欢迎",ph:"/ˈwelkəm/",unit:1},
        {en:"back",cn:"回来",ph:"/bæk/",unit:1},
        {en:"Canada",cn:"加拿大",ph:"/ˈkænədə/",unit:1},
        {en:"China",cn:"中国",ph:"/ˈtʃaɪnə/",unit:1},
        {en:"the UK",cn:"英国",ph:"/ˌjuː ˈkeɪ/",unit:1},
        {en:"the USA",cn:"美国",ph:"/ˌjuː es ˈeɪ/",unit:1},
        {en:"student",cn:"学生",ph:"/ˈstjuːdnt/",unit:1},
        {en:"pupil",cn:"小学生",ph:"/ˈpjuːpl/",unit:1},
        {en:"teacher",cn:"教师",ph:"/ˈtʃəːtʃə(r)/",unit:1},
        {en:"man",cn:"男人",ph:"/mæn/",unit:2},
        {en:"woman",cn:"女人",ph:"/ˈwʊmən/",unit:2},
        {en:"who's",cn:"是谁",ph:"/huːz/",unit:2},
        {en:"thin",cn:"瘦的",ph:"/θɪn/",unit:3},
        {en:"fat",cn:"胖的",ph:"/fæt/",unit:3},
        {en:"tall",cn:"高的",ph:"/tɔːl/",unit:3},
        {en:"short",cn:"矮的",ph:"/ʃɔːt/",unit:3},
        {en:"long",cn:"长的",ph:"/lɒŋ/",unit:3},
        {en:"small",cn:"小的",ph:"/smɔːl/",unit:3},
        {en:"big",cn:"大的",ph:"/bɪɡ/",unit:3},
        {en:"tail",cn:"尾巴",ph:"/teɪl/",unit:3},
        {en:"giraffe",cn:"长颈鹿",ph:"/dʒəˈrɑːf/",unit:3},
        {en:"so",cn:"这么",ph:"/səʊ/",unit:3},
        {en:"children",cn:"儿童",ph:"/ˈtʃɪldrən/",unit:3},
        {en:"on",cn:"在……上面",ph:"/ɒn/",unit:4},
        {en:"in",cn:"在……里面",ph:"/ɪn/",unit:4},
        {en:"under",cn:"在……下面",ph:"/ˈʌndə(r)/",unit:4},
        {en:"chair",cn:"椅子",ph:"/tʃeə(r)/",unit:4},
        {en:"desk",cn:"书桌",ph:"/desk/",unit:4},
        {en:"cap",cn:"便帽",ph:"/kæp/",unit:4},
        {en:"ball",cn:"球",ph:"/bɔːl/",unit:4},
        {en:"car",cn:"汽车",ph:"/kɑː(r)/",unit:4},
        {en:"boat",cn:"小船",ph:"/bəʊt/",unit:4},
        {en:"map",cn:"地图",ph:"/mæp/",unit:4},
        {en:"where",cn:"在哪里",ph:"/weə(r)/",unit:4},
        {en:"silly",cn:"傻的",ph:"/ˈsɪli/",unit:4},
        {en:"strawberry",cn:"草莓",ph:"/ˈstrɔːbəri/",unit:5},
        {en:"buy",cn:"买",ph:"/baɪ/",unit:5},
        {en:"honey",cn:"亲爱的",ph:"/ˈhʌni/",unit:5},
        {en:"sorry",cn:"对不起",ph:"/ˈsɒri/",unit:5},
        {en:"eleven",cn:"十一",ph:"/ɪˈlevn/",unit:6},
        {en:"twelve",cn:"十二",ph:"/twelv/",unit:6},
        {en:"thirteen",cn:"十三",ph:"/ˌθɜːˈtiːn/",unit:6},
        {en:"fourteen",cn:"十四",ph:"/ˌfɔːˈtiːn/",unit:6},
        {en:"fifteen",cn:"十五",ph:"/ˌfɪfˈtiːn/",unit:6},
        {en:"sixteen",cn:"十六",ph:"/ˌsɪksˈtiːn/",unit:6},
        {en:"seventeen",cn:"十七",ph:"/ˌsevnˈtiːn/",unit:6},
        {en:"eighteen",cn:"十八",ph:"/ˌeɪˈtiːn/",unit:6},
        {en:"nineteen",cn:"十九",ph:"/ˌnaɪnˈtiːn/",unit:6},
        {en:"twenty",cn:"二十",ph:"/ˈtwenti/",unit:6},
        {en:"kite",cn:"风筝",ph:"/kaɪt/",unit:6},
        {en:"beautiful",cn:"美丽的",ph:"/ˈbjuːtɪfl/",unit:6},
    ],
    "4-1": [
        {en:"classroom",cn:"教室",ph:"/ˈklɑːsruːm/",unit:1},
        {en:"window",cn:"窗户",ph:"/ˈwɪndəʊ/",unit:1},
        {en:"blackboard",cn:"黑板",ph:"/ˈblækbɔːd/",unit:1},
        {en:"light",cn:"灯",ph:"/laɪt/",unit:1},
        {en:"picture",cn:"图画",ph:"/ˈpɪktʃə(r)/",unit:1},
        {en:"door",cn:"门",ph:"/dɔː(r)/",unit:1},
        {en:"teacher's desk",cn:"讲台",ph:"/ˈtiːtʃəz desk/",unit:1},
        {en:"computer",cn:"计算机",ph:"/kəmˈpjuːtə(r)/",unit:1},
        {en:"fan",cn:"风扇",ph:"/fæn/",unit:1},
        {en:"wall",cn:"墙壁",ph:"/wɔːl/",unit:1},
        {en:"floor",cn:"地板",ph:"/flɔː(r)/",unit:1},
        {en:"near",cn:"在……旁边",ph:"/nɪə(r)/",unit:1},
        {en:"clean",cn:"打扫",ph:"/kliːn/",unit:1},
        {en:"help",cn:"帮助",ph:"/help/",unit:1},
        {en:"schoolbag",cn:"书包",ph:"/ˈskuːlbæɡ/",unit:2},
        {en:"maths book",cn:"数学书",ph:"/mæθs bʊk/",unit:2},
        {en:"English book",cn:"英语书",ph:"/ˈɪŋɡlɪʃ bʊk/",unit:2},
        {en:"Chinese book",cn:"语文书",ph:"/ˌtʃaɪˈniːz bʊk/",unit:2},
        {en:"storybook",cn:"故事书",ph:"/ˈstɔːribʊk/",unit:2},
        {en:"candy",cn:"糖果",ph:"/ˈkændi/",unit:2},
        {en:"notebook",cn:"笔记本",ph:"/ˈnəʊtbʊk/",unit:2},
        {en:"toy",cn:"玩具",ph:"/tɔɪ/",unit:2},
        {en:"key",cn:"钥匙",ph:"/kiː/",unit:2},
        {en:"lost",cn:"丢失",ph:"/lɒst/",unit:2},
        {en:"so much",cn:"非常地",ph:"/səʊ mʌtʃ/",unit:2},
        {en:"cute",cn:"可爱的",ph:"/kjuːt/",unit:2},
        {en:"strong",cn:"强壮的",ph:"/strɒŋ/",unit:3},
        {en:"friendly",cn:"友好的",ph:"/ˈfrendli/",unit:3},
        {en:"quiet",cn:"安静的",ph:"/ˈkwaɪət/",unit:3},
        {en:"hair",cn:"头发",ph:"/heə(r)/",unit:3},
        {en:"shoe",cn:"鞋",ph:"/ʃuː/",unit:3},
        {en:"glasses",cn:"眼镜",ph:"/ˈɡlɑːsɪz/",unit:3},
        {en:"hat",cn:"帽子",ph:"/hæt/",unit:3},
        {en:"her",cn:"她的",ph:"/hɜː(r)/",unit:3},
        {en:"his",cn:"他的",ph:"/hɪz/",unit:3},
        {en:"bedroom",cn:"卧室",ph:"/ˈbedruːm/",unit:4},
        {en:"living room",cn:"客厅",ph:"/ˈlɪvɪŋ ruːm/",unit:4},
        {en:"study",cn:"书房",ph:"/ˈstʌdi/",unit:4},
        {en:"kitchen",cn:"厨房",ph:"/ˈkɪtʃɪn/",unit:4},
        {en:"bathroom",cn:"浴室",ph:"/ˈbɑːθruːm/",unit:4},
        {en:"bed",cn:"床",ph:"/bed/",unit:4},
        {en:"phone",cn:"电话",ph:"/fəʊn/",unit:4},
        {en:"table",cn:"桌子",ph:"/ˈteɪbl/",unit:4},
        {en:"sofa",cn:"沙发",ph:"/ˈsəʊfə/",unit:4},
        {en:"fridge",cn:"冰箱",ph:"/frɪdʒ/",unit:4},
        {en:"find",cn:"找到",ph:"/faɪnd/",unit:4},
        {en:"them",cn:"他/她/它们（宾格）",ph:"/ðəm/",unit:4},
        {en:"beef",cn:"牛肉",ph:"/biːf/",unit:5},
        {en:"chicken",cn:"鸡肉",ph:"/ˈtʃɪkɪn/",unit:5},
        {en:"noodles",cn:"面条",ph:"/ˈnuːdlz/",unit:5},
        {en:"soup",cn:"汤",ph:"/suːp/",unit:5},
        {en:"vegetable",cn:"蔬菜",ph:"/ˈvedʒtəbl/",unit:5},
        {en:"chopsticks",cn:"筷子",ph:"/ˈtʃɒpstɪks/",unit:5},
        {en:"bowl",cn:"碗",ph:"/bəʊl/",unit:5},
        {en:"fork",cn:"餐叉",ph:"/fɔːk/",unit:5},
        {en:"knife",cn:"刀",ph:"/naɪf/",unit:5},
        {en:"spoon",cn:"勺子",ph:"/spuːn/",unit:5},
        {en:"ready",cn:"准备好",ph:"/ˈredi/",unit:5},
        {en:"pass",cn:"传递",ph:"/pɑːs/",unit:5},
        {en:"parents",cn:"父母",ph:"/ˈpeərənts/",unit:6},
        {en:"cousin",cn:"同辈表亲",ph:"/ˈkʌzn/",unit:6},
        {en:"uncle",cn:"舅父；叔父等",ph:"/ˈʌŋkl/",unit:6},
        {en:"aunt",cn:"姑母；姨母等",ph:"/ɑːnt/",unit:6},
        {en:"doctor",cn:"医生",ph:"/ˈdɒktə(r)/",unit:6},
        {en:"cook",cn:"厨师",ph:"/kʊk/",unit:6},
        {en:"driver",cn:"司机",ph:"/ˈdraɪvə(r)/",unit:6},
        {en:"farmer",cn:"农民",ph:"/ˈfɑːmə(r)/",unit:6},
        {en:"nurse",cn:"护士",ph:"/nɜːs/",unit:6},
        {en:"people",cn:"人们",ph:"/ˈpiːpl/",unit:6},
        {en:"puppy",cn:"小狗",ph:"/ˈpʌpi/",unit:6},
        {en:"job",cn:"工作",ph:"/dʒɒb/",unit:6},
    ],
    "4-2": [
        {en:"sorry",cn:"对不起",ph:"/ˈsɒri/",unit:1},
        {en:"hurry up",cn:"快点",ph:"/ˈhʌri ʌp/",unit:1},
        {en:"late",cn:"迟到",ph:"/leɪt/",unit:1},
        {en:"class",cn:"课",ph:"/klɑːs/",unit:1},
        {en:"rule",cn:"规则",ph:"/ruːl/",unit:1},
        {en:"classroom",cn:"教室",ph:"/ˈklɑːsruːm/",unit:1},
        {en:"turn off",cn:"关掉",ph:"/tɜːn ɒf/",unit:1},
        {en:"light",cn:"灯",ph:"/laɪt/",unit:1},
        {en:"blackboard",cn:"黑板",ph:"/ˈblækbɔːd/",unit:1},
        {en:"desk",cn:"书桌",ph:"/desk/",unit:1},
        {en:"chair",cn:"椅子",ph:"/tʃeə(r)/",unit:1},
        {en:"tidy",cn:"整洁的",ph:"/ˈtaɪdi/",unit:1},
        {en:"music",cn:"音乐",ph:"/ˈmjuːzɪk/",unit:1},
        {en:"door",cn:"门",ph:"/dɔː(r)/",unit:1},
        {en:"window",cn:"窗",ph:"/ˈwɪndəʊ/",unit:1},
        {en:"fan",cn:"风扇",ph:"/fæn/",unit:1},
        {en:"when",cn:"当…时",ph:"/wen/",unit:1},
        {en:"understand",cn:"懂",ph:"/ˌʌndəˈstænd/",unit:1},
        {en:"wall",cn:"墙",ph:"/wɔːl/",unit:1},
        {en:"newspaper",cn:"报纸",ph:"/ˈnjuːzpeɪpə(r)/",unit:1},
        {en:"hand out",cn:"分发",ph:"/hænd aʊt/",unit:1},
        {en:"workbook",cn:"练习册",ph:"/ˈwɜːkbʊk/",unit:1},
        {en:"watch",cn:"看",ph:"/wɒtʃ/",unit:2},
        {en:"TV",cn:"电视",ph:"/ˌtiː ˈviː/",unit:2},
        {en:"homework",cn:"家庭作业",ph:"/ˈhəʊmwɜːk/",unit:2},
        {en:"first",cn:"首先",ph:"/fɜːst/",unit:2},
        {en:"wet",cn:"湿的",ph:"/wet/",unit:2},
        {en:"run",cn:"跑",ph:"/rʌn/",unit:2},
        {en:"living room",cn:"客厅",ph:"/ˈlɪvɪŋ ruːm/",unit:2},
        {en:"safe",cn:"安全的",ph:"/seɪf/",unit:2},
        {en:"word",cn:"单词",ph:"/wɜːd/",unit:2},
        {en:"wash",cn:"洗",ph:"/wɒʃ/",unit:2},
        {en:"helpful",cn:"有帮助的",ph:"/ˈhelpfl/",unit:2},
        {en:"loud",cn:"大声的",ph:"/laɪd/",unit:2},
        {en:"sleep",cn:"睡觉",ph:"/sliːp/",unit:2},
        {en:"bedroom",cn:"卧室",ph:"/ˈbedruːm/",unit:2},
        {en:"kitchen",cn:"厨房",ph:"/ˈkɪtʃɪn/",unit:2},
        {en:"study",cn:"书房",ph:"/ˈstʌdi/",unit:2},
        {en:"bathroom",cn:"浴室",ph:"/ˈbɑːθruːm/",unit:2},
        {en:"think",cn:"想",ph:"/θɪŋk/",unit:2},
        {en:"work",cn:"工作",ph:"/wɜːk/",unit:3},
        {en:"hard",cn:"努力地",ph:"/hɑːd/",unit:3},
        {en:"follow",cn:"遵循",ph:"/ˈfɒləʊ/",unit:3},
        {en:"feel",cn:"觉得",ph:"/fiːl/",unit:3},
        {en:"over",cn:"结束",ph:"/ˈəʊvə(r)/",unit:3},
        {en:"kid",cn:"小孩",ph:"/kɪd/",unit:3},
        {en:"dinner",cn:"正餐",ph:"/ˈdɪnə(r)/",unit:3},
        {en:"art",cn:"美术",ph:"/ɑːt/",unit:3},
        {en:"lunch",cn:"午餐",ph:"/lʌntʃ/",unit:3},
        {en:"maths",cn:"数学",ph:"/mæθs/",unit:3},
        {en:"get up",cn:"起床",ph:"/ɡet ʌp/",unit:3},
        {en:"go to school",cn:"上学",ph:"/ɡəʊ tu skuːl/",unit:3},
        {en:"go home",cn:"回家",ph:"/ɡəʊ həʊm/",unit:3},
        {en:"go to bed",cn:"上床睡觉",ph:"/ɡəʊ tu bed/",unit:3},
        {en:"want",cn:"想要",ph:"/wɒnt/",unit:3},
        {en:"clock",cn:"钟",ph:"/klɒk/",unit:3},
        {en:"minute",cn:"分钟",ph:"/ˈmɪnɪt/",unit:3},
        {en:"trousers",cn:"裤子",ph:"/ˈtraʊzəz/",unit:4},
        {en:"pair",cn:"一条/双",ph:"/peə(r)/",unit:4},
        {en:"clothes",cn:"衣服",ph:"/kləʊðz/",unit:4},
        {en:"shorts",cn:"短裤",ph:"/ʃɔːts/",unit:4},
        {en:"jacket",cn:"夹克",ph:"/ˈdʒækɪt/",unit:4},
        {en:"skirt",cn:"裙子",ph:"/skɜːt/",unit:4},
        {en:"expensive",cn:"昂贵的",ph:"/ɪkˈspensɪv/",unit:4},
        {en:"cheap",cn:"便宜的",ph:"/tʃiːp/",unit:4},
        {en:"shoe",cn:"鞋",ph:"/ʃuː/",unit:4},
        {en:"beautiful",cn:"美丽的",ph:"/ˈbjuːtɪfl/",unit:4},
        {en:"sunglasses",cn:"太阳镜",ph:"/ˈsʌnɡlɑːsɪz/",unit:4},
        {en:"free",cn:"免费的",ph:"/friː/",unit:4},
        {en:"size",cn:"尺寸",ph:"/saɪz/",unit:4},
        {en:"cow",cn:"奶牛",ph:"/kaʊ/",unit:5},
        {en:"horse",cn:"马",ph:"/hɔːs/",unit:5},
        {en:"sheep",cn:"绵羊",ph:"/ʃiːp/",unit:5},
        {en:"pig",cn:"猪",ph:"/pɪɡ/",unit:5},
        {en:"chicken",cn:"鸡肉",ph:"/ˈtʃɪkɪn/",unit:5},
        {en:"tomato",cn:"西红柿",ph:"/təˈmɑːtəʊ/",unit:5},
        {en:"bee",cn:"蜜蜂",ph:"/biː/",unit:5},
        {en:"mouse",cn:"老鼠",ph:"/maʊs/",unit:5},
        {en:"carrot",cn:"胡萝卜",ph:"/ˈkærət/",unit:5},
        {en:"potato",cn:"土豆",ph:"/pəˈteɪtəʊ/",unit:5},
        {en:"green bean",cn:"四季豆",ph:"/biːn/",unit:5},
        {en:"feed",cn:"喂养",ph:"/fiːd/",unit:6},
        {en:"pick",cn:"摘",ph:"/pɪk/",unit:6},
        {en:"milk",cn:"挤奶",ph:"/mɪlk/",unit:6},
        {en:"knife",cn:"刀",ph:"/naɪf/",unit:6},
        {en:"fork",cn:"餐叉",ph:"/fɔːk/",unit:6},
        {en:"chopstick",cn:"筷子",ph:"/ˈtʃɒpstɪk/",unit:6},
        {en:"waste",cn:"浪费",ph:"/weɪst/",unit:6},
        {en:"food",cn:"食物",ph:"/fuːd/",unit:6},
        {en:"delicious",cn:"美味的",ph:"/ɪˈlɪʃəs/",unit:6},
        {en:"bowl",cn:"碗",ph:"/bəʊl/",unit:6},
        {en:"spoon",cn:"勺子",ph:"/spuːn/",unit:6},
        {en:"supermarket",cn:"超市",ph:"/ˈsuːpəmɑːkɪt/",unit:6},
    ],
    "5-1": [
        {en:"young",cn:"年轻的",ph:"/jʌŋ/",unit:1},
        {en:"funny",cn:"滑稽可笑的",ph:"/ˈfʌni/",unit:1},
        {en:"kind",cn:"体贴的",ph:"/kaɪnd/",unit:1},
        {en:"strict",cn:"严格的",ph:"/strɪkt/",unit:1},
        {en:"polite",cn:"有礼貌的",ph:"/pəˈlaɪt/",unit:1},
        {en:"hard-working",cn:"勤奋的",ph:"/ˌhɑːd ˈwɜːkɪŋ/",unit:1},
        {en:"helpful",cn:"愿意帮忙的",ph:"/ˈhelpfl/",unit:1},
        {en:"clever",cn:"聪明的",ph:"/ˈklevə(r)/",unit:1},
        {en:"shy",cn:"害羞的",ph:"/ʃaɪ/",unit:1},
        {en:"know",cn:"知道",ph:"/nəʊ/",unit:1},
        {en:"robot",cn:"机器人",ph:"/ˈrəʊbɒt/",unit:1},
        {en:"Monday",cn:"星期一",ph:"/ˈmʌndeɪ/",unit:2},
        {en:"Tuesday",cn:"星期二",ph:"/ˈtjuːzdeɪ/",unit:2},
        {en:"Wednesday",cn:"星期三",ph:"/ˈwednzdeɪ/",unit:2},
        {en:"Thursday",cn:"星期四",ph:"/ˈθɜːzdeɪ/",unit:2},
        {en:"Friday",cn:"星期五",ph:"/ˈfraɪdeɪ/",unit:2},
        {en:"Saturday",cn:"星期六",ph:"/ˈsætədeɪ/",unit:2},
        {en:"Sunday",cn:"星期日",ph:"/ˈsʌndeɪ/",unit:2},
        {en:"weekend",cn:"周末",ph:"/ˌwiːkˈend/",unit:2},
        {en:"wash my clothes",cn:"洗我的衣服",ph:"",unit:2},
        {en:"watch TV",cn:"看电视",ph:"",unit:2},
        {en:"do homework",cn:"做作业",ph:"",unit:2},
        {en:"read books",cn:"看书",ph:"",unit:2},
        {en:"play football",cn:"踢足球",ph:"",unit:2},
        {en:"sandwich",cn:"三明治",ph:"/ˈsænwɪtʃ/",unit:3},
        {en:"salad",cn:"蔬菜沙拉",ph:"/ˈsæləd/",unit:3},
        {en:"hamburger",cn:"汉堡包",ph:"/ˈhæmbɜːɡə(r)/",unit:3},
        {en:"ice cream",cn:"冰淇淋",ph:"/ˌaɪs ˈkriːm/",unit:3},
        {en:"tea",cn:"茶",ph:"/tiː/",unit:3},
        {en:"fresh",cn:"新鲜的",ph:"/freʃ/",unit:3},
        {en:"healthy",cn:"健康的",ph:"/ˈhelθi/",unit:3},
        {en:"delicious",cn:"美味的",ph:"/dɪˈlɪʃəs/",unit:3},
        {en:"hot",cn:"辣的",ph:"/hɒt/",unit:3},
        {en:"sweet",cn:"甜的",ph:"/sweet/",unit:3},
        {en:"favourite",cn:"最喜爱的",ph:"/ˈfeɪvərɪt/",unit:3},
        {en:"sing English songs",cn:"唱英文歌曲",ph:"",unit:4},
        {en:"play the pipa",cn:"弹琵琶",ph:"",unit:4},
        {en:"do kung fu",cn:"打功夫",ph:"",unit:4},
        {en:"draw cartoons",cn:"画漫画",ph:"",unit:4},
        {en:"cook",cn:"烹饪",ph:"/kʊk/",unit:4},
        {en:"swim",cn:"游泳",ph:"/swɪm/",unit:4},
        {en:"speak English",cn:"说英语",ph:"",unit:4},
        {en:"play basketball",cn:"打篮球",ph:"",unit:4},
        {en:"clock",cn:"时钟",ph:"/klɒk/",unit:5},
        {en:"plant",cn:"植物",ph:"/plɑːnt/",unit:5},
        {en:"water bottle",cn:"水瓶",ph:"",unit:5},
        {en:"bike",cn:"自行车",ph:"/baɪk/",unit:5},
        {en:"photo",cn:"照片",ph:"/ˈfəʊtəʊ/",unit:5},
        {en:"beside",cn:"在…旁边",ph:"/bɪˈsaɪd/",unit:5},
        {en:"between",cn:"在…中间",ph:"/bɪˈtwiːn/",unit:5},
        {en:"behind",cn:"在…后面",ph:"/bɪˈhaɪnd/",unit:5},
        {en:"above",cn:"在…上方",ph:"/əˈbʌv/",unit:5},
        {en:"in front of",cn:"在…前面",ph:"",unit:5},
        {en:"forest",cn:"森林",ph:"/ˈfɒrɪst/",unit:6},
        {en:"river",cn:"河流",ph:"/ˈrɪvə(r)/",unit:6},
        {en:"lake",cn:"湖泊",ph:"/leɪk/",unit:6},
        {en:"mountain",cn:"高山",ph:"/ˈmaʊntən/",unit:6},
        {en:"hill",cn:"小山",ph:"/hɪl/",unit:6},
        {en:"bridge",cn:"桥",ph:"/brɪdʒ/",unit:6},
        {en:"village",cn:"村庄",ph:"/ˈvɪlɪdʒ/",unit:6},
        {en:"house",cn:"房屋",ph:"/haʊs/",unit:6},
    ],
    "5-2": [
        {en:"eat breakfast",cn:"吃早饭",ph:"",unit:1},
        {en:"have class",cn:"上课",ph:"",unit:1},
        {en:"play sports",cn:"进行体育运动",ph:"",unit:1},
        {en:"clean my room",cn:"打扫房间",ph:"",unit:1},
        {en:"go for a walk",cn:"散步",ph:"",unit:1},
        {en:"go shopping",cn:"去购物",ph:"",unit:1},
        {en:"spring",cn:"春天",ph:"/sprɪŋ/",unit:2},
        {en:"summer",cn:"夏天",ph:"/ˈsʌmə(r)/",unit:2},
        {en:"autumn",cn:"秋天",ph:"/ˈɔːtəm/",unit:2},
        {en:"winter",cn:"冬天",ph:"/ˈwɪntə(r)/",unit:2},
        {en:"picnic",cn:"野餐",ph:"/ˈpɪknɪk/",unit:2},
        {en:"January",cn:"一月",ph:"",unit:3},
        {en:"February",cn:"二月",ph:"",unit:3},
        {en:"March",cn:"三月",ph:"",unit:3},
        {en:"April",cn:"四月",ph:"",unit:3},
        {en:"May",cn:"五月",ph:"",unit:3},
        {en:"June",cn:"六月",ph:"",unit:3},
        {en:"July",cn:"七月",ph:"",unit:3},
        {en:"August",cn:"八月",ph:"",unit:3},
        {en:"September",cn:"九月",ph:"",unit:3},
        {en:"October",cn:"十月",ph:"",unit:3},
        {en:"November",cn:"十一月",ph:"",unit:3},
        {en:"December",cn:"十二月",ph:"",unit:3},
        {en:"first",cn:"第一",ph:"",unit:4},
        {en:"second",cn:"第二",ph:"",unit:4},
        {en:"third",cn:"第三",ph:"",unit:4},
        {en:"fourth",cn:"第四",ph:"",unit:4},
        {en:"fifth",cn:"第五",ph:"",unit:4},
        {en:"twelfth",cn:"第十二",ph:"",unit:4},
        {en:"twentieth",cn:"第二十",ph:"",unit:4},
        {en:"mine",cn:"我的",ph:"/maɪn/",unit:5},
        {en:"yours",cn:"你的",ph:"/jɔːz/",unit:5},
        {en:"his",cn:"他的",ph:"/hɪz/",unit:5},
        {en:"hers",cn:"她的",ph:"/hɜːz/",unit:5},
        {en:"theirs",cn:"他们的",ph:"/ðeəz/",unit:5},
        {en:"ours",cn:"我们的",ph:"/ˈaʊəz/",unit:5},
        {en:"keep",cn:"保持",ph:"/kiːp/",unit:6},
        {en:"quietly",cn:"安静地",ph:"/ˈkwaɪətli/",unit:6},
        {en:"anything",cn:"任何事物",ph:"/ˈeniθɪŋ/",unit:6},
        {en:"take turns",cn:"轮流",ph:"",unit:6},
    ],
    "6-1": [
        {en:"museum",cn:"博物馆",ph:"/mjuˈziːəm/",unit:1},
        {en:"post office",cn:"邮局",ph:"",unit:1},
        {en:"bookstore",cn:"书店",ph:"/ˈbʊkstɔː(r)/",unit:1},
        {en:"cinema",cn:"电影院",ph:"/ˈɪnəmə/",unit:1},
        {en:"hospital",cn:"医院",ph:"/ˈhɒspɪtl/",unit:1},
        {en:"crossing",cn:"十字路口",ph:"/ˈkrɒsɪŋ/",unit:1},
        {en:"straight",cn:"笔直地",ph:"/streɪt/",unit:1},
        {en:"left",cn:"左",ph:"/left/",unit:1},
        {en:"right",cn:"右",ph:"/raɪt/",unit:1},
        {en:"turn",cn:"转弯",ph:"/tɜːn/",unit:1},
        {en:"subway",cn:"地铁",ph:"/ˈsʌbweɪ/",unit:2},
        {en:"train",cn:"火车",ph:"/treɪn/",unit:2},
        {en:"taxi",cn:"出租车",ph:"/ˈtæksi/",unit:2},
        {en:"ship",cn:"船",ph:"/ʃɪp/",unit:2},
        {en:"plane",cn:"飞机",ph:"/pleɪn/",unit:2},
        {en:"foot",cn:"脚",ph:"/fʊt/",unit:2},
        {en:"slow down",cn:"慢下来",ph:"",unit:2},
        {en:"stop",cn:"停下",ph:"/stɒp/",unit:2},
        {en:"attention",cn:"注意",ph:"/əˈtenʃn/",unit:2},
        {en:"helmet",cn:"头盔",ph:"/ˈhelmɪt/",unit:2},
        {en:"visit",cn:"拜访",ph:"/ˈvɪzɪt/",unit:3},
        {en:"film",cn:"电影",ph:"/fɪlm/",unit:3},
        {en:"trip",cn:"旅行",ph:"/trɪp/",unit:3},
        {en:"tonight",cn:"今晚",ph:"/təˈnaɪt/",unit:3},
        {en:"tomorrow",cn:"明天",ph:"/təˈmɒrəʊ/",unit:3},
        {en:"dictionary",cn:"词典",ph:"/ˈdɪkʃənri/",unit:3},
        {en:"comic book",cn:"漫画书",ph:"",unit:3},
        {en:"word book",cn:"单词本",ph:"",unit:3},
        {en:"studies",cn:"学习(三单)",ph:"/ˈstʌdiz/",unit:4},
        {en:"puzzle",cn:"谜",ph:"/ˈpʌzl/",unit:4},
        {en:"hiking",cn:"远足",ph:"/ˈhaɪkɪŋ/",unit:4},
        {en:"hobby",cn:"爱好",ph:"/ˈhɒbi/",unit:4},
        {en:"jasmine",cn:"茉莉",ph:"/ˈdʒæzmɪn/",unit:4},
        {en:"idea",cn:"想法",ph:"/aɪˈdɪə/",unit:4},
        {en:"join",cn:"加入",ph:"/dʒɔɪn/",unit:4},
        {en:"factory",cn:"工厂",ph:"/ˈfæktri/",unit:5},
        {en:"worker",cn:"工人",ph:"/ˈwɜːkə(r)/",unit:5},
        {en:"postman",cn:"邮递员",ph:"/ˈpəʊstmən/",unit:5},
        {en:"businessman",cn:"商人",ph:"/ˈbɪznəsmæn/",unit:5},
        {en:"scientist",cn:"科学家",ph:"/ˈsaɪəntɪst/",unit:5},
        {en:"pilot",cn:"飞行员",ph:"/ˈpaɪlət/",unit:5},
        {en:"coach",cn:"教练",ph:"/kəʊtʃ/",unit:5},
        {en:"police officer",cn:"警察",ph:"",unit:5},
        {en:"angry",cn:"生气的",ph:"/ˈæŋɡri/",unit:6},
        {en:"afraid",cn:"害怕的",ph:"/əˈfreɪd/",unit:6},
        {en:"sad",cn:"悲伤的",ph:"/sæd/",unit:6},
        {en:"worried",cn:"担心的",ph:"/ˈwʌrid/",unit:6},
        {en:"happy",cn:"高兴的",ph:"/ˈhæpi/",unit:6},
        {en:"doctor",cn:"医生",ph:"/ˈdɒktə(r)/",unit:6},
        {en:"breath",cn:"呼吸",ph:"/breθ/",unit:6},
    ],
    "6-2": [
        {en:"younger",cn:"更年轻的",ph:"",unit:1},
        {en:"older",cn:"更年长的",ph:"",unit:1},
        {en:"taller",cn:"更高的",ph:"",unit:1},
        {en:"shorter",cn:"更矮的",ph:"",unit:1},
        {en:"longer",cn:"更长的",ph:"",unit:1},
        {en:"thinner",cn:"更瘦的",ph:"",unit:1},
        {en:"heavier",cn:"更重的",ph:"",unit:1},
        {en:"stronger",cn:"更强壮的",ph:"",unit:1},
        {en:"cleaned",cn:"打扫(过去式)",ph:"",unit:2},
        {en:"washed",cn:"洗(过去式)",ph:"",unit:2},
        {en:"watched",cn:"看(过去式)",ph:"",unit:2},
        {en:"stayed",cn:"停留(过去式)",ph:"",unit:2},
        {en:"drank",cn:"喝(过去式)",ph:"",unit:2},
        {en:"saw",cn:"看见(过去式)",ph:"",unit:2},
        {en:"read",cn:"读(过去式)",ph:"",unit:2},
        {en:"had",cn:"有(过去式)",ph:"",unit:2},
        {en:"slept",cn:"睡觉(过去式)",ph:"",unit:2},
        {en:"went",cn:"去(过去式)",ph:"",unit:3},
        {en:"rode",cn:"骑(过去式)",ph:"",unit:3},
        {en:"hurt",cn:"受伤(过去式)",ph:"",unit:3},
        {en:"ate",cn:"吃(过去式)",ph:"",unit:3},
        {en:"took pictures",cn:"照相(过去式)",ph:"",unit:3},
        {en:"beach",cn:"海滩",ph:"/biːtʃ/",unit:3},
        {en:"dining hall",cn:"餐厅",ph:"",unit:4},
        {en:"gym",cn:"体育馆",ph:"/dʒɪm/",unit:4},
        {en:"grass",cn:"草坪",ph:"/ɡrɑːs/",unit:4},
        {en:"star",cn:"星星",ph:"/stɑː(r)/",unit:4},
        {en:"different",cn:"不同的",ph:"/ˈdɪfrənt/",unit:4},
        {en:"ago",cn:"以前",ph:"/əˈɡəʊ/",unit:4},
    ],
};

var UNIT_COUNTS = {
    "3-1": [20, 18, 13, 11, 11, 11],
    "3-2": [13, 3, 11, 12, 4, 12],
    "4-1": [14, 12, 9, 12, 12, 12],
    "4-2": [22, 18, 17, 13, 11, 12],
    "5-1": [11, 13, 11, 8, 10, 8],
    "5-2": [6, 5, 12, 7, 6, 4],
    "6-1": [10, 10, 8, 7, 8, 7],
    "6-2": [8, 9, 6, 6, 0, 0],
};

// 词汇统计
var VOCAB_STATS = {
    "3-1": 84,
    "3-2": 55,
    "4-1": 71,
    "4-2": 93,
    "5-1": 61,
    "5-2": 40,
    "6-1": 50,
    "6-2": 29
};
var TOTAL_WORDS = 483;
