// PEP Primary English Vocabulary
// Source: 人教PET2024版小学英语.docx | Generated: 2026-04-17

var LOCAL_VOCAB_PEP = {
  'G3U1': { // 三年级上册 (Grade 3 Semester 1) 68 words
    name: '三年级上册',
    nameEn: "Grade 3 Semester 1",
    units: {
      // Unit 1: Ms Ms Ms /mɪz/ /mɪz/ 女士（用于女姓姓名前，不指明婚否） 女士（用于女姓姓名前，
      'U01': [
        {rank:1,word:'Ms',phonetic:"/mɪz/",trans:"女士（用于女姓姓名前，不指明婚否）"},
        {rank:2,word:'old',phonetic:"/əʊld/",trans:"……岁的；老的"},
        {rank:3,word:'how old',phonetic:"/haʊ əʊld/",trans:"几岁"},
        {rank:4,word:'too',phonetic:"/tuː/",trans:"也；太"},
        {rank:5,word:'friend',phonetic:"/frend/",trans:"朋友"},
        {rank:6,word:'our',phonetic:"/ˈaʊə(r)/",trans:"我们的"},
        {rank:7,word:'school',phonetic:"/skuːl/",trans:"学校"},
        {rank:8,word:'morning',phonetic:"/ˈmɔːnɪŋ/",trans:"早晨；上午"},
        {rank:9,word:'afternoon',phonetic:"/ˌɑːftəˈnuːn/",trans:"下午"},
        {rank:10,word:'great',phonetic:"/ɡreɪt/",trans:"太棒了；伟大的"},
        {rank:11,word:'nice',phonetic:"/naɪs/",trans:"令人愉快的"},
        {rank:12,word:'meet',phonetic:"/miːt/",trans:"遇见；结识"},
      ],
      // Unit 2: family family family /ˈfæməli/ /ˈfæməli/ 家庭；家人 家庭；
      'U02': [
        {rank:1,word:'family',phonetic:"/ˈfæməli/",trans:"家庭；家人"},
        {rank:2,word:'mother',phonetic:"/ˈmʌðə(r)/",trans:"母亲；妈妈"},
        {rank:3,word:'dad',phonetic:"/dæd/",trans:"爸爸"},
        {rank:4,word:'mum',phonetic:"/mʌm/",trans:"妈妈"},
        {rank:5,word:'grandfather',phonetic:"/ˈɡrænfɑːðə(r)/",trans:"爷爷；外公"},
        {rank:6,word:'grandmother',phonetic:"/ˈɡrænmʌðə(r)/",trans:"奶奶；外婆"},
        {rank:7,word:'grandpa',phonetic:"/ˈɡrænpɑː/",trans:"爷爷；外公"},
        {rank:8,word:'grandma',phonetic:"/ˈɡrænmɑː/",trans:"奶奶；外婆"},
        {rank:9,word:'baby',phonetic:"/ˈbeɪbi/",trans:"婴儿"},
        {rank:10,word:'me',phonetic:"/miː/",trans:"我（宾格）"},
        {rank:11,word:'sister',phonetic:"/ˈsɪstə(r)/",trans:"姐；妹"},
        {rank:12,word:'brother',phonetic:"/ˈbrʌðə(r)/",trans:"兄；弟"},
        {rank:13,word:'have',phonetic:"/hæv/",trans:"有；吃"},
        {rank:14,word:'big',phonetic:"/bɪɡ/",trans:"大的"},
        {rank:15,word:'small',phonetic:"/smɔːl/",trans:"小的"},
        {rank:16,word:'love',phonetic:"/lʌv/",trans:"爱"},
      ],
      // Unit 3: pet pet pet /pet/ /pet/ 宠物 宠物
      'U03': [
        {rank:1,word:'pet',phonetic:"/pet/",trans:"宠物"},
        {rank:2,word:'cat',phonetic:"/kæt/",trans:"猫"},
        {rank:3,word:'dog',phonetic:"/dɒɡ/",trans:"狗"},
        {rank:4,word:'fish',phonetic:"/fɪʃ/",trans:"鱼"},
        {rank:5,word:'bird',phonetic:"/bɜːd/",trans:"鸟"},
        {rank:6,word:'rabbit',phonetic:"/ˈræbɪt/",trans:"兔子"},
        {rank:7,word:'listen',phonetic:"/ˈlɪsn/",trans:"听"},
        {rank:8,word:'sing',phonetic:"/sɪŋ/",trans:"唱"},
        {rank:9,word:'dance',phonetic:"/dɑːns/",trans:"跳舞"},
        {rank:10,word:'what',phonetic:"/wɒt/",trans:"什么"},
        {rank:11,word:'cute',phonetic:"/kjuːt/",trans:"可爱的"},
      ],
      // Unit 4: plant plant plant /plɑːnt/ /plɑːnt/ 植物 植物
      'U04': [
        {rank:1,word:'plant',phonetic:"/plɑːnt/",trans:"植物"},
        {rank:2,word:'grass',phonetic:"/ɡrɑːs/",trans:"草"},
        {rank:3,word:'tree',phonetic:"/triː/",trans:"树"},
        {rank:4,word:'sun',phonetic:"/sʌn/",trans:"太阳"},
        {rank:5,word:'water',phonetic:"/ˈwɔːtə(r)/",trans:"水；浇水"},
        {rank:6,word:'see',phonetic:"/siː/",trans:"看见"},
        {rank:7,word:'many',phonetic:"/ˈmeni/",trans:"许多"},
        {rank:8,word:'how many',phonetic:"/haʊ /ˈmeni/",trans:"多少"},
        {rank:9,word:'colour',phonetic:"/ˈkʌlə(r)/",trans:"颜色"},
        {rank:10,word:'everywhere',phonetic:"/ˈevriweə(r)/",trans:"到处"},
      ],
      // Unit 5: fruit fruit fruit /fruːt/ /fruːt/ 水果 水果
      'U05': [
        {rank:1,word:'fruit',phonetic:"/fruːt/",trans:"水果"},
        {rank:2,word:'orange',phonetic:"/ˈɒrɪndʒ/",trans:"橙子"},
        {rank:3,word:'pear',phonetic:"/peə(r)/",trans:"梨"},
        {rank:4,word:'grape',phonetic:"/ɡreɪp/",trans:"葡萄"},
        {rank:5,word:'some',phonetic:"/sʌm/",trans:"一些"},
        {rank:6,word:'box',phonetic:"/bɒks/",trans:"盒子；箱子"},
        {rank:7,word:'yum',phonetic:"/jʌm/",trans:"味道好"},
        {rank:8,word:'healthy',phonetic:"/ˈhelθi/",trans:"健康的"},
        {rank:9,word:'share',phonetic:"/ʃeə(r)/",trans:"分享"},
      ],
      // Unit 6: count count count /kaʊnt/ /kaʊnt/ 数数 数数
      'U06': [
        {rank:1,word:'count',phonetic:"/kaʊnt/",trans:"数数"},
        {rank:2,word:'desk',phonetic:"/desk/",trans:"书桌"},
        {rank:3,word:'chair',phonetic:"/tʃeə(r)/",trans:"椅子"},
        {rank:4,word:'pencil',phonetic:"/ˈpensl/",trans:"铅笔"},
        {rank:5,word:'pen',phonetic:"/pen/",trans:"钢笔"},
        {rank:6,word:'ruler',phonetic:"/ˈruːlə(r)/",trans:"直尺"},
        {rank:7,word:'eraser',phonetic:"/ɪˈreɪzə(r)/",trans:"橡皮"},
        {rank:8,word:'crayon',phonetic:"/ˈkreɪən/",trans:"蜡笔"},
        {rank:9,word:'bag',phonetic:"/bæɡ/",trans:"包"},
        {rank:10,word:'help',phonetic:"/help/",trans:"帮助"},
      ],
    },
  },
  'G3U7': { // 三年级下册 (Grade 3 Semester 2) 77 words
    name: '三年级下册',
    nameEn: "Grade 3 Semester 2",
    units: {
      // Unit 1: boy boy boy /bɔɪ/ /bɔɪ/ 男孩 男孩
      'U01': [
        {rank:1,word:'boy',phonetic:"/bɔɪ/",trans:"男孩"},
        {rank:2,word:'girl',phonetic:"/ɡɜːl/",trans:"女孩"},
        {rank:3,word:'today',phonetic:"/təˈdeɪ/",trans:"今天"},
        {rank:4,word:'new',phonetic:"/njuː/",trans:"新的"},
        {rank:5,word:'friend',phonetic:"/frend/",trans:"朋友"},
        {rank:6,word:'from',phonetic:"/frəm/",trans:"来自"},
        {rank:7,word:'welcome',phonetic:"/ˈwelkəm/",trans:"欢迎"},
        {rank:8,word:'back',phonetic:"/bæk/",trans:"回来；后面"},
        {rank:9,word:'Canada',phonetic:"/ˈkænədə/",trans:"加拿大"},
        {rank:10,word:'China',phonetic:"/ˈtʃaɪnə/",trans:"中国"},
        {rank:11,word:'the UK',phonetic:"/ˌjuː ˈkeɪ/",trans:"英国"},
        {rank:12,word:'the USA',phonetic:"/ˌjuː es ˈeɪ/",trans:"美国"},
        {rank:13,word:'student',phonetic:"/ˈstjuːdnt/",trans:"学生"},
        {rank:14,word:'pupil',phonetic:"/ˈpjuːpl/",trans:"小学生"},
        {rank:15,word:'teacher',phonetic:"/ˈtʃəːtʃə(r)/",trans:"教师"},
      ],
      // Unit 2: man man man /mæn/ /mæn/ 男人 男人
      'U02': [
        {rank:1,word:'man',phonetic:"/mæn/",trans:"男人"},
        {rank:2,word:'woman',phonetic:"/ˈwʊmən/",trans:"女人"},
        {rank:3,word:'father',phonetic:"/ˈfɑːðə(r)/",trans:"父亲；爸爸"},
        {rank:4,word:'dad',phonetic:"/dæd/",trans:"爸爸（口语）"},
        {rank:5,word:'mother',phonetic:"/ˈmʌðə(r)/",trans:"母亲；妈妈"},
        {rank:6,word:'mum',phonetic:"/mʌm/",trans:"妈妈（口语）"},
        {rank:7,word:'grandfather',phonetic:"/ˈɡrænfɑːðə(r)/",trans:"祖父；外祖父"},
        {rank:8,word:'grandpa',phonetic:"/ˈɡrænpɑː/",trans:"爷爷；外公"},
        {rank:9,word:'grandmother',phonetic:"/ˈɡrænmʌðə(r)/",trans:"祖母；外祖母"},
        {rank:10,word:'grandma',phonetic:"/ˈɡrænmɑː/",trans:"奶奶；外婆"},
        {rank:11,word:'brother',phonetic:"/ˈbrʌðə(r)/",trans:"兄；弟"},
        {rank:12,word:'sister',phonetic:"/ˈsɪstə(r)/",trans:"姐；妹"},
        {rank:13,word:'family',phonetic:"/ˈfæməli/",trans:"家庭；家人"},
        {rank:14,word:'who\'s (who is)',phonetic:"/huːz/",trans:"是谁"},
      ],
      // Unit 3: thin thin thin /θɪn/ /θɪn/ 瘦的 瘦的
      'U03': [
        {rank:1,word:'thin',phonetic:"/θɪn/",trans:"瘦的"},
        {rank:2,word:'fat',phonetic:"/fæt/",trans:"胖的"},
        {rank:3,word:'tall',phonetic:"/tɔːl/",trans:"高的"},
        {rank:4,word:'short',phonetic:"/ʃɔːt/",trans:"矮的；短的"},
        {rank:5,word:'long',phonetic:"/lɒŋ/",trans:"长的"},
        {rank:6,word:'small',phonetic:"/smɔːl/",trans:"小的"},
        {rank:7,word:'big',phonetic:"/bɪɡ/",trans:"大的"},
        {rank:8,word:'tail',phonetic:"/teɪl/",trans:"尾巴"},
        {rank:9,word:'giraffe',phonetic:"/dʒəˈrɑːf/",trans:"长颈鹿"},
        {rank:10,word:'so',phonetic:"/səʊ/",trans:"这么；那么"},
        {rank:11,word:'children',phonetic:"/ˈtʃɪldrən/",trans:"儿童（child的复数）"},
      ],
      // Unit 4: on on on /ɒn/ /ɒn/ 在……上面 在……上面
      'U04': [
        {rank:1,word:'on',phonetic:"/ɒn/",trans:"在……上面"},
        {rank:2,word:'in',phonetic:"/ɪn/",trans:"在……里面"},
        {rank:3,word:'under',phonetic:"/ˈʌndə(r)/",trans:"在……下面"},
        {rank:4,word:'box',phonetic:"/bɒks/",trans:"盒子；箱子"},
        {rank:5,word:'desk',phonetic:"/desk/",trans:"书桌"},
        {rank:6,word:'chair',phonetic:"/tʃeə(r)/",trans:"椅子"},
        {rank:7,word:'cap',phonetic:"/kæp/",trans:"便帽"},
        {rank:8,word:'ball',phonetic:"/bɔːl/",trans:"球"},
        {rank:9,word:'car',phonetic:"/kɑː(r)/",trans:"小汽车"},
        {rank:10,word:'boat',phonetic:"/bəʊt/",trans:"小船"},
        {rank:11,word:'map',phonetic:"/mæp/",trans:"地图"},
        {rank:12,word:'toy',phonetic:"/tɔɪ/",trans:"玩具"},
        {rank:13,word:'where',phonetic:"/weə(r)/",trans:"在哪里"},
        {rank:14,word:'silly',phonetic:"/ˈsɪli/",trans:"傻的；糊涂的"},
      ],
      // Unit 5: pear pear pear /peə(r)/ /peə(r)/ 梨 梨
      'U05': [
        {rank:1,word:'pear',phonetic:"/peə(r)/",trans:"梨"},
        {rank:2,word:'banana',phonetic:"/bəˈnɑːnə/",trans:"香蕉"},
        {rank:3,word:'orange',phonetic:"/ˈɒrɪndʒ/",trans:"橙子"},
        {rank:4,word:'watermelon',phonetic:"/ˈwɔːtəmelən/",trans:"西瓜"},
        {rank:5,word:'strawberry',phonetic:"/ˈstrɔːbəri/",trans:"草莓"},
        {rank:6,word:'grape',phonetic:"/ɡreɪp/",trans:"葡萄"},
        {rank:7,word:'buy',phonetic:"/baɪ/",trans:"买"},
        {rank:8,word:'fruit',phonetic:"/fruːt/",trans:"水果"},
        {rank:9,word:'honey',phonetic:"/ˈhʌni/",trans:"亲爱的（常用作称呼）"},
        {rank:10,word:'sorry',phonetic:"/ˈsɒri/",trans:"对不起"},
      ],
      // Unit 6: eleven eleven eleven /ɪˈlevn/ /ɪˈlevn/ 十一 十一
      'U06': [
        {rank:1,word:'eleven',phonetic:"/ɪˈlevn/",trans:"十一"},
        {rank:2,word:'thirteen',phonetic:"/ˌθɜːˈtiːn/",trans:"十三"},
        {rank:3,word:'fourteen',phonetic:"/ˌfɔːˈtiːn/",trans:"十四"},
        {rank:4,word:'fifteen',phonetic:"/ˌfɪfˈtiːn/",trans:"十五"},
        {rank:5,word:'sixteen',phonetic:"/ˌsɪksˈtiːn/",trans:"十六"},
        {rank:6,word:'seventeen',phonetic:"/ˌsevnˈtiːn/",trans:"十七"},
        {rank:7,word:'eighteen',phonetic:"/ˌeɪˈtiːn/",trans:"十八"},
        {rank:8,word:'nineteen',phonetic:"/ˌnaɪnˈtiːn/",trans:"十九"},
        {rank:9,word:'twenty',phonetic:"/ˈtwenti/",trans:"二十"},
        {rank:10,word:'kite',phonetic:"/kaɪt/",trans:"风筝"},
        {rank:11,word:'beautiful',phonetic:"/ˈbjuːtɪfl/",trans:"美丽的"},
        {rank:12,word:'how many',phonetic:"/haʊ /ˈmeni/",trans:"多少"},
        {rank:13,word:'look at',phonetic:"/lʊk æt/",trans:"看……"},
      ],
    },
  },
  'G4U1': { // 四年级上册 (Grade 4 Semester 1) 103 words
    name: '四年级上册',
    nameEn: "Grade 4 Semester 1",
    units: {
      // Unit 1: classroom classroom classroom /ˈklɑːsruːm/ /ˈklɑːs
      'U01': [
        {rank:1,word:'classroom',phonetic:"/ˈklɑːsruːm/",trans:"教室"},
        {rank:2,word:'window',phonetic:"/ˈwɪndəʊ/",trans:"窗户"},
        {rank:3,word:'blackboard',phonetic:"/ˈblækbɔːd/",trans:"黑板"},
        {rank:4,word:'light',phonetic:"/laɪt/",trans:"灯；光"},
        {rank:5,word:'picture',phonetic:"/ˈpɪktʃə(r)/",trans:"图画；照片"},
        {rank:6,word:'door',phonetic:"/dɔː(r)/",trans:"门"},
        {rank:7,word:'teacher\'s desk',phonetic:"/ˈtiːtʃəz desk/",trans:"讲台"},
        {rank:8,word:'computer',phonetic:"/kəmˈpjuːtə(r)/",trans:"计算机"},
        {rank:9,word:'fan',phonetic:"/fæn/",trans:"风扇"},
        {rank:10,word:'wall',phonetic:"/wɔːl/",trans:"墙壁"},
        {rank:11,word:'floor',phonetic:"/flɔː(r)/",trans:"地板"},
        {rank:12,word:'near',phonetic:"/nɪə(r)/",trans:"在……旁边"},
        {rank:13,word:'really',phonetic:"/ˈriːəli/",trans:"真的"},
        {rank:14,word:'clean',phonetic:"/kliːn/",trans:"打扫；清洁；干净的"},
        {rank:15,word:'help',phonetic:"/help/",trans:"帮助"},
        {rank:16,word:'let\'s (let us)',phonetic:"/lets/",trans:"让我们"},
      ],
      // Unit 2: schoolbag schoolbag schoolbag /ˈskuːlbæɡ/ /ˈskuːlb
      'U02': [
        {rank:1,word:'schoolbag',phonetic:"/ˈskuːlbæɡ/",trans:"书包"},
        {rank:2,word:'maths book',phonetic:"/mæθs bʊk/",trans:"数学书"},
        {rank:3,word:'English book',phonetic:"/ˈɪŋɡlɪʃ bʊk/",trans:"英语书"},
        {rank:4,word:'Chinese book',phonetic:"/ˌtʃaɪˈniːz bʊk/",trans:"语文书"},
        {rank:5,word:'storybook',phonetic:"/ˈstɔːribʊk/",trans:"故事书"},
        {rank:6,word:'candy',phonetic:"/ˈkændi/",trans:"糖果"},
        {rank:7,word:'notebook',phonetic:"/ˈnəʊtbʊk/",trans:"笔记本"},
        {rank:8,word:'toy',phonetic:"/tɔɪ/",trans:"玩具"},
        {rank:9,word:'key',phonetic:"/kiː/",trans:"钥匙"},
        {rank:10,word:'lost',phonetic:"/lɒst/",trans:"丢失"},
        {rank:11,word:'so much',phonetic:"/səʊ mʌtʃ/",trans:"非常地"},
        {rank:12,word:'cute',phonetic:"/kjuːt/",trans:"可爱的"},
        {rank:13,word:'heavy',phonetic:"/ˈhevi/",trans:"重的"},
        {rank:14,word:'excuse me',phonetic:"/ɪkˈskjuːz miː/",trans:"打扰了；请原谅"},
      ],
      // Unit 3: strong strong strong /strɒŋ/ /strɒŋ/ 强壮的 强壮的
      'U03': [
        {rank:1,word:'strong',phonetic:"/strɒŋ/",trans:"强壮的"},
        {rank:2,word:'quiet',phonetic:"/ˈkwaɪət/",trans:"安静的"},
        {rank:3,word:'hair',phonetic:"/heə(r)/",trans:"头发"},
        {rank:4,word:'shoe',phonetic:"/ʃuː/",trans:"鞋"},
        {rank:5,word:'glasses',phonetic:"/ˈɡlɑːsɪz/",trans:"眼镜"},
        {rank:6,word:'tall',phonetic:"/tɔːl/",trans:"高的"},
        {rank:7,word:'short',phonetic:"/ʃɔːt/",trans:"矮的；短的"},
        {rank:8,word:'thin',phonetic:"/θɪn/",trans:"瘦的"},
        {rank:9,word:'right',phonetic:"/raɪt/",trans:"对的；正确的"},
        {rank:10,word:'hat',phonetic:"/hæt/",trans:"帽子"},
        {rank:11,word:'her',phonetic:"/hɜː(r)/",trans:"她的"},
        {rank:12,word:'his',phonetic:"/hɪz/",trans:"他的"},
        {rank:13,word:'or',phonetic:"/ɔː(r)/",trans:"或者"},
      ],
      // Unit 4: bedroom bedroom bedroom /ˈbedruːm/ /ˈbedruːm/ 卧室 卧
      'U04': [
        {rank:1,word:'bedroom',phonetic:"/ˈbedruːm/",trans:"卧室"},
        {rank:2,word:'living room',phonetic:"/ˈlɪvɪŋ ruːm/",trans:"客厅；起居室"},
        {rank:3,word:'study',phonetic:"/ˈstʌdi/",trans:"书房"},
        {rank:4,word:'kitchen',phonetic:"/ˈkɪtʃɪn/",trans:"厨房"},
        {rank:5,word:'bathroom',phonetic:"/ˈbɑːθruːm/",trans:"浴室；洗手间"},
        {rank:6,word:'bed',phonetic:"/bed/",trans:"床"},
        {rank:7,word:'phone',phonetic:"/fəʊn/",trans:"电话"},
        {rank:8,word:'table',phonetic:"/ˈteɪbl/",trans:"桌子"},
        {rank:9,word:'sofa',phonetic:"/ˈsəʊfə/",trans:"沙发"},
        {rank:10,word:'fridge',phonetic:"/frɪdʒ/",trans:"冰箱"},
        {rank:11,word:'find',phonetic:"/faɪnd/",trans:"找到"},
        {rank:12,word:'them',phonetic:"/ðəm/",trans:"他/她/它们（宾格）"},
        {rank:13,word:'open',phonetic:"/ˈəʊpən/",trans:"打开"},
        {rank:14,word:'look',phonetic:"/lʊk/",trans:"看"},
      ],
      // Unit 5: beef beef beef /biːf/ /biːf/ 牛肉 牛肉
      'U05': [
        {rank:1,word:'beef',phonetic:"/biːf/",trans:"牛肉"},
        {rank:2,word:'chicken',phonetic:"/ˈtʃɪkɪn/",trans:"鸡肉"},
        {rank:3,word:'noodles',phonetic:"/ˈnuːdlz/",trans:"面条"},
        {rank:4,word:'soup',phonetic:"/suːp/",trans:"汤"},
        {rank:5,word:'vegetable',phonetic:"/ˈvedʒtəbl/",trans:"蔬菜"},
        {rank:6,word:'chopsticks',phonetic:"/ˈtʃɒpstɪks/",trans:"筷子"},
        {rank:7,word:'bowl',phonetic:"/bəʊl/",trans:"碗"},
        {rank:8,word:'fork',phonetic:"/fɔːk/",trans:"餐叉"},
        {rank:9,word:'knife',phonetic:"/naɪf/",trans:"刀"},
        {rank:10,word:'spoon',phonetic:"/spuːn/",trans:"勺子"},
        {rank:11,word:'ready',phonetic:"/ˈredi/",trans:"准备好"},
        {rank:12,word:'help yourself',phonetic:"/help jɔːˈself/",trans:"请自便"},
        {rank:13,word:'pass',phonetic:"/pɑːs/",trans:"传递"},
        {rank:14,word:'try',phonetic:"/traɪ/",trans:"试一试"},
        {rank:15,word:'dinner',phonetic:"/ˈdɪnə(r)/",trans:"晚餐"},
      ],
      // Unit 6: parents parents parents /ˈpeərənts/ /ˈpeərənts/ 父母
      'U06': [
        {rank:1,word:'parents',phonetic:"/ˈpeərənts/",trans:"父母"},
        {rank:2,word:'cousin',phonetic:"/ˈkʌzn/",trans:"同辈表亲"},
        {rank:3,word:'uncle',phonetic:"/ˈʌŋkl/",trans:"舅父；叔父等"},
        {rank:4,word:'aunt',phonetic:"/ɑːnt/",trans:"姑母；姨母等"},
        {rank:5,word:'baby brother',phonetic:"/ˈbeɪbi ˈbrʌðə(r)/",trans:"婴儿小弟弟"},
        {rank:6,word:'doctor',phonetic:"/ˈdɒktə(r)/",trans:"医生"},
        {rank:7,word:'cook',phonetic:"/kʊk/",trans:"厨师"},
        {rank:8,word:'driver',phonetic:"/ˈdraɪvə(r)/",trans:"司机"},
        {rank:9,word:'farmer',phonetic:"/ˈfɑːmə(r)/",trans:"农民"},
        {rank:10,word:'nurse',phonetic:"/nɜːs/",trans:"护士"},
        {rank:11,word:'people',phonetic:"/ˈpiːpl/",trans:"人们"},
        {rank:12,word:'but',phonetic:"/bʌt/",trans:"但是"},
        {rank:13,word:'little',phonetic:"/ˈlɪtl/",trans:"小的"},
        {rank:14,word:'puppy',phonetic:"/ˈpʌpi/",trans:"小狗"},
        {rank:15,word:'job',phonetic:"/dʒɒb/",trans:"工作"},
        {rank:16,word:'basketball player',phonetic:"/ˈbɑːskɪtbɔːl ˈpleɪə/",trans:"篮球运动员"},
        {rank:17,word:'中文',phonetic:"英文",trans:"中文"},
        {rank:18,word:'一',phonetic:"eleven",trans:"十一"},
        {rank:19,word:'二',phonetic:"twelve",trans:"十二"},
        {rank:20,word:'三',phonetic:"thirteen",trans:"十三"},
        {rank:21,word:'四',phonetic:"fourteen",trans:"十四"},
        {rank:22,word:'五',phonetic:"fifteen",trans:"十五"},
        {rank:23,word:'六',phonetic:"sixteen",trans:"十六"},
        {rank:24,word:'七',phonetic:"seventeen",trans:"十七"},
        {rank:25,word:'八',phonetic:"eighteen",trans:"十八"},
        {rank:26,word:'九',phonetic:"nineteen",trans:"十九"},
        {rank:27,word:'十',phonetic:"twenty",trans:"二十"},
        {rank:28,word:'三十',phonetic:"forty",trans:"四十"},
        {rank:29,word:'五十',phonetic:"sixty",trans:"六十"},
        {rank:30,word:'七十',phonetic:"eighty",trans:"八十"},
        {rank:31,word:'九十',phonetic:"hundred",trans:"百"},
      ],
    },
  },
  'G4U7': { // 四年级下册 (Grade 4 Semester 2) 80 words
    name: '四年级下册',
    nameEn: "Grade 4 Semester 2",
    units: {
      // Unit 1: young young young /jʌŋ/ /jʌŋ/ 年轻的 年轻的
      'U01': [
        {rank:1,word:'young',phonetic:"/jʌŋ/",trans:"年轻的"},
        {rank:2,word:'funny',phonetic:"/ˈfʌni/",trans:"滑稽可笑的"},
        {rank:3,word:'kind',phonetic:"/kaɪnd/",trans:"体贴的；慈祥的"},
        {rank:4,word:'strict',phonetic:"/strɪkt/",trans:"严格的"},
        {rank:5,word:'polite',phonetic:"/pəˈlaɪt/",trans:"有礼貌的"},
        {rank:6,word:'hard-working',phonetic:"/ˌhɑːd ˈwɜːkɪŋ/",trans:"工作努力的；勤奋的"},
        {rank:7,word:'helpful',phonetic:"/ˈhelpfl/",trans:"愿意帮忙的"},
        {rank:8,word:'clever',phonetic:"/ˈklevə(r)/",trans:"聪明的"},
        {rank:9,word:'shy',phonetic:"/ʃaɪ/",trans:"害羞的"},
        {rank:10,word:'know',phonetic:"/nəʊ/",trans:"知道；了解"},
        {rank:11,word:'sometimes',phonetic:"/ˈsʌmtaɪmz/",trans:"有时"},
        {rank:12,word:'robot',phonetic:"/ˈrəʊbɒt/",trans:"机器人"},
        {rank:13,word:'finish',phonetic:"/ˈfɪnɪʃ/",trans:"完成"},
      ],
      // Unit 2: Monday Monday Monday /ˈmʌndeɪ/ /ˈmʌndeɪ/ 星期一 星期一
      'U02': [
        {rank:1,word:'Monday',phonetic:"/ˈmʌndeɪ/",trans:"星期一"},
        {rank:2,word:'Tuesday',phonetic:"/ˈtjuːzdeɪ/",trans:"星期二"},
        {rank:3,word:'Wednesday',phonetic:"/ˈwednzdeɪ/",trans:"星期三"},
        {rank:4,word:'Thursday',phonetic:"/ˈθɜːzdeɪ/",trans:"星期四"},
        {rank:5,word:'Friday',phonetic:"/ˈfraɪdeɪ/",trans:"星期五"},
        {rank:6,word:'Saturday',phonetic:"/ˈsætədeɪ/",trans:"星期六"},
        {rank:7,word:'Sunday',phonetic:"/ˈsʌndeɪ/",trans:"星期日"},
        {rank:8,word:'weekend',phonetic:"/ˌwiːkˈend/",trans:"周末"},
        {rank:9,word:'wash my clothes',phonetic:"",trans:"洗我的衣服"},
        {rank:10,word:'watch TV',phonetic:"",trans:"看电视"},
        {rank:11,word:'do homework',phonetic:"",trans:"做作业"},
        {rank:12,word:'read books',phonetic:"",trans:"看书"},
        {rank:13,word:'play football',phonetic:"",trans:"踢足球"},
        {rank:14,word:'cooking class',phonetic:"",trans:"烹饪课"},
        {rank:15,word:'often',phonetic:"/ˈɒfn/",trans:"常常"},
      ],
      // Unit 3: sandwich sandwich sandwich /ˈsænwɪtʃ/ /ˈsænwɪtʃ/ 三
      'U03': [
        {rank:1,word:'sandwich',phonetic:"/ˈsænwɪtʃ/",trans:"三明治"},
        {rank:2,word:'salad',phonetic:"/ˈsæləd/",trans:"蔬菜沙拉"},
        {rank:3,word:'hamburger',phonetic:"/ˈhæmbɜːɡə(r)/",trans:"汉堡包"},
        {rank:4,word:'ice cream',phonetic:"/ˌaɪs ˈkriːm/",trans:"冰淇淋"},
        {rank:5,word:'tea',phonetic:"/tiː/",trans:"茶"},
        {rank:6,word:'fresh',phonetic:"/freʃ/",trans:"新鲜的"},
        {rank:7,word:'healthy',phonetic:"/ˈhelθi/",trans:"健康的"},
        {rank:8,word:'delicious',phonetic:"/dɪˈlɪʃəs/",trans:"美味的"},
        {rank:9,word:'hot',phonetic:"/hɒt/",trans:"辣的；热的"},
        {rank:10,word:'sweet',phonetic:"/swiːt/",trans:"甜的"},
        {rank:11,word:'hungry',phonetic:"/ˈhʌŋɡri/",trans:"饥饿的"},
        {rank:12,word:'favourite',phonetic:"/ˈfeɪvərɪt/",trans:"最喜爱的"},
        {rank:13,word:'onion',phonetic:"/ˈʌnjən/",trans:"洋葱"},
      ],
      // Unit 4: dance dance dance /dɑːns/ /dɑːns/ 跳舞 跳舞
      'U04': [
        {rank:1,word:'dance',phonetic:"/dɑːns/",trans:"跳舞"},
        {rank:2,word:'sing English songs',phonetic:"",trans:"唱英文歌曲"},
        {rank:3,word:'play the pipa',phonetic:"",trans:"弹琵琶"},
        {rank:4,word:'do kung fu',phonetic:"",trans:"打功夫"},
        {rank:5,word:'draw cartoons',phonetic:"",trans:"画漫画"},
        {rank:6,word:'cook',phonetic:"/kʊk/",trans:"烹饪"},
        {rank:7,word:'swim',phonetic:"/swɪm/",trans:"游泳"},
        {rank:8,word:'speak English',phonetic:"",trans:"说英语"},
        {rank:9,word:'play basketball',phonetic:"",trans:"打篮球"},
        {rank:10,word:'play ping-pong',phonetic:"",trans:"打乒乓球"},
        {rank:11,word:'party',phonetic:"/ˈpɑːti/",trans:"聚会"},
        {rank:12,word:'learn',phonetic:"/lɜːn/",trans:"学；学习"},
        {rank:13,word:'any',phonetic:"/ˈeni/",trans:"任何的"},
        {rank:14,word:'problem',phonetic:"/ˈprɒbləm/",trans:"问题"},
      ],
      // Unit 5: clock clock clock /klɒk/ /klɒk/ 时钟 时钟
      'U05': [
        {rank:1,word:'clock',phonetic:"/klɒk/",trans:"时钟"},
        {rank:2,word:'plant',phonetic:"/plɑːnt/",trans:"植物"},
        {rank:3,word:'water bottle',phonetic:"",trans:"水瓶"},
        {rank:4,word:'bike',phonetic:"/baɪk/",trans:"自行车"},
        {rank:5,word:'photo',phonetic:"/ˈfəʊtəʊ/",trans:"照片"},
        {rank:6,word:'beside',phonetic:"/bɪˈsaɪd/",trans:"在……旁边"},
        {rank:7,word:'between',phonetic:"/bɪˈtwiːn/",trans:"在……中间"},
        {rank:8,word:'behind',phonetic:"/bɪˈhaɪnd/",trans:"在……后面"},
        {rank:9,word:'above',phonetic:"/əˈbʌv/",trans:"在……上方"},
        {rank:10,word:'in front of',phonetic:"",trans:"在……前面"},
        {rank:11,word:'their',phonetic:"/ðeə(r)/",trans:"他们的"},
        {rank:12,word:'lots of',phonetic:"",trans:"许多"},
        {rank:13,word:'dirty',phonetic:"/ˈdɜːti/",trans:"肮脏的"},
      ],
      // Unit 6: forest forest forest /ˈfɒrɪst/ /ˈfɒrɪst/ 森林 森林
      'U06': [
        {rank:1,word:'forest',phonetic:"/ˈfɒrɪst/",trans:"森林"},
        {rank:2,word:'river',phonetic:"/ˈrɪvə(r)/",trans:"河；河流"},
        {rank:3,word:'lake',phonetic:"/leɪk/",trans:"湖；湖泊"},
        {rank:4,word:'mountain',phonetic:"/ˈmaʊntən/",trans:"高山；山岳"},
        {rank:5,word:'hill',phonetic:"/hɪl/",trans:"小山"},
        {rank:6,word:'tree',phonetic:"/triː/",trans:"树"},
        {rank:7,word:'bridge',phonetic:"/brɪdʒ/",trans:"桥"},
        {rank:8,word:'village',phonetic:"/ˈvɪlɪdʒ/",trans:"村庄"},
        {rank:9,word:'house',phonetic:"/haʊs/",trans:"房屋"},
        {rank:10,word:'boating',phonetic:"/ˈbəʊtɪŋ/",trans:"划船"},
        {rank:11,word:'nature park',phonetic:"",trans:"自然公园"},
        {rank:12,word:'rabbit',phonetic:"/ˈræbɪt/",trans:"兔子"},
      ],
    },
  },
};

var UNIT_COUNTS = {
  'G3U1': ["U01", "U02", "U03", "U04", "U05", "U06"],
  'G3U7': ["U01", "U02", "U03", "U04", "U05", "U06"],
  'G4U1': ["U01", "U02", "U03", "U04", "U05", "U06"],
  'G4U7': ["U01", "U02", "U03", "U04", "U05", "U06"],
};