// Vietnamese Vocabulary Data - Auto-generated
var VN_VOCAB = {
  starter: [
    ["như", "作为/喜欢", "as/like", 0],
    ["tôi", "我", "I", 0],
    ["mình", "他的/我", "his/me", 0],
    ["mà", "那/那个/但", "that/but", 0],
    ["ông", "他/祖父", "grandfather", 0],
    ["là", "是/过去式/成为", "was/To be", 0],
    ["cho", "为了/对于/给", "for/give", 0],
    ["trên", "在...上/多于", "on/above", 0],
    ["là", "是/成为", "are/To be", 0],
    ["với", "和/与", "with", 0],
    ["họ", "他们/姓", "they/Surname", 0],
    ["được", "是/存在/好的", "be/Okay", 0],
    ["tại", "在", "at/in", 0],
    ["một", "一/一个", "one", 0],
    ["có", "有", "have", 0],
    ["này", "这/这个", "this", 0],
    ["từ", "从", "from", 0],
    ["bởi", "通过/由/经过", "by", 0],
    ["nóng", "热的", "hot", 0],
    ["từ", "单词/从", "word/from", 0],
    ["nhưng", "但是", "but", 0],
    ["những gì", "什么", "what", 0],
    ["một số", "一些", "some", 0],
    ["là", "是/成为", "is/To be", 0],
    ["nó", "它", "it", 0],
    ["anh", "你/哥哥", "you/Older brother", 0],
    ["hoặc", "或者", "or", 0],
    ["có", "有", "had/Have", 0],
    ["các", "这", "the", 0],
    ["của", "的/属于", "of/belong to", 0],
    ["để", "到", "to", 0],
    ["và", "和", "and", 0],
    ["một", "一个", "a/one", 0],
    ["trong", "在", "in", 0],
    ["chúng tôi", "我们", "we", 0],
    ["có thể", "能/会/或许", "can/maybe", 0],
    ["ra", "出去", "go out", 0],
    ["khác", "其他", "other", 0],
    ["là", "是/成为", "were/To be", 0],
    ["mà", "哪个/但", "which/but", 0],
    ["làm", "做", "do", 0],
    ["của họ", "他们的", "their", 0],
    ["thời gian", "时间", "time", 0],
    ["nếu", "如果", "if", 0],
    ["sẽ", "将/会/将要", "will", 0],
    ["như thế nào", "如何", "how", 0],
    ["nói", "说话", "said/speak", 0],
    ["một", "一个", "an/one", 0],
    ["môi", "每个/唇", "each/lip", 0],
    ["nói", "告诉/说话", "tell/speak", 0],
    ["không", "做/不是", "does/Are not", 0],
    ["bộ", "放", "set", 0],
    ["ba", "三", "three", 0],
    ["muốn", "想", "want", 0],
    ["không khí", "空气", "air", 0],
    ["cũng", "出色地/还", "well/also", 0],
    ["cũng", "也/还", "also", 0],
    ["chơi", "玩", "play", 0],
    ["nhỏ", "小的", "small", 0],
    ["cuối", "结尾/最后的", "end/last", 0],
    ["đặt", "放", "put", 0],
    ["nhà", "家", "home", 0],
    ["đọc", "读", "read", 0],
    ["tay", "手", "hand", 0],
    ["cổng", "港口/门", "port/gate", 0],
    ["lớn", "大的", "large/big", 0],
    ["chính tả", "拼写", "spelling", 0],
    ["thêm", "添加/更多的", "add/more", 0],
    ["thậm chí", "甚至", "even", 0],
    ["đất", "土地", "land", 0],
    ["ở đây", "这里", "here", 0],
    ["phải", "必须/正确的", "must/Right", 0],
    ["lớn", "大的", "big", 0],
    ["cao", "高的", "high", 0],
    ["như vậy", "这样的/所以", "such/so", 0],
    ["theo", "跟随/根据", "follow/according to", 0],
    ["hành động", "行为", "act", 0],
    ["lý do tại sao", "为什么", "why", 0],
    ["xin", "询问", "Ask for", 0],
    ["người đàn ông", "男人", "men/man", 0],
    ["thay đổi", "改变", "change", 0],
    ["đi", "去了", "went/Go", 0],
    ["ánh sáng", "光", "light", 0],
    ["loại", "种类/类型", "kind/type", 0],
    ["tắt", "离开/关", "turn off", 0],
    ["cần", "需要", "need", 0],
    ["nhà", "房子/家", "house/home", 0],
    ["hình ảnh", "图片/图像", "picture/image", 0],
    ["thử", "尝试", "try", 0],
    ["chúng tôi", "我们", "us/we", 0],
    ["một lần nữa", "再次", "once again", 0],
    ["động vật", "动物", "animal", 0],
    ["điểm", "观点", "point", 0],
    ["mẹ", "母亲/妈妈", "mother/Mom", 0],
    ["thế giới", "世界", "world", 0],
    ["gần", "靠近/附近的", "near the", 0],
    ["xây dựng", "建造", "build", 0],
    ["tự", "自己/独自一人", "self/on one's own", 0],
    ["đất", "地球/土地", "earth/land", 0],
    ["cha", "父亲", "father", 0],
    ["bất kỳ", "任何", "any", 0],
    ["mới", "新的", "new", 0],
    ["công việc", "工作", "work/job", 0],
    ["một phần", "部分", "part", 0],
    ["có", "拿/带走/有", "take/Have", 0],
    ["được", "得到/好的", "get/Okay", 0],
    ["nơi", "地方", "place", 0],
    ["thực hiện", "制成/履行", "made/perform", 0],
    ["sống", "居住/活的", "live/living", 0],
    ["nơi", "在哪里/地方", "where/place", 0],
    ["sau khi", "之后", "after", 0],
    ["trở lại", "返回", "back/return", 0],
    ["ít", "小/少的/小的", "little", 0],
    ["chỉ", "仅仅/仅有的", "only", 0],
    ["chung quanh", "圆形的/大约", "around", 0],
    ["người đàn ông", "男人", "man", 0],
    ["năm", "年", "year", 0],
    ["đến", "来了/到达", "came/arrive", 0],
    ["chương trình", "展示/程序", "show/programme", 0],
    ["mỗi", "每一个/每个", "every/each", 0],
    ["tốt", "好的", "good", 0],
    ["tôi", "我(宾格)", "me/I", 0],
    ["cung cấp cho", "给", "give", 0],
    ["của chúng tôi", "我们的", "our", 0],
    ["dưới", "在下面/以下", "under/below", 0],
    ["tên", "姓名", "name", 0],
    ["rất", "非常", "very", 0],
    ["thông qua", "通过", "through", 0],
    ["chỉ", "只是/刚刚/仅有的", "just/only", 0],
    ["hình thức", "形式", "form", 0],
    ["câu", "句子", "sentence", 0],
    ["tuyệt vời", "伟大的", "great", 0],
    ["nghi", "思考/怀疑", "think/doubt", 0],
    ["nói", "说话", "say/speak", 0],
    ["giúp", "帮助", "help", 0],
    ["thấp", "低的/短的", "low/short", 0],
    ["dòng", "线/当前的", "line/current", 0],
    ["khác nhau", "不同的", "different", 0],
    ["lần lượt", "转动/先后", "turn/one after another", 0],
    ["nguyên nhân", "原因", "cause/reason", 0],
    ["nhiều", "很多", "much", 0],
    ["có nghĩa là", "意思是/方法", "means", 0],
    ["trước", "之前", "before", 0],
    ["di chuyển", "移动", "move", 0],
    ["ngay", "正确的", "right", 0],
    ["cậu bé", "男生", "boy", 0],
    ["cũ", "老的", "old", 0],
    ["quá", "也", "too", 0],
    ["như nhau", "相同的", "same", 0],
    ["cô", "她/错过", "she/Miss", 0],
    ["tất cả", "全部", "all", 0],
    ["có", "那里/有", "there/Have", 0],
    ["khi", "当/什么时候", "when", 0],
    ["lên", "上/起来", "go up", 0],
    ["sử dụng", "使用", "use", 0],
    ["của bạn", "你的", "your", 0],
    ["cách", "方式", "way", 0],
    ["về", "关于", "about", 0],
    ["nhiều", "很多", "many/much", 0],
    ["sau đó", "然后/之后", "then/Later", 0],
    ["họ", "他们(宾格)/姓", "them/Surname", 0],
    ["viết", "写", "write", 0],
    ["sẽ", "将/会/将要", "would/will", 0],
    ["như", "喜欢", "like", 0],
    ["để", "所以/这么/到", "so/to", 0],
    ["các", "这些", "these", 0],
    ["cô", "她的/错过", "her/Miss", 0],
    ["lâu", "长的", "long", 0],
    ["làm", "制作/做", "make/do", 0],
    ["điều", "事物", "thing", 0],
    ["thấy", "看见", "see", 0],
    ["anh", "他(宾格)/哥哥", "him/Older brother", 0],
    ["hai", "二", "two", 0],
    ["có", "有", "has/Have", 0],
    ["xem", "看", "look/see", 0],
    ["hơn", "更多的/比", "more/than", 0],
    ["ngày", "天", "day", 0],
    ["có thể", "能/或许", "could/maybe", 0],
    ["đi", "去", "go", 0],
    ["đến", "来/到达", "come/arrive", 0],
    ["đã làm", "做过", "did", 0],
    ["số", "数字", "number", 0],
    ["âm thanh", "声音", "sound", 0],
    ["không có", "不/没有/无法使用", "Not available", 0],
    ["nhất", "大多数/最好的", "most/best", 0],
    ["nhân dân", "人们", "people", 0],
    ["của tôi", "我的/矿", "my/mine", 0],
    ["hơn", "结束/超过/比", "over/than", 0],
    ["biết", "知道", "know", 0],
    ["nước", "水", "water", 0],
    ["hơn", "比", "than", 0],
    ["gọi", "称呼", "call", 0],
    ["đầu tiên", "第一/首先", "Firstly", 0],
    ["người", "谁/人们", "who/People", 0],
    ["có thể", "可能/或许", "maybe", 0],
    ["xuống", "向下", "down", 0],
    ["bên", "边/旁", "beside", 0],
    ["được", "到过/好的", "been/Okay", 0],
    ["bây giờ", "现在", "now", 0],
    ["tìm", "寻找", "find", 0],
    ["đầu", "头", "head", 0],
    ["đứng", "站立", "stand", 0],
    ["riêng", "自己的/私人的", "own/private", 0],
    ["trang", "页", "page", 0],
    ["nên", "应该", "should", 0],
    ["nước", "国家/水", "country/water", 0],
    ["tìm thấy", "成立/寻找", "found/find", 0],
    ["câu trả lời", "回答", "answer", 0],
    ["trường", "学校", "school", 0],
    ["phát triển", "生长/发展", "grow/develop", 0],
    ["nghiên cứu", "学习", "study", 0],
    ["vẫn", "仍然", "still", 0],
    ["học", "学习", "learn", 0],
    ["nhà máy", "植物/工厂", "plant/factory", 0],
    ["bìa", "覆盖", "cover", 0],
    ["thực phẩm", "食物", "food", 0],
    ["ánh nắng mặt trời", "太阳/阳光", "sunshine", 0],
    ["bốn", "四", "four", 0],
    ["giữa", "之间", "between", 0],
    ["nhà nước", "状态", "state", 0],
    ["giữ", "保持/抓住", "keep/hold", 0],
    ["mắt", "眼睛", "eye", 0],
    ["không bao giờ", "绝不", "never", 0],
    ["cuối cùng", "最后的/最终的", "last/Final", 0],
    ["cho phép", "让/允许", "let/allow", 0],
    ["nghĩ", "想法/思考", "thought/think", 0],
    ["thành phố", "城市", "city", 0],
    ["cây", "树", "tree", 0],
    ["qua", "叉/通过", "cross/via", 0],
    ["trang trại", "农场", "farm", 0],
    ["cứng", "难的", "hard", 0],
    ["bắt đầu", "开始", "start/begin", 0],
    ["might", "可能", "might", 0],
    ["câu chuyện", "故事", "story", 0],
    ["cưa", "锯", "saw", 0],
    ["đến nay", "远的/到目前为止", "far/up to now", 0],
    ["biển", "海", "sea", 0],
    ["vẽ", "画", "draw", 0],
    ["còn lại", "左边/其余的", "left/remaining", 0],
    ["cuối", "晚的/最后的", "late/last", 0],
    ["chạy", "跑步", "run", 0],
    ["không", "不是", "don’t/Are not", 0],
    ["trong khi", "尽管", "while", 0],
    ["báo chí", "按", "press", 0],
    ["gần", "关闭/附近的", "close/near the", 0],
    ["đêm", "夜晚", "night", 0],
    ["thực", "真实的", "real", 0],
    ["cuộc sống", "生活", "life", 0],
    ["số", "很少/数字", "few/number", 0],
    ["phía bắc", "北", "north", 0],
    ["cuốn sách", "书", "book", 0],
    ["thực hiện", "携带/履行", "carry/perform", 0],
    ["mất", "采取了/丢失的", "took/lost", 0],
    ["khoa học", "科学", "science", 0],
    ["ăn", "吃", "eat", 0],
    ["phòng", "房间", "room", 0],
    ["người bạn", "朋友", "friend", 0],
    ["bắt đầu", "开始", "began/begin", 0],
    ["ý tưởng", "主意", "idea", 0],
    ["cá", "鱼", "fish", 0],
    ["núi", "山", "mountain", 0],
    ["ngăn chặn", "停止/防止", "stop/prevent", 0],
    ["một lần", "一次", "once", 0],
    ["cơ sở", "根据", "base", 0],
    ["nghe", "听到", "hear/listen", 0],
    ["ngựa", "马", "horse", 0],
    ["cắt", "切", "cut", 0],
    ["chắc chắn", "当然", "sure", 0],
    ["xem", "手表/看", "watch/see", 0],
    ["màu", "颜色", "color", 0],
    ["khuôn mặt", "脸", "face", 0],
    ["gỗ", "木头", "wood", 0],
    ["chính", "主要的", "main", 0],
    ["mở", "打开", "open", 0],
    ["dường như", "它似乎", "it seems", 0],
    ["cùng", "一起", "together", 0],
    ["tiếp theo", "下一个", "next", 0],
    ["trắng", "白色的", "white", 0],
    ["trẻ em", "孩子们", "children", 0],
    ["bắt đầu", "开始", "begin", 0],
    ["có", "得到/有", "got/Have", 0],
    ["đi bộ", "走", "walk", 0],
    ["Ví dụ", "例子/例如", "For example", 0],
    ["giảm bớt", "舒适/减少", "decrease", 0],
    ["giấy", "纸", "paper", 0],
    ["nhóm", "团体", "group", 0],
    ["luôn luôn", "总是", "always", 0],
    ["nhạc", "音乐", "music", 0],
    ["những", "那些/这些", "those/these", 0],
    ["cả hai", "两个都", "both", 0],
    ["đánh dấu", "标记/打钩", "mark/tick", 0],
    ["thường", "经常", "often", 0],
    ["thư", "信/字母", "letters", 0],
    ["cho đến khi", "直到", "until", 0],
    ["dặm", "英里", "mile", 0],
    ["sông", "河", "river", 0],
    ["xe", "车", "car", 0],
    ["chân", "脚", "feet/foot", 0],
    ["chăm sóc", "关心/照顾", "take care of", 0],
    ["thứ hai", "第二/周一", "second/Monday", 0],
    ["đủ", "足够的", "enough", 0],
    ["đồng bằng", "清楚的", "plain", 0],
    ["cô gái", "女孩", "girl", 0],
    ["thông thường", "通常情况下", "usual/normally", 0],
    ["trẻ", "年轻的", "young", 0],
    ["sẵn sàng", "准备好", "ready", 0],
    ["trên đây", "多于", "above", 0],
    ["bao giờ", "曾经", "ever", 0],
    ["màu đỏ", "红色的", "red", 0],
    ["danh sách", "列表", "list", 0],
    ["mặc dù", "尽管", "though/in spite of", 0],
    ["cảm thấy", "感觉", "feel", 0],
    ["nói chuyện", "讲话", "talk", 0],
    ["chim", "鸟", "bird", 0],
    ["sớm", "很快/早期的", "soon/early", 0],
    ["cơ thể", "身体", "body", 0],
    ["con chó", "狗", "dog", 0],
    ["gia đình", "家庭", "family", 0],
    ["trực tiếp", "直接的", "direct", 0],
    ["đặt ra", "姿势/出发", "pose/set out", 0],
    ["lại", "离开/再次", "leave/again", 0],
    ["bài hát", "歌曲", "song", 0],
    ["đo lường", "措施/测量", "measurement", 0],
    ["cửa", "门", "door", 0],
    ["sản phẩm", "产品", "product", 0],
    ["đen", "黑色的", "black", 0],
    ["ngắn", "短的", "short", 0],
    ["chữ số", "数字", "numeral/digits", 0],
    ["lớp", "班级", "class", 0],
    ["gió", "风", "wind", 0],
    ["câu hỏi", "问题", "question", 0],
    ["xảy ra", "发生", "happen", 0],
    ["hoàn thành", "完全的", "complete", 0],
    ["tàu", "船", "ship", 0],
    ["khu vực", "区域", "area", 0],
    ["một nửa", "一半", "half", 0],
    ["đá", "岩石/石头", "rock/stone", 0],
    ["để", "命令/到", "order/to", 0],
    ["lửa", "火", "fire", 0],
    ["nam", "南/男性", "south/male", 0],
    ["vấn đề", "问题", "problem", 0],
    ["mảnh", "片", "piece", 0],
    ["nói", "告诉/说话", "told/speak", 0],
    ["biết", "知道", "knew/know", 0],
    ["vượt qua", "经过/克服", "pass/overcome", 0],
    ["từ", "自从", "since/from", 0],
    ["đầu", "顶部/头", "top/head", 0],
    ["toàn bộ", "所有的", "whole", 0],
    ["vua", "国王", "king", 0],
    ["đường phố", "街道", "street", 0],
    ["inch", "英寸", "inches", 0],
    ["nhân", "乘/核", "multiply/core", 0],
    ["không có gì", "没有什么", "nothing", 0],
    ["Tất nhiên", "课程/当然", "Of course", 0],
    ["ở lại", "停留", "stay", 0],
    ["bánh xe", "车轮", "wheel", 0],
    ["đầy đủ", "满的", "full", 0],
    ["lực", "力量", "force", 0],
    ["màu xanh", "蓝色的/绿色的", "blue/green", 0],
    ["đối tượng", "目的", "object", 0],
    ["quyết định", "决定", "decide/decision", 0],
    ["bề mặt", "表面", "surface", 0],
    ["sâu", "深的", "deep", 0],
    ["mặt trăng", "月亮", "moon", 0],
    ["đảo", "岛", "island", 0],
    ["chân", "脚", "foot", 0],
    ["hệ thống", "系统", "system", 0],
    ["bận rộn", "忙碌的", "busy", 0],
    ["kiểm tra", "测试/查看", "test/check", 0],
    ["ghi", "记录/注意", "record/take note", 0],
    ["thuyền", "船", "boat", 0],
    ["phổ biến", "常见的/受欢迎的", "common/popular", 0],
    ["vàng", "金子/黄色的", "gold/Yellow", 0],
    ["có thể", "可能的/或许", "possible/maybe", 0],
    ["máy bay", "飞机", "plane", 0],
    ["thay", "斯蒂德/代替", "stead/replace", 0],
    ["khô", "干燥/干的", "dry/dried", 0],
    ["tự hỏi", "想知道", "wonder", 0],
    ["cười", "笑", "laugh", 0],
    ["ngàn", "千", "thousand", 0],
    ["trước", "前", "ago/before", 0],
    ["ran", "跑/然", "ran", 0],
    ["kiểm tra", "查看", "check", 0],
    ["trò chơi", "游戏", "game", 0],
    ["hình dạng", "形状", "shape", 0],
    ["đánh đồng", "等同", "equate", 0],
    ["nóng", "热的", "hot", 0],
    ["bỏ lỡ", "错过", "miss", 0],
    ["mang", "带来/携带", "brought/carry", 0],
    ["nhiệt", "热", "heat", 0],
    ["tuyết", "雪", "snow", 0],
    ["lốp xe", "轮胎", "tires", 0],
    ["mang lại", "带来", "bring", 0],
    ["vâng", "是的", "yes", 0],
    ["xa", "遥远", "distant", 0],
    ["điền", "充满", "fill", 0],
    ["đông", "东方/冬天", "east/winter", 0],
    ["sơn", "画", "paint", 0],
    ["ngôn ngữ", "语言", "language", 0],
    ["trong", "之中/在", "among/in", 0],
    ["đơn vị", "单元", "unit", 0],
    ["điện", "力量/电", "power/electricity", 0],
    ["thị trấn", "镇", "town", 0],
    ["tốt", "美好的", "fine/Good", 0],
    ["nhất định", "肯定", "certain", 0],
    ["bay", "飞", "fly", 0],
    ["giảm", "落下/减少", "fall/reduce", 0],
    ["dẫn", "带领/指导", "lead/guide", 0],
    ["kêu", "哭/称呼", "cry/call", 0],
    ["tối", "黑暗的", "dark", 0],
    ["máy", "机器", "machine", 0],
    ["ghi", "笔记/注意", "take note", 0],
    ["đợi", "等待", "wait", 0],
    ["kế hoạch", "计划", "plan", 0],
    ["con số", "数字", "figure/number", 0],
    ["sao", "星星", "star", 0],
    ["hộp", "盒子", "box", 0],
    ["danh từ", "名词", "noun", 0],
    ["lĩnh vực", "场地", "field", 0],
    ["phần còn lại", "休息/其余的部分", "the rest", 0],
    ["chính xác", "正确的/确切地", "correct/Exactly", 0],
    ["thể", "有能力的", "able/can", 0],
    ["bảng", "磅/木板", "pound/board", 0],
    ["Xong", "完毕/完成的", "done/Finished", 0],
    ["vẻ đẹp", "美丽", "beauty", 0],
    ["ổ đĩa", "驾驶", "drive", 0],
    ["đứng", "站着/站立", "stood/stand", 0],
    ["chứa", "包含", "contain", 0],
    ["trước", "正面/前", "front/before", 0],
    ["dạy", "教", "teach", 0],
    ["tuần", "星期", "week", 0],
    ["thức", "最终的/醒", "final/awake", 0],
    ["đã", "给了/使满意", "gave/Satisfied", 0],
    ["màu xanh lá cây", "绿色的", "green", 0],
    ["oh", "哦", "oh", 0],
    ["nhanh chóng", "快的", "quick", 0],
    ["phát triển", "发展", "develop", 0],
    ["đại dương", "海洋", "ocean", 0],
    ["ấm áp", "温暖的", "warm", 0],
    ["miễn phí", "自由的/免费", "free of charge", 0],
    ["phút", "分钟", "minute", 0],
    ["mạnh mẽ", "强的", "strong", 0],
    ["đặc biệt", "特别的", "special", 0],
    ["tâm", "头脑/心", "mind/heart", 0],
    ["sau", "在后面", "behind/after", 0],
    ["trong", "清除/在", "clear/in", 0],
    ["đuôi", "尾巴", "tail", 0],
    ["sản xuất", "生产", "produce/manufacture", 0],
    ["thực tế", "事实/现实", "fact/reality", 0],
    ["không gian", "空间", "space", 0],
    ["nghe", "听到", "heard/listen", 0],
    ["tốt nhất", "最好的", "best", 0],
    ["giờ", "小时", "hour", 0],
    ["tốt hơn", "更好的", "better", 0],
    ["đúng", "真的/正确的", "true/correct", 0],
    ["trong khi", "期间/尽管", "during/while", 0],
    ["trăm", "百", "hundred", 0],
    ["năm", "五/年", "five/year", 0],
    ["nhớ", "记住/错过", "remember/miss", 0],
    ["bước", "步", "step", 0],
    ["đầu", "早期的/头", "early/head", 0],
    ["giư", "抓住", "hold", 0],
    ["tây", "西方", "west", 0],
    ["mặt đất", "地面", "ground", 0],
    ["quan tâm", "兴趣/关心", "interest/care about", 0],
    ["đạt", "抵达/获得", "reach/obtain", 0],
    ["nhanh chóng", "快速地/快的", "fast/quick", 0],
    ["động từ", "动词", "verb", 0],
    ["hát", "唱歌", "sing", 0],
    ["lắng nghe", "听", "listen", 0],
    ["sáu", "六", "six", 0],
    ["bảng", "桌子/木板", "table/board", 0],
    ["du lịch", "旅行/旅游", "travel/tourism", 0],
    ["ít", "较少的/小的", "less/little", 0],
    ["buổi sáng", "早晨", "morning", 0],
    ["mười", "十", "ten", 0],
    ["đơn giản", "简单的", "simple", 0],
    ["nhiều", "一些/很多", "several/much", 0],
    ["nguyên âm", "元音", "vowels", 0],
    ["hướng", "朝向/方向", "toward/direction", 0],
    ["chiến tranh", "战争", "war", 0],
    ["đặt", "躺着/放", "lay/put", 0],
    ["chống lại", "反对", "against", 0],
    ["mô hình", "图案/模型", "pattern/model", 0],
    ["chậm", "慢的", "slow", 0],
    ["trung tâm", "中心", "center", 0],
    ["tình yêu", "爱", "love", 0],
    ["người", "人们", "person/People", 0],
    ["tiền", "钱", "money", 0],
    ["phục vụ", "服务", "serve", 0],
    ["xuất hiện", "出现", "appear", 0],
    ["đường", "路", "road", 0],
    ["Bản đồ", "地图", "map", 0],
    ["mưa", "雨", "rain", 0],
    ["quy tắc", "规则", "rules", 0],
    ["phối", "治理/协调", "govern/coordinate", 0],
    ["kéo", "拉/拖", "pull/drag", 0],
    ["lạnh", "寒冷的", "cold", 0],
    ["thông báo", "注意/通知", "notice/Notification", 0],
    ["giọng nói", "嗓音", "voice", 0],
  ],
  basic: [
    ["như", "作为/喜欢", "as/like", 0],
    ["tôi", "我", "I", 0],
    ["mình", "他的/我", "his/me", 0],
    ["mà", "那/那个/但", "that/but", 0],
    ["ông", "他/祖父", "grandfather", 0],
    ["là", "是/过去式/成为", "was/To be", 0],
    ["cho", "为了/对于/给", "for/give", 0],
    ["trên", "在...上/多于", "on/above", 0],
    ["là", "是/成为", "are/To be", 0],
    ["với", "和/与", "with", 0],
    ["họ", "他们/姓", "they/Surname", 0],
    ["được", "是/存在/好的", "be/Okay", 0],
    ["tại", "在", "at/in", 0],
    ["một", "一/一个", "one", 0],
    ["có", "有", "have", 0],
    ["này", "这/这个", "this", 0],
    ["từ", "从", "from", 0],
    ["bởi", "通过/由/经过", "by", 0],
    ["nóng", "热的", "hot", 0],
    ["từ", "单词/从", "word/from", 0],
    ["nhưng", "但是", "but", 0],
    ["những gì", "什么", "what", 0],
    ["một số", "一些", "some", 0],
    ["là", "是/成为", "is/To be", 0],
    ["nó", "它", "it", 0],
    ["anh", "你/哥哥", "you/Older brother", 0],
    ["hoặc", "或者", "or", 0],
    ["có", "有", "had/Have", 0],
    ["các", "这", "the", 0],
    ["của", "的/属于", "of/belong to", 0],
    ["để", "到", "to", 0],
    ["và", "和", "and", 0],
    ["một", "一个", "a/one", 0],
    ["trong", "在", "in", 0],
    ["chúng tôi", "我们", "we", 0],
    ["có thể", "能/会/或许", "can/maybe", 0],
    ["ra", "出去", "go out", 0],
    ["khác", "其他", "other", 0],
    ["là", "是/成为", "were/To be", 0],
    ["mà", "哪个/但", "which/but", 0],
    ["làm", "做", "do", 0],
    ["của họ", "他们的", "their", 0],
    ["thời gian", "时间", "time", 0],
    ["nếu", "如果", "if", 0],
    ["sẽ", "将/会/将要", "will", 0],
    ["như thế nào", "如何", "how", 0],
    ["nói", "说话", "said/speak", 0],
    ["một", "一个", "an/one", 0],
    ["môi", "每个/唇", "each/lip", 0],
    ["nói", "告诉/说话", "tell/speak", 0],
    ["không", "做/不是", "does/Are not", 0],
    ["bộ", "放", "set", 0],
    ["ba", "三", "three", 0],
    ["muốn", "想", "want", 0],
    ["không khí", "空气", "air", 0],
    ["cũng", "出色地/还", "well/also", 0],
    ["cũng", "也/还", "also", 0],
    ["chơi", "玩", "play", 0],
    ["nhỏ", "小的", "small", 0],
    ["cuối", "结尾/最后的", "end/last", 0],
    ["đặt", "放", "put", 0],
    ["nhà", "家", "home", 0],
    ["đọc", "读", "read", 0],
    ["tay", "手", "hand", 0],
    ["cổng", "港口/门", "port/gate", 0],
    ["lớn", "大的", "large/big", 0],
    ["chính tả", "拼写", "spelling", 0],
    ["thêm", "添加/更多的", "add/more", 0],
    ["thậm chí", "甚至", "even", 0],
    ["đất", "土地", "land", 0],
    ["ở đây", "这里", "here", 0],
    ["phải", "必须/正确的", "must/Right", 0],
    ["lớn", "大的", "big", 0],
    ["cao", "高的", "high", 0],
    ["như vậy", "这样的/所以", "such/so", 0],
    ["theo", "跟随/根据", "follow/according to", 0],
    ["hành động", "行为", "act", 0],
    ["lý do tại sao", "为什么", "why", 0],
    ["xin", "询问", "Ask for", 0],
    ["người đàn ông", "男人", "men/man", 0],
    ["thay đổi", "改变", "change", 0],
    ["đi", "去了", "went/Go", 0],
    ["ánh sáng", "光", "light", 0],
    ["loại", "种类/类型", "kind/type", 0],
    ["tắt", "离开/关", "turn off", 0],
    ["cần", "需要", "need", 0],
    ["nhà", "房子/家", "house/home", 0],
    ["hình ảnh", "图片/图像", "picture/image", 0],
    ["thử", "尝试", "try", 0],
    ["chúng tôi", "我们", "us/we", 0],
    ["một lần nữa", "再次", "once again", 0],
    ["động vật", "动物", "animal", 0],
    ["điểm", "观点", "point", 0],
    ["mẹ", "母亲/妈妈", "mother/Mom", 0],
    ["thế giới", "世界", "world", 0],
    ["gần", "靠近/附近的", "near the", 0],
    ["xây dựng", "建造", "build", 0],
    ["tự", "自己/独自一人", "self/on one's own", 0],
    ["đất", "地球/土地", "earth/land", 0],
    ["cha", "父亲", "father", 0],
    ["bất kỳ", "任何", "any", 0],
    ["mới", "新的", "new", 0],
    ["công việc", "工作", "work/job", 0],
    ["một phần", "部分", "part", 0],
    ["có", "拿/带走/有", "take/Have", 0],
    ["được", "得到/好的", "get/Okay", 0],
    ["nơi", "地方", "place", 0],
    ["thực hiện", "制成/履行", "made/perform", 0],
    ["sống", "居住/活的", "live/living", 0],
    ["nơi", "在哪里/地方", "where/place", 0],
    ["sau khi", "之后", "after", 0],
    ["trở lại", "返回", "back/return", 0],
    ["ít", "小/少的/小的", "little", 0],
    ["chỉ", "仅仅/仅有的", "only", 0],
    ["chung quanh", "圆形的/大约", "around", 0],
    ["người đàn ông", "男人", "man", 0],
    ["năm", "年", "year", 0],
    ["đến", "来了/到达", "came/arrive", 0],
    ["chương trình", "展示/程序", "show/programme", 0],
    ["mỗi", "每一个/每个", "every/each", 0],
    ["tốt", "好的", "good", 0],
    ["tôi", "我(宾格)", "me/I", 0],
    ["cung cấp cho", "给", "give", 0],
    ["của chúng tôi", "我们的", "our", 0],
    ["dưới", "在下面/以下", "under/below", 0],
    ["tên", "姓名", "name", 0],
    ["rất", "非常", "very", 0],
    ["thông qua", "通过", "through", 0],
    ["chỉ", "只是/刚刚/仅有的", "just/only", 0],
    ["hình thức", "形式", "form", 0],
    ["câu", "句子", "sentence", 0],
    ["tuyệt vời", "伟大的", "great", 0],
    ["nghi", "思考/怀疑", "think/doubt", 0],
    ["nói", "说话", "say/speak", 0],
    ["giúp", "帮助", "help", 0],
    ["thấp", "低的/短的", "low/short", 0],
    ["dòng", "线/当前的", "line/current", 0],
    ["khác nhau", "不同的", "different", 0],
    ["lần lượt", "转动/先后", "turn/one after another", 0],
    ["nguyên nhân", "原因", "cause/reason", 0],
    ["nhiều", "很多", "much", 0],
    ["có nghĩa là", "意思是/方法", "means", 0],
    ["trước", "之前", "before", 0],
    ["di chuyển", "移动", "move", 0],
    ["ngay", "正确的", "right", 0],
    ["cậu bé", "男生", "boy", 0],
    ["cũ", "老的", "old", 0],
    ["quá", "也", "too", 0],
    ["như nhau", "相同的", "same", 0],
    ["cô", "她/错过", "she/Miss", 0],
    ["tất cả", "全部", "all", 0],
    ["có", "那里/有", "there/Have", 0],
    ["khi", "当/什么时候", "when", 0],
    ["lên", "上/起来", "go up", 0],
    ["sử dụng", "使用", "use", 0],
    ["của bạn", "你的", "your", 0],
    ["cách", "方式", "way", 0],
    ["về", "关于", "about", 0],
    ["nhiều", "很多", "many/much", 0],
    ["sau đó", "然后/之后", "then/Later", 0],
    ["họ", "他们(宾格)/姓", "them/Surname", 0],
    ["viết", "写", "write", 0],
    ["sẽ", "将/会/将要", "would/will", 0],
    ["như", "喜欢", "like", 0],
    ["để", "所以/这么/到", "so/to", 0],
    ["các", "这些", "these", 0],
    ["cô", "她的/错过", "her/Miss", 0],
    ["lâu", "长的", "long", 0],
    ["làm", "制作/做", "make/do", 0],
    ["điều", "事物", "thing", 0],
    ["thấy", "看见", "see", 0],
    ["anh", "他(宾格)/哥哥", "him/Older brother", 0],
    ["hai", "二", "two", 0],
    ["có", "有", "has/Have", 0],
    ["xem", "看", "look/see", 0],
    ["hơn", "更多的/比", "more/than", 0],
    ["ngày", "天", "day", 0],
    ["có thể", "能/或许", "could/maybe", 0],
    ["đi", "去", "go", 0],
    ["đến", "来/到达", "come/arrive", 0],
    ["đã làm", "做过", "did", 0],
    ["số", "数字", "number", 0],
    ["âm thanh", "声音", "sound", 0],
    ["không có", "不/没有/无法使用", "Not available", 0],
    ["nhất", "大多数/最好的", "most/best", 0],
    ["nhân dân", "人们", "people", 0],
    ["của tôi", "我的/矿", "my/mine", 0],
    ["hơn", "结束/超过/比", "over/than", 0],
    ["biết", "知道", "know", 0],
    ["nước", "水", "water", 0],
    ["hơn", "比", "than", 0],
    ["gọi", "称呼", "call", 0],
    ["đầu tiên", "第一/首先", "Firstly", 0],
    ["người", "谁/人们", "who/People", 0],
    ["có thể", "可能/或许", "maybe", 0],
    ["xuống", "向下", "down", 0],
    ["bên", "边/旁", "beside", 0],
    ["được", "到过/好的", "been/Okay", 0],
    ["bây giờ", "现在", "now", 0],
    ["tìm", "寻找", "find", 0],
    ["đầu", "头", "head", 0],
    ["đứng", "站立", "stand", 0],
    ["riêng", "自己的/私人的", "own/private", 0],
    ["trang", "页", "page", 0],
    ["nên", "应该", "should", 0],
    ["nước", "国家/水", "country/water", 0],
    ["tìm thấy", "成立/寻找", "found/find", 0],
    ["câu trả lời", "回答", "answer", 0],
    ["trường", "学校", "school", 0],
    ["phát triển", "生长/发展", "grow/develop", 0],
    ["nghiên cứu", "学习", "study", 0],
    ["vẫn", "仍然", "still", 0],
    ["học", "学习", "learn", 0],
    ["nhà máy", "植物/工厂", "plant/factory", 0],
    ["bìa", "覆盖", "cover", 0],
    ["thực phẩm", "食物", "food", 0],
    ["ánh nắng mặt trời", "太阳/阳光", "sunshine", 0],
    ["bốn", "四", "four", 0],
    ["giữa", "之间", "between", 0],
    ["nhà nước", "状态", "state", 0],
    ["giữ", "保持/抓住", "keep/hold", 0],
    ["mắt", "眼睛", "eye", 0],
    ["không bao giờ", "绝不", "never", 0],
    ["cuối cùng", "最后的/最终的", "last/Final", 0],
    ["cho phép", "让/允许", "let/allow", 0],
    ["nghĩ", "想法/思考", "thought/think", 0],
    ["thành phố", "城市", "city", 0],
    ["cây", "树", "tree", 0],
    ["qua", "叉/通过", "cross/via", 0],
    ["trang trại", "农场", "farm", 0],
    ["cứng", "难的", "hard", 0],
    ["bắt đầu", "开始", "start/begin", 0],
    ["might", "可能", "might", 0],
    ["câu chuyện", "故事", "story", 0],
    ["cưa", "锯", "saw", 0],
    ["đến nay", "远的/到目前为止", "far/up to now", 0],
    ["biển", "海", "sea", 0],
    ["vẽ", "画", "draw", 0],
    ["còn lại", "左边/其余的", "left/remaining", 0],
    ["cuối", "晚的/最后的", "late/last", 0],
    ["chạy", "跑步", "run", 0],
    ["không", "不是", "don’t/Are not", 0],
    ["trong khi", "尽管", "while", 0],
    ["báo chí", "按", "press", 0],
    ["gần", "关闭/附近的", "close/near the", 0],
    ["đêm", "夜晚", "night", 0],
    ["thực", "真实的", "real", 0],
    ["cuộc sống", "生活", "life", 0],
    ["số", "很少/数字", "few/number", 0],
    ["phía bắc", "北", "north", 0],
    ["cuốn sách", "书", "book", 0],
    ["thực hiện", "携带/履行", "carry/perform", 0],
    ["mất", "采取了/丢失的", "took/lost", 0],
    ["khoa học", "科学", "science", 0],
    ["ăn", "吃", "eat", 0],
    ["phòng", "房间", "room", 0],
    ["người bạn", "朋友", "friend", 0],
    ["bắt đầu", "开始", "began/begin", 0],
    ["ý tưởng", "主意", "idea", 0],
    ["cá", "鱼", "fish", 0],
    ["núi", "山", "mountain", 0],
    ["ngăn chặn", "停止/防止", "stop/prevent", 0],
    ["một lần", "一次", "once", 0],
    ["cơ sở", "根据", "base", 0],
    ["nghe", "听到", "hear/listen", 0],
    ["ngựa", "马", "horse", 0],
    ["cắt", "切", "cut", 0],
    ["chắc chắn", "当然", "sure", 0],
    ["xem", "手表/看", "watch/see", 0],
    ["màu", "颜色", "color", 0],
    ["khuôn mặt", "脸", "face", 0],
    ["gỗ", "木头", "wood", 0],
    ["chính", "主要的", "main", 0],
    ["mở", "打开", "open", 0],
    ["dường như", "它似乎", "it seems", 0],
    ["cùng", "一起", "together", 0],
    ["tiếp theo", "下一个", "next", 0],
    ["trắng", "白色的", "white", 0],
    ["trẻ em", "孩子们", "children", 0],
    ["bắt đầu", "开始", "begin", 0],
    ["có", "得到/有", "got/Have", 0],
    ["đi bộ", "走", "walk", 0],
    ["Ví dụ", "例子/例如", "For example", 0],
    ["giảm bớt", "舒适/减少", "decrease", 0],
    ["giấy", "纸", "paper", 0],
    ["nhóm", "团体", "group", 0],
    ["luôn luôn", "总是", "always", 0],
    ["nhạc", "音乐", "music", 0],
    ["những", "那些/这些", "those/these", 0],
    ["cả hai", "两个都", "both", 0],
    ["đánh dấu", "标记/打钩", "mark/tick", 0],
    ["thường", "经常", "often", 0],
    ["thư", "信/字母", "letters", 0],
    ["cho đến khi", "直到", "until", 0],
    ["dặm", "英里", "mile", 0],
    ["sông", "河", "river", 0],
    ["xe", "车", "car", 0],
    ["chân", "脚", "feet/foot", 0],
    ["chăm sóc", "关心/照顾", "take care of", 0],
    ["thứ hai", "第二/周一", "second/Monday", 0],
    ["đủ", "足够的", "enough", 0],
    ["đồng bằng", "清楚的", "plain", 0],
    ["cô gái", "女孩", "girl", 0],
    ["thông thường", "通常情况下", "usual/normally", 0],
    ["trẻ", "年轻的", "young", 0],
    ["sẵn sàng", "准备好", "ready", 0],
    ["trên đây", "多于", "above", 0],
    ["bao giờ", "曾经", "ever", 0],
    ["màu đỏ", "红色的", "red", 0],
    ["danh sách", "列表", "list", 0],
    ["mặc dù", "尽管", "though/in spite of", 0],
    ["cảm thấy", "感觉", "feel", 0],
    ["nói chuyện", "讲话", "talk", 0],
    ["chim", "鸟", "bird", 0],
    ["sớm", "很快/早期的", "soon/early", 0],
    ["cơ thể", "身体", "body", 0],
    ["con chó", "狗", "dog", 0],
    ["gia đình", "家庭", "family", 0],
    ["trực tiếp", "直接的", "direct", 0],
    ["đặt ra", "姿势/出发", "pose/set out", 0],
    ["lại", "离开/再次", "leave/again", 0],
    ["bài hát", "歌曲", "song", 0],
    ["đo lường", "措施/测量", "measurement", 0],
    ["cửa", "门", "door", 0],
    ["sản phẩm", "产品", "product", 0],
    ["đen", "黑色的", "black", 0],
    ["ngắn", "短的", "short", 0],
    ["chữ số", "数字", "numeral/digits", 0],
    ["lớp", "班级", "class", 0],
    ["gió", "风", "wind", 0],
    ["câu hỏi", "问题", "question", 0],
    ["xảy ra", "发生", "happen", 0],
    ["hoàn thành", "完全的", "complete", 0],
    ["tàu", "船", "ship", 0],
    ["khu vực", "区域", "area", 0],
    ["một nửa", "一半", "half", 0],
    ["đá", "岩石/石头", "rock/stone", 0],
    ["để", "命令/到", "order/to", 0],
    ["lửa", "火", "fire", 0],
    ["nam", "南/男性", "south/male", 0],
    ["vấn đề", "问题", "problem", 0],
    ["mảnh", "片", "piece", 0],
    ["nói", "告诉/说话", "told/speak", 0],
    ["biết", "知道", "knew/know", 0],
    ["vượt qua", "经过/克服", "pass/overcome", 0],
    ["từ", "自从", "since/from", 0],
    ["đầu", "顶部/头", "top/head", 0],
    ["toàn bộ", "所有的", "whole", 0],
    ["vua", "国王", "king", 0],
    ["đường phố", "街道", "street", 0],
    ["inch", "英寸", "inches", 0],
    ["nhân", "乘/核", "multiply/core", 0],
    ["không có gì", "没有什么", "nothing", 0],
    ["Tất nhiên", "课程/当然", "Of course", 0],
    ["ở lại", "停留", "stay", 0],
    ["bánh xe", "车轮", "wheel", 0],
    ["đầy đủ", "满的", "full", 0],
    ["lực", "力量", "force", 0],
    ["màu xanh", "蓝色的/绿色的", "blue/green", 0],
    ["đối tượng", "目的", "object", 0],
    ["quyết định", "决定", "decide/decision", 0],
    ["bề mặt", "表面", "surface", 0],
    ["sâu", "深的", "deep", 0],
    ["mặt trăng", "月亮", "moon", 0],
    ["đảo", "岛", "island", 0],
    ["chân", "脚", "foot", 0],
    ["hệ thống", "系统", "system", 0],
    ["bận rộn", "忙碌的", "busy", 0],
    ["kiểm tra", "测试/查看", "test/check", 0],
    ["ghi", "记录/注意", "record/take note", 0],
    ["thuyền", "船", "boat", 0],
    ["phổ biến", "常见的/受欢迎的", "common/popular", 0],
    ["vàng", "金子/黄色的", "gold/Yellow", 0],
    ["có thể", "可能的/或许", "possible/maybe", 0],
    ["máy bay", "飞机", "plane", 0],
    ["thay", "斯蒂德/代替", "stead/replace", 0],
    ["khô", "干燥/干的", "dry/dried", 0],
    ["tự hỏi", "想知道", "wonder", 0],
    ["cười", "笑", "laugh", 0],
    ["ngàn", "千", "thousand", 0],
    ["trước", "前", "ago/before", 0],
    ["ran", "跑/然", "ran", 0],
    ["kiểm tra", "查看", "check", 0],
    ["trò chơi", "游戏", "game", 0],
    ["hình dạng", "形状", "shape", 0],
    ["đánh đồng", "等同", "equate", 0],
    ["nóng", "热的", "hot", 0],
    ["bỏ lỡ", "错过", "miss", 0],
    ["mang", "带来/携带", "brought/carry", 0],
    ["nhiệt", "热", "heat", 0],
    ["tuyết", "雪", "snow", 0],
    ["lốp xe", "轮胎", "tires", 0],
    ["mang lại", "带来", "bring", 0],
    ["vâng", "是的", "yes", 0],
    ["xa", "遥远", "distant", 0],
    ["điền", "充满", "fill", 0],
    ["đông", "东方/冬天", "east/winter", 0],
    ["sơn", "画", "paint", 0],
    ["ngôn ngữ", "语言", "language", 0],
    ["trong", "之中/在", "among/in", 0],
    ["đơn vị", "单元", "unit", 0],
    ["điện", "力量/电", "power/electricity", 0],
    ["thị trấn", "镇", "town", 0],
    ["tốt", "美好的", "fine/Good", 0],
    ["nhất định", "肯定", "certain", 0],
    ["bay", "飞", "fly", 0],
    ["giảm", "落下/减少", "fall/reduce", 0],
    ["dẫn", "带领/指导", "lead/guide", 0],
    ["kêu", "哭/称呼", "cry/call", 0],
    ["tối", "黑暗的", "dark", 0],
    ["máy", "机器", "machine", 0],
    ["ghi", "笔记/注意", "take note", 0],
    ["đợi", "等待", "wait", 0],
    ["kế hoạch", "计划", "plan", 0],
    ["con số", "数字", "figure/number", 0],
    ["sao", "星星", "star", 0],
    ["hộp", "盒子", "box", 0],
    ["danh từ", "名词", "noun", 0],
    ["lĩnh vực", "场地", "field", 0],
    ["phần còn lại", "休息/其余的部分", "the rest", 0],
    ["chính xác", "正确的/确切地", "correct/Exactly", 0],
    ["thể", "有能力的", "able/can", 0],
    ["bảng", "磅/木板", "pound/board", 0],
    ["Xong", "完毕/完成的", "done/Finished", 0],
    ["vẻ đẹp", "美丽", "beauty", 0],
    ["ổ đĩa", "驾驶", "drive", 0],
    ["đứng", "站着/站立", "stood/stand", 0],
    ["chứa", "包含", "contain", 0],
    ["trước", "正面/前", "front/before", 0],
    ["dạy", "教", "teach", 0],
    ["tuần", "星期", "week", 0],
    ["thức", "最终的/醒", "final/awake", 0],
    ["đã", "给了/使满意", "gave/Satisfied", 0],
    ["màu xanh lá cây", "绿色的", "green", 0],
    ["oh", "哦", "oh", 0],
    ["nhanh chóng", "快的", "quick", 0],
    ["phát triển", "发展", "develop", 0],
    ["đại dương", "海洋", "ocean", 0],
    ["ấm áp", "温暖的", "warm", 0],
    ["miễn phí", "自由的/免费", "free of charge", 0],
    ["phút", "分钟", "minute", 0],
    ["mạnh mẽ", "强的", "strong", 0],
    ["đặc biệt", "特别的", "special", 0],
    ["tâm", "头脑/心", "mind/heart", 0],
    ["sau", "在后面", "behind/after", 0],
    ["trong", "清除/在", "clear/in", 0],
    ["đuôi", "尾巴", "tail", 0],
    ["sản xuất", "生产", "produce/manufacture", 0],
    ["thực tế", "事实/现实", "fact/reality", 0],
    ["không gian", "空间", "space", 0],
    ["nghe", "听到", "heard", 0],
    ["tốt nhất", "最好的", "best", 0],
    ["giờ", "小时", "hour", 0],
    ["tốt hơn", "更好的", "better", 0],
    ["đúng", "真的/正确的", "true", 0],
    ["trong khi", "期间/尽管", "during", 0],
    ["trăm", "百", "hundred", 0],
    ["năm", "五/年", "five", 0],
    ["nhớ", "记住/错过", "remember", 0],
    ["bước", "步", "step", 0],
    ["đầu", "早期的/头", "early", 0],
    ["giư", "抓住", "hold", 0],
    ["tây", "西方", "west", 0],
    ["mặt đất", "地面", "ground", 0],
    ["quan tâm", "兴趣/关心", "interest", 0],
    ["đạt", "抵达/获得", "reach", 0],
    ["nhanh chóng", "快速地/快的", "fast", 0],
    ["động từ", "动词", "verb", 0],
    ["hát", "唱歌", "sing", 0],
    ["lắng nghe", "听", "listen", 0],
    ["sáu", "六", "six", 0],
    ["bảng", "桌子/木板", "table", 0],
    ["du lịch", "旅行/旅游", "travel", 0],
    ["ít", "较少的/小的", "less", 0],
    ["buổi sáng", "早晨", "morning", 0],
    ["mười", "十", "ten", 0],
    ["đơn giản", "简单的", "simple", 0],
    ["nhiều", "一些/很多", "several", 0],
    ["nguyên âm", "元音", "vowel", 0],
    ["hướng", "朝向/方向", "toward", 0],
    ["chiến tranh", "战争", "war", 0],
    ["đặt", "躺着/放", "lay", 0],
    ["chống lại", "反对", "against", 0],
    ["mô hình", "图案/模型", "pattern", 0],
    ["chậm", "慢的", "slow", 0],
    ["trung tâm", "中心", "center", 0],
    ["tình yêu", "爱", "love", 0],
    ["người", "人们", "person", 0],
    ["tiền", "钱", "money", 0],
    ["phục vụ", "服务", "serve", 0],
    ["xuất hiện", "出现", "appear", 0],
    ["đường", "路", "road", 0],
    ["Bản đồ", "地图", "map", 0],
    ["mưa", "雨", "rain", 0],
    ["quy tắc", "规则", "rule", 0],
    ["phối", "治理/协调", "govern", 0],
    ["kéo", "拉/拖", "pull", 0],
    ["lạnh", "寒冷的", "cold", 0],
    ["thông báo", "注意/通知", "notice", 0],
    ["giọng nói", "嗓音", "voice", 0],
    ["năng lượng", "活力", "energy", 0],
    ["săn", "打猎", "hunt", 0],
    ["có thể xảy ra", "可能发生", "probable", 0],
    ["giường", "床", "bed", 0],
    ["anh trai", "兄弟/哥哥", "brother", 0],
    ["trứng", "蛋", "egg", 0],
    ["đi xe", "骑", "ride", 0],
    ["pin", "细胞/电池", "cell", 0],
    ["tin", "相信", "believe", 0],
    ["có lẽ", "也许/或许", "perhaps", 0],
    ["chọn", "挑选/选择", "pick", 0],
    ["đột ngột", "突然的", "sudden", 0],
    ["tính", "数数", "count", 0],
    ["vuông", "正方形", "square", 0],
    ["lý do", "原因", "reason", 0],
    ["chiều dài", "长度", "length", 0],
    ["đại diện", "代表", "represent", 0],
    ["nghệ thuật", "艺术", "art", 0],
    ["Tiêu đề", "主题/标题", "subject", 0],
    ["khu", "地区/区域", "region", 0],
    ["kích thước", "尺寸", "size", 0],
    ["khác nhau", "各不相同/不同的", "vary", 0],
    ["giải quyết", "定居/处理", "settle", 0],
    ["nói", "说话", "speak", 0],
    ["trọng lượng", "重量", "weight", 0],
    ["chung", "一般的/共享", "general", 0],
    ["băng", "冰", "ice", 0],
    ["vấn đề", "事情/问题", "matter", 0],
    ["vòng tròn", "圆圈", "circle", 0],
    ["đôi", "一对", "pair", 0],
    ["bao gồm", "包括", "include", 0],
    ["chia", "划分", "divide", 0],
    ["âm tiết", "音节", "syllable", 0],
    ["cảm thấy", "毛毡/感觉", "felt", 0],
    ["lớn", "盛大/大的", "grand", 0],
    ["bóng", "球", "ball", 0],
    ["nhưng", "然而/但", "yet", 0],
    ["sóng", "海浪", "wave", 0],
    ["rơi", "降低/落下", "drop", 0],
    ["tim", "心", "heart", 0],
    ["là", "是/成为", "am", 0],
    ["hiện nay", "展示/现在", "present", 0],
    ["nặng", "重的", "heavy", 0],
    ["khiêu vũ", "舞蹈/跳舞", "dance", 0],
    ["động cơ", "引擎", "engine", 0],
    ["vị trí", "位置/地点", "position", 0],
    ["cánh tay", "手臂", "arm", 0],
    ["rộng", "宽的", "wide", 0],
    ["buồm", "帆", "sail", 0],
    ["tài liệu", "材料/文档", "material", 0],
    ["phần", "分数/部分", "fraction", 0],
    ["rừng", "森林", "forest", 0],
    ["ngồi", "坐", "sit", 0],
    ["cuộc đua", "种族", "race", 0],
    ["cửa sổ", "窗户", "window", 0],
    ["cửa hàng", "店铺", "store", 0],
    ["mùa hè", "夏天", "summer", 0],
    ["đào tạo", "火车", "train", 0],
    ["ngủ", "睡觉", "sleep", 0],
    ["chứng minh", "证明", "prove", 0],
    ["đơn độc", "孤独的/单身的", "lone", 0],
    ["chân", "腿/脚", "leg", 0],
    ["tập thể dục", "锻炼/做运动", "exercise", 0],
    ["tường", "墙", "wall", 0],
    ["bắt", "抓住", "catch", 0],
    ["mount", "山。山", "mount", 0],
    ["muốn", "希望/想", "wish", 0],
    ["bầu trời", "天空", "sky", 0],
    ["hội đồng quản trị", "木板/董事会", "board", 0],
    ["niềm vui", "喜悦", "joy", 0],
    ["mùa đông", "冬天", "winter", 0],
    ["ngồi", "坐", "sat", 0],
    ["bằng văn bản", "以书面形式", "written", 0],
    ["hoang dã", "荒野/野性的", "wild", 0],
    ["cụ", "乐器/工具", "instrument", 0],
    ["giữ", "保留/抓住", "kept", 0],
    ["kính", "玻璃/眼镜", "glass", 0],
    ["cỏ", "草", "grass", 0],
    ["bò", "奶牛", "cow", 0],
    ["công việc", "工作", "job", 0],
    ["cạnh", "边缘", "edge", 0],
    ["dấu hiệu", "符号/代币", "sign", 0],
    ["lần", "访问/时间", "visit", 0],
    ["qua", "过去的/通过", "past", 0],
    ["mềm", "柔软的", "soft", 0],
    ["vui vẻ", "乐趣/快乐的", "fun", 0],
    ["sáng", "明亮的", "bright", 0],
    ["khí", "气体", "gas", 0],
    ["thời tiết", "天气", "weather", 0],
    ["tháng", "月", "month", 0],
    ["triệu", "百万", "million", 0],
    ["chịu", "熊", "bear", 0],
    ["kết thúc", "结束/结尾", "finish", 0],
    ["hạnh phúc", "快乐的", "happy", 0],
    ["hy vọng", "希望", "hope", 0],
    ["hoa", "花", "flower", 0],
    ["mặc", "衣服/穿", "clothe", 0],
    ["lạ", "奇怪的", "strange", 0],
    ["ra đi", "消失了/离开", "gone", 0],
    ["thương mại", "贸易/商业", "trade", 0],
    ["giai điệu", "旋律", "melody", 0],
    ["chuyến đi", "旅行", "trip", 0],
    ["văn phòng", "办公室", "office", 0],
    ["nhận", "收到", "receive", 0],
    ["hàng", "排", "row", 0],
    ["miệng", "嘴", "mouth", 0],
    ["chính xác", "精确的/确切地", "exact", 0],
    ["biểu tượng", "象征/图标", "symbol", 0],
    ["chết", "死", "die", 0],
    ["nhất", "至少/最好的", "least", 0],
    ["rắc rối", "麻烦", "trouble", 0],
    ["hét lên", "喊/尖叫", "shout", 0],
    ["trừ", "除了", "except", 0],
    ["đã viết", "写道", "wrote", 0],
    ["hạt giống", "种子", "seed", 0],
    ["giai điệu", "语气/旋律", "tone", 0],
    ["tham gia", "加入", "join", 0],
    ["đề nghị", "建议", "suggest", 0],
    ["sạch", "干净的", "clean", 0],
    ["nghỉ", "休息", "break", 0],
    ["phụ nữ", "女士/女性", "lady", 0],
    ["sân", "院子", "yard", 0],
    ["tăng", "上升/增加", "rise", 0],
    ["xấu", "坏的", "bad", 0],
    ["đòn", "吹", "blow", 0],
    ["dầu", "油", "oil", 0],
    ["máu", "血", "blood", 0],
    ["chạm", "触碰", "touch", 0],
    ["tăng", "长大了/增加", "grew", 0],
    ["phần trăm", "百分比", "cent", 0],
    ["trộn", "混合", "mix", 0],
    ["đội", "团队", "team", 0],
    ["dây", "金属丝", "wire", 0],
    ["chi phí", "成本/费用", "cost", 0],
    ["thua", "丢失的/失去", "lost", 0],
    ["nâu", "棕色的", "brown", 0],
    ["mặc", "穿", "wear", 0],
    ["vườn", "花园", "garden", 0],
    ["như nhau", "平等的/相同的", "equal", 0],
    ["gửi", "发送", "sent", 0],
    ["chọn", "选择", "choose", 0],
    ["giảm", "跌倒了/减少", "fell", 0],
    ["phù hợp với", "合身/套装", "fit", 0],
    ["chảy", "流动/跑步", "flow", 0],
    ["công bằng", "公平的", "fair", 0],
    ["ngân hàng", "银行", "bank", 0],
    ["thu thập", "收集", "collect", 0],
    ["lưu", "节省", "save", 0],
    ["kiểm soát", "控制", "control", 0],
    ["số thập phân", "小数", "decimal", 0],
    ["tai", "耳朵", "ear", 0],
    ["khác", "别的/其他", "else", 0],
    ["khá", "相当", "quite", 0],
    ["đã phá vỡ", "坏了", "broke", 0],
    ["khi", "案件/什么时候", "case", 0],
    ["trung", "中间/中央", "middle", 0],
    ["giết", "杀", "kill", 0],
    ["con trai", "儿子/男生", "son", 0],
    ["hồ", "湖", "lake", 0],
    ["thời điểm", "片刻/时间", "moment", 0],
    ["quy mô", "规模", "scale", 0],
    ["lớn", "大声/大的", "loud", 0],
    ["mùa xuân", "春天", "spring", 0],
    ["quan sát", "观察", "observe", 0],
    ["con", "孩子", "child", 0],
    ["thẳng", "直的", "straight", 0],
    ["phụ âm", "辅音", "consonant", 0],
    ["quốc gia", "国家", "nation", 0],
    ["từ điển", "字典", "dictionary", 0],
    ["sưa", "牛奶", "milk", 0],
    ["tốc độ", "速度", "speed", 0],
    ["phương pháp", "方法", "method", 0],
    ["cơ quan", "器官/机构", "organ", 0],
    ["trả", "支付", "pay", 0],
    ["tuổi", "年龄/岁", "age", 0],
    ["phần", "部分", "section", 0],
    ["váy", "裙子", "dress", 0],
    ["điện toán đám mây", "云计算", "cloud", 0],
    ["bất ngờ", "惊喜", "surprise", 0],
    ["yên tĩnh", "安静的", "quiet", 0],
    ["đá", "石头", "stone", 0],
    ["nhỏ", "微小的", "tiny", 0],
    ["lên cao", "爬/嗨起来", "climb", 0],
    ["mát mẻ", "凉爽的", "cool", 0],
    ["thiết kế", "设计", "design", 0],
    ["người nghèo", "贫穷的/穷人", "poor", 0],
    ["rất nhiều", "很多/这么多", "lot", 0],
    ["thí nghiệm", "实验", "experiment", 0],
    ["dưới", "底部/以下", "bottom", 0],
    ["chính", "钥匙/主要的", "key", 0],
    ["sắt", "铁", "iron", 0],
    ["đơn", "单身的", "single", 0],
    ["thanh", "戳/酒吧", "stick", 0],
    ["phẳng", "平坦的/飞机", "flat", 0],
    ["hai mươi", "二十", "twenty", 0],
    ["da", "皮肤", "skin", 0],
    ["nụ cười", "微笑", "smile", 0],
    ["nếp", "折痕/黏", "crease", 0],
    ["lỗ", "洞", "hole", 0],
    ["nhảy", "跳/舞蹈", "jump", 0],
    ["bé", "婴儿/小的", "baby", 0],
    ["tám", "八", "eight", 0],
    ["làng", "村庄", "village", 0],
    ["đáp ứng", "见面/回复", "meet", 0],
    ["gốc", "根/起源", "root", 0],
    ["mua", "买", "buy", 0],
    ["nâng cao", "增加/先进的", "raise", 0],
    ["giải quyết", "解决/处理", "solve", 0],
    ["kim loại", "金属", "metal", 0],
    ["liệu", "无论/材料", "whether", 0],
    ["đẩy", "推", "push", 0],
    ["bảy", "七", "seven", 0],
    ["đoạn", "段落", "paragraph", 0],
    ["thứ ba", "第三/周二", "third", 0],
    ["có trách nhiệm", "将/负责任的", "shall", 0],
    ["được tổ chức", "握住/有组织的", "held", 0],
    ["lông", "头发", "hair", 0],
    ["mô tả", "描述", "describe", 0],
    ["nấu ăn", "厨师", "cook", 0],
    ["sàn", "地面", "floor", 0],
    ["hoặc", "任何一个/或者", "either", 0],
    ["kết quả", "结果", "result", 0],
    ["ghi", "烧伤/注意", "burn", 0],
    ["đồi", "爬坡道", "hill", 0],
    ["an toàn", "安全的", "safe", 0],
    ["mèo", "猫", "cat", 0],
    ["thế kỷ", "世纪", "century", 0],
    ["xem xét", "考虑", "consider", 0],
    ["loại", "类型", "type", 0],
    ["pháp luật", "法律", "law", 0],
    ["bit", "少量/位", "bit", 0],
    ["bờ biển", "海岸", "coast", 0],
    ["bản sao", "复制", "copy", 0],
    ["cụm từ", "短语", "phrase", 0],
    ["im lặng", "沉默的", "silent", 0],
    ["cao", "高的", "tall", 0],
    ["cát", "沙", "sand", 0],
    ["đất", "土壤/土地", "soil", 0],
    ["cuộn", "卷", "roll", 0],
    ["nhiệt độ", "温度", "temperature", 0],
    ["ngón tay", "手指", "finger", 0],
    ["ngành công nghiệp", "行业", "industry", 0],
    ["giá trị", "价值", "value", 0],
    ["cuộc chiến", "斗争/战争", "fight", 0],
    ["lời nói dối", "说谎", "lie", 0],
    ["đánh bại", "打/击败", "beat", 0],
    ["kích thích", "激发/刺激", "excite", 0],
    ["tự nhiên", "自然的", "natural", 0],
    ["xem", "看法", "view", 0],
    ["ý nghĩa", "感觉/意义", "sense", 0],
    ["vốn", "首都", "capital", 0],
    ["sẽ không", "惯于", "won’t", 0],
    ["ghế", "椅子", "chair", 0],
    ["nguy hiểm", "危险", "danger", 0],
    ["trái cây", "水果", "fruit", 0],
    ["giàu", "富有的", "rich", 0],
    ["dày", "厚的", "thick", 0],
    ["người lính", "士兵", "soldier", 0],
    ["quá trình", "过程/进步", "process", 0],
    ["hoạt động", "操作/工作", "operate", 0],
    ["thực hành", "实践", "practice", 0],
    ["riêng biệt", "分离", "separate", 0],
    ["khó khăn", "难的", "difficult", 0],
    ["bác sĩ", "医生", "doctor", 0],
    ["xin vui lòng", "请", "please", 0],
    ["bảo vệ", "保护", "protect", 0],
    ["trưa", "中午/午餐", "noon", 0],
    ["cây trồng", "庄稼/植物", "crop", 0],
    ["hiện đại", "现代的", "modern", 0],
    ["yếu tố", "元素", "element", 0],
    ["nhấn", "打/按", "hit", 0],
    ["sinh viên", "学生", "student", 0],
    ["góc", "角落", "corner", 0],
    ["bên", "派对/旁", "party", 0],
    ["cung cấp", "供应/提供", "supply", 0],
    ["có", "谁/有", "whose", 0],
    ["xác định vị trí", "定位", "locate", 0],
    ["vòng", "戒指", "ring", 0],
    ["nhân vật", "特点/数字", "character", 0],
    ["côn trùng", "昆虫", "insect", 0],
    ["bắt", "捕捉/抓住", "caught", 0],
    ["thời gian", "时期/时间", "period", 0],
    ["chỉ ra", "表明/指出", "indicate", 0],
    ["radio", "收音机", "radio", 0],
    ["nói", "辐/说话", "spoke", 0],
    ["nguyên tử", "原子", "atom", 0],
    ["con người", "人类", "human", 0],
    ["lịch sử", "历史", "history", 0],
    ["hiệu lực", "影响", "effect", 0],
    ["điện", "电的", "electric", 0],
    ["mong đợi", "预计/期待", "expect", 0],
    ["xương", "骨", "bone", 0],
    ["đường sắt", "轨/铁路", "rail", 0],
    ["tưởng tượng", "想象", "imagine", 0],
    ["cho", "提供/给", "provide", 0],
    ["đồng ý", "同意", "agree", 0],
    ["do đó", "因此/所以", "thus", 0],
    ["nhẹ nhàng", "温和的/轻轻", "gentle", 0],
    ["người phụ nữ", "女士", "woman", 0],
    ["đội trưởng", "队长", "captain", 0],
    ["đoán", "猜测", "guess", 0],
    ["cần thiết", "必要的", "necessary", 0],
    ["sắc nét", "锋利的", "sharp", 0],
    ["cánh", "翼", "wing", 0],
    ["tạo", "创造", "create", 0],
    ["hàng xóm", "邻居", "neighbor", 0],
    ["rửa", "洗", "wash", 0],
    ["bat", "蝙蝠", "bat", 0],
    ["thay", "相当/代替", "rather", 0],
    ["đám đông", "人群", "crowd", 0],
    ["ngô", "玉米", "corn", 0],
    ["so sánh", "比较", "compare", 0],
    ["bài thơ", "诗", "poem", 0],
    ["chuỗi", "细绳", "string", 0],
    ["chuông", "钟", "bell", 0],
    ["phụ thuộc", "依赖的", "depend", 0],
    ["thịt", "肉", "meat", 0],
    ["chà", "擦", "rub", 0],
    ["ống", "管子", "tube", 0],
    ["nổi tiếng", "著名的", "famous", 0],
    ["đồng đô la", "美元", "dollar", 0],
    ["sông", "溪流/河", "stream", 0],
    ["sợ hãi", "害怕的", "fear", 0],
    ["cảnh", "视线/场景", "sight", 0],
    ["mỏng", "薄的", "thin", 0],
    ["tam giác", "三角形", "triangle", 0],
    ["hành tinh", "行星", "planet", 0],
    ["nhanh", "匆忙/快速地", "hurry", 0],
    ["trưởng", "首席", "chief", 0],
    ["thuộc địa", "殖民地", "colony", 0],
    ["đồng hồ", "钟", "clock", 0],
    ["tôi", "矿/我", "mine", 0],
    ["cà vạt", "领带", "tie", 0],
    ["nhập", "进入", "enter", 0],
    ["chính", "主要的", "major", 0],
    ["tươi", "新鲜的", "fresh", 0],
    ["tìm kiếm", "搜索", "search", 0],
    ["gửi", "发送", "send", 0],
    ["vàng", "黄色的", "yellow", 0],
    ["súng", "枪", "gun", 0],
    ["cho phép", "允许", "allow", 0],
    ["in", "打印", "print", 0],
    ["chết", "死的", "dead", 0],
    ["tại chỗ", "点", "spot", 0],
    ["sa mạc", "沙漠", "desert", 0],
    ["phù hợp với", "套装", "suit", 0],
    ["hiện tại", "当前的/展示", "current", 0],
    ["thang máy", "举起/电梯", "lift", 0],
    ["tăng", "玫瑰/增加", "rose", 0],
    ["đến", "到达", "arrive", 0],
    ["chủ", "掌握/所有者", "master", 0],
    ["theo dõi", "追踪/监视器", "track", 0],
    ["mẹ", "家长/妈妈", "parent", 0],
    ["bờ", "支撑/边缘", "shore", 0],
    ["phân chia", "分配/分享", "division", 0],
    ["tờ", "床单", "sheet", 0],
    ["chất", "物质/事情", "substance", 0],
    ["ủng hộ", "青睐/捐", "favor", 0],
    ["kết nối", "连接", "connect", 0],
    ["bài", "邮政", "post", 0],
    ["chi tiêu", "花费/开支", "spend", 0],
    ["hợp âm", "和弦", "chord", 0],
    ["chất béo", "胖的", "fat", 0],
    ["vui", "高兴的/乐趣", "glad", 0],
    ["ban đầu", "原来的/最初的", "original", 0],
    ["chia sẻ", "分享", "share", 0],
    ["trạm", "车站", "station", 0],
    ["cha", "爸爸/父亲", "dad", 0],
    ["bánh mì", "面包", "bread", 0],
    ["phí", "收费/费用", "charge", 0],
    ["thích hợp", "恰当的/合身", "proper", 0],
    ["thanh", "酒吧", "bar", 0],
    ["phục vụ", "提供/服务", "offer", 0],
    ["phân khúc", "部分", "segment", 0],
    ["nô lệ", "奴隶", "slave", 0],
    ["vịt", "鸭子", "duck", 0],
    ["ngay lập tức", "立即的/马上", "instant", 0],
    ["thị trường", "市场", "market", 0],
    ["mức độ", "程度/等级", "degree", 0],
    ["cư", "填充", "populate", 0],
    ["gà", "小鸡", "chick", 0],
    ["thân yêu", "亲爱的", "dear", 0],
    ["kẻ thù", "敌人", "enemy", 0],
    ["trả lời", "回复", "reply", 0],
    ["ly", "喝/玻璃", "drink", 0],
    ["xảy ra", "发生", "occur", 0],
    ["hỗ trợ", "支持", "support", 0],
    ["bài phát biểu", "演讲", "speech", 0],
    ["thiên nhiên", "自然", "nature", 0],
    ["phạm vi", "范围", "range", 0],
    ["hơi nước", "蒸汽", "steam", 0],
    ["chuyển động", "运动/移动", "motion", 0],
    ["con đường", "小路", "path", 0],
    ["chất lỏng", "液体", "liquid", 0],
    ["đăng nhập", "日志/登录", "log", 0],
    ["có nghĩa là", "意思是/方法", "meant", 0],
    ["thương", "商/爱", "quotient", 0],
    ["răng", "牙齿", "teeth", 0],
    ["vỏ", "壳/吠", "shell", 0],
    ["cổ", "脖子", "neck", 0],
    ["oxy", "氧", "oxygen", 0],
    ["đường", "糖/路", "sugar", 0],
    ["chết", "死亡", "death", 0],
    ["khá", "漂亮的/相当", "pretty", 0],
    ["kỹ năng", "技能", "skill", 0],
    ["phụ nữ", "女性", "women", 0],
    ["mùa", "季节", "season", 0],
    ["giải pháp", "解决方案", "solution", 0],
    ["nam châm", "磁铁", "magnet", 0],
    ["bạc", "银", "silver", 0],
    ["cảm ơn", "感谢/谢谢", "thank", 0],
    ["chi nhánh", "分支", "branch", 0],
    ["trận đấu", "匹配", "match", 0],
    ["hậu tố", "后缀", "suffix", 0],
    ["đặc biệt là", "尤其", "especially", 0],
    ["sung", "如图", "fig", 0],
    ["sợ", "害怕的", "afraid", 0],
    ["to", "巨大的", "huge", 0],
    ["em gái", "姐姐/妹妹", "sister", 0],
    ["thép", "钢", "steel", 0],
    ["thảo luận", "讨论", "discuss", 0],
    ["về phía trước", "向前", "forward", 0],
    ["tương tự", "相似的", "similar", 0],
    ["hướng dẫn", "指导/指示", "guide", 0],
    ["kinh nghiệm", "经验", "experience", 0],
    ["điểm", "分数/观点", "score", 0],
    ["táo", "苹果", "apple", 0],
    ["mua", "买", "bought", 0],
    ["dẫn", "引领/指导", "led", 0],
    ["sân", "沥青/院子", "pitch", 0],
    ["áo", "外套/衬衫", "coat", 0],
    ["khối lượng", "大量的/体积", "mass", 0],
    ["thẻ", "卡片", "card", 0],
    ["ban nhạc", "乐队", "band", 0],
    ["dây", "绳索/金属丝", "rope", 0],
    ["trượt", "滑", "slip", 0],
    ["giành chiến thắng", "赢", "win", 0],
    ["mơ", "梦", "dream", 0],
    ["buổi tối", "晚上", "evening", 0],
    ["điều kiện", "状况", "condition", 0],
    ["thức ăn chăn nuôi", "喂养/动物饲料", "feed", 0],
    ["công cụ", "工具", "tool", 0],
    ["tổng số", "全部的", "total", 0],
    ["cơ bản", "基本的", "basic", 0],
    ["mùi", "闻", "smell", 0],
    ["thung lũng", "谷", "valley", 0],
    ["cũng không", "也不/两者都不", "nor", 0],
    ["đôi", "双倍的/一对", "double", 0],
    ["ghế", "座位/椅子", "seat", 0],
    ["tiếp tục", "继续", "continue", 0],
    ["khối", "堵塞", "block", 0],
    ["biểu đồ", "图表", "chart", 0],
    ["mũ", "帽子", "hat", 0],
    ["bán", "卖", "sell", 0],
    ["thành công", "成功", "success", 0],
    ["công ty", "公司", "company", 0],
    ["trừ", "减去/除了", "subtract", 0],
    ["sự kiện", "事件", "event", 0],
    ["riêng", "特别的/私人的", "particular", 0],
    ["thỏa thuận", "交易/同意", "deal", 0],
    ["bơi", "游泳", "swim", 0],
    ["hạn", "学期", "term", 0],
    ["ngược lại", "对面的", "opposite", 0],
    ["vợ", "妻子", "wife", 0],
    ["giày", "鞋", "shoe", 0],
    ["vai", "肩膀", "shoulder", 0],
    ["lây lan", "传播", "spread", 0],
    ["sắp xếp", "安排", "arrange", 0],
    ["trại", "营", "camp", 0],
    ["phát minh", "发明了", "invent", 0],
    ["bông", "棉布", "cotton", 0],
    ["Sinh", "出生", "born", 0],
    ["xác định", "决定/确认", "determine", 0],
    ["lít", "夸脱/升", "quart", 0],
    ["chín", "九/成熟", "nine", 0],
    ["xe tải", "卡车", "truck", 0],
    ["tiếng ồn", "噪音", "noise", 0],
    ["mức", "等级", "level", 0],
    ["cơ hội", "机会", "chance", 0],
    ["thu thập", "收集", "gather", 0],
    ["cửa hàng", "店铺", "shop", 0],
    ["căng ra", "拉紧", "stretch", 0],
    ["ném", "扔", "throw", 0],
    ["tỏa sáng", "闪耀", "shine", 0],
    ["tài sản", "财产/资产", "property", 0],
    ["cột", "柱子", "column", 0],
    ["phân tử", "分子", "molecule", 0],
    ["chọn", "选择", "select", 0],
    ["sai", "错误的", "wrong", 0],
    ["màu xám", "灰色的", "gray", 0],
    ["lặp lại", "重复", "repeat", 0],
    ["yêu cầu", "要求", "require", 0],
    ["rộng", "广阔/宽的", "broad", 0],
    ["chuẩn bị", "准备", "prepare", 0],
    ["muối", "盐", "salt", 0],
    ["mui", "鼻子/兜帽", "nose", 0],
    ["số nhiều", "复数/许多", "plural", 0],
    ["tức giận", "愤怒/生气的", "anger", 0],
    ["xin", "宣称/询问", "claim", 0],
    ["lục", "大陆/绿色的", "continent", 0],
  ],
};