// VSL1 Vocabulary - 564 words, 12 units
var VN_VOCAB = VN_VOCAB || {};
VN_VOCAB['vsl1'] = [
    ['anh', '你（第二人称，用于年轻男子，同龄或年长）', 'you (second person, for young man, same age or older)', 1],
    ['bạn bè', '朋友', 'friend(s)', 1],
    ['bà', '您/你（用于女士、年长女性）', 'you (for madam, old woman)', 1],
    ['các', '诸位/你们（用于人称代词前的复数前缀）', 'a pluralizer used before personal pronouns', 1],
    ['cám ơn', '谢谢，感谢', 'thank you, to thank', 1],
    ['chào', '你好，打招呼', 'hello, to greet', 1],
    ['chị', '你（用于女士、同龄或年长的年轻女性，相当于姐）', 'you (for madam, young woman same age or older)', 1],
    ['cô', '您/你（用于小姐、女老师）', 'you (for miss, female teacher)', 1],
    ['cô giáo', '女老师', 'teacher (female)', 1],
    ['còn', '那么…呢，至于', 'and (about)', 1],
    ['có ... không?', '…吗？（用于是非疑问句的句型）', 'an interrogative structure used to form a Yes/No question', 1],
    ['cũng', '也', 'also', 1],
    ['đàn ông', '男人', 'man', 1],
    ['em', '你（用于孩子、比自己年轻的人，相当于妹/弟）', 'you (for child, younger)', 1],
    ['gặp', '见面，见', 'to meet, to see', 1],
    ['gì', '什么', 'what', 1],
    ['hẹn gặp lại', '再见', 'see you again', 1],
    ['không', '不，没有', 'no, not', 1],
    ['mạnh', '健康的，身体好的', 'to be fine, healthy', 1],
    ['là', '是', 'to be', 1],
    ['ông', '您/你（用于先生、年长男性）', 'you (for sir, old man)', 1],
    ['phụ nữ', '女人，妇女', 'woman', 1],
    ['rất vui được', '很高兴能…', 'pleased to...', 1],
    ['sinh viên', '大学生，学生', 'student', 1],
    ['tên', '名字', 'name', 1],
    ['thầy', '您（用于男老师）', 'you (for male teacher)', 1],
    ['tôi', '我', 'I, me', 1],
    ['xin lỗi', '对不起，抱歉', 'excuse me', 1],
    ['ấy', '那（用于将第二人称代词转为第三人称，如 anh ấy = 他）', 'used to change the second person pronoun to the third person', 2],
    ['ai', '谁', 'who', 2],
    ['Anh', '英国', 'England', 2],
    ['dây', '这，这里（近处）', 'this (here, close at hand)', 2],
    ['đấy', '那，那些', 'that, those', 2],
    ['đó', '那，那些', 'that, those', 2],
    ['Đức', '德国', 'Germany', 2],
    ['Hàn Quốc', '韩国', 'Korea', 2],
    ['Mỹ', '美国', 'United States', 2],
    ['nào', '哪，哪个？', 'which?', 2],
    ['người', '人', 'person, people', 2],
    ['người Đức', '德国人', 'German person', 2],
    ['người Pháp', '法国人', 'French person', 2],
    ['người Úc', '澳大利亚人', 'Australian person', 2],
    ['Nhật Bản', '日本', 'Japan', 2],
    ['nước', '国家', 'country, nation', 2],
    ['phải không', '对吗？，是不是？', "is that right?, ... isn't it?", 2],
    ['Pháp', '法国', 'France', 2],
    ['Trung Quốc', '中国', 'China', 2],
    ['Úc', '澳大利亚', 'Australia', 2],
    ['và', '和，与', 'and', 2],
    ['vâng', '是的（礼貌回答）', 'yes', 2],
    ['Việt Nam', '越南', 'Vietnam', 2],
    ['ăn', '吃', 'to eat', 3],
    ['bây giờ', '现在', 'now', 3],
    ['bác sĩ', '医生 / 医师', 'physician, doctor', 3],
    ['bệnh viện', '医院', 'hospital', 3],
    ['bình thường', '平常 / 正常 / 没事', 'as usual, normal, all right', 3],
    ['bưu điện', '邮局', 'post office', 3],
    ['ca sĩ', '歌手', 'singer', 3],
    ['cho', '给 / 为', 'for', 3],
    ['chờ', '等 / 等待', 'to wait', 3],
    ['công ty', '公司', 'company', 3],
    ['dạo này', '最近 / 这日子', 'these days', 3],
    ['du lịch', '旅游 / 观光', 'tourism, to travel', 3],
    ['đâu', '哪里', 'where', 3],
    ['đang', '正在 (表示进行时)', 'word used to indicate s.th. in progress', 3],
    ['đằng kia', '那里 / 那边', 'over there', 3],
    ['để', '为了 / 以便', 'to, in order to', 3],
    ['đến', '到 / 来 / 抵达', 'to come, to arrive', 3],
    ['đi', '去 / 走', 'to go', 3],
    ['đợi', '等 / 等待', 'to wait', 3],
    ['đón', '接 / 迎接', 'to welcome, to pick up', 3],
    ['giáo viên', '老师 / 教师', 'teacher', 3],
    ['hôm nay', '今天', 'today', 3],
    ['học', '学 / 学习', 'to learn, to study', 3],
    ['kỹ sư', '工程师', 'engineer', 3],
    ['làm việc', '做 / 工作', 'to do, to work', 3],
    ['lên xe', '上车', 'to get into a car', 3],
    ['mệt', '累 / 疲倦', 'tired', 3],
    ['mời', '请 / 邀请', 'to invite', 3],
    ['nghề nghiệp', '职业 / 工作', 'profession, occupation', 3],
    ['nhà', '家 / 房子', 'house', 3],
    ['nhân viên', '职员 / 员工', 'employee, staff', 3],
    ['nhân viên tiếp thị', '营销人员 / 市场推广人员', 'marketing personnel', 3],
    ['nhiều', '多 / 许多', 'many, a lot of', 3],
    ['nội trợ', '家庭主妇', 'housewife', 3],
    ['nước ngoài', '国外 / 外国', 'foreign, overseas', 3],
    ['ở', '在 / 住', 'to be, to stay, at, in', 3],
    ['phải', '对 / 正确 / 必须', 'right', 3],
    ['quốc tịch', '国籍', 'nationality', 3],
    ['sân bay', '机场 / 航空港', 'airport', 3],
    ['sống', '居住', 'to live', 3],
    ['sinh sống', '生活', 'to live', 3],
    ['tài xế', '司机', 'driver', 3],
    ['thành phố', '城市 / 市镇', 'city, town', 3],
    ['thư ký', '秘书', 'secretary', 3],
    ['thợ chụp hình', '摄影师', 'photographer', 3],
    ['tiếng Việt', '越南语', 'Vietnamese language', 3],
    ['trường', '学校', 'school', 3],
    ['về', '回 / 归 / 关于', 'to go home', 3],
    ['xe ô tô', '汽车', 'car', 3],
    ['xe hơi', '汽车', 'car', 3],
    ['y tá', '护士', 'nurse', 3],
    ['báo “Phụ nữ”', '《妇女》杂志', '“Women” Magazine', 4],
    ['chợ', '市场', 'market', 4],
    ['cơ quan', '机关、办公室', 'office', 4],
    ['của', '的', 'of', 4],
    ['Đại học Khoa học Xã hội và Nhân văn', '人文社会科学大学', 'University of Social Sciences and Humanities', 4],
    ['điện thoại', '电话', 'telephone', 4],
    ['địa chỉ', '地址', 'address', 4],
    ['đọc', '读、阅读', 'to read', 4],
    ['được', '可以、能够', 'can, be able', 4],
    ['đường', '路、街道', 'road, way, street', 4],
    ['giám đốc', '经理、总经理、主任', 'director', 4],
    ['giới thiệu', '介绍', 'to introduce', 4],
    ['hay/hoặc', '或者', 'or', 4],
    ['hiện nay', '现今、目前', 'at present', 4],
    ['hôm qua', '昨天', 'yesterday', 4],
    ['lái xe', '开车、驾驶', 'to drive', 4],
    ['lẻ', '（用于百/千位后有零时）零...', 'used to indicate the second digit when it is a zero', 4],
    ['lớp', '班级', 'class', 4],
    ['mấy', '几、多少', 'how many, how much', 4],
    ['một ít', '一点儿、一些', 'a little, a few', 4],
    ['một chút', '一点儿、一些', 'a little, a few', 4],
    ['nấu ăn', '做饭、烹饪', 'to cook', 4],
    ['năm', '年', 'year', 4],
    ['ngân hàng', '银行', 'bank', 4],
    ['ngàn', '千', 'thousand', 4],
    ['nghìn', '千', 'thousand', 4],
    ['nghe', '听', 'to listen to, to hear', 4],
    ['ngồi', '坐', 'to sit', 4],
    ['nhà hàng', '饭店、餐厅', 'restaurant', 4],
    ['nói', '说、谈话', 'to speak, to say, to talk', 4],
    ['phóng viên', '记者', 'journalist, reporter', 4],
    ['quận', '郡、（市辖）区', 'district', 4],
    ['rưỡi', '半、一半', '... and a half', 4],
    ['số', '号码、数字', 'number', 4],
    ['tháng', '月、月份', 'month', 4],
    ['tiếng', '声音、语言', 'voice, language', 4],
    ['tiếng Anh', '英语', 'English', 4],
    ['tiếng Hàn Quốc', '韩语', 'Korean language', 4],
    ['tiếng Nga', '俄语', 'Russian language', 4],
    ['tiếng Nhật', '日语', 'Japanese language', 4],
    ['tiếng Pháp', '法语', 'French language', 4],
    ['tiếng Trung Quốc', '中语、中文', 'Chinese language', 4],
    ['tốt', '好', 'good, well', 4],
    ['trăm', '百', 'hundred', 4],
    ['viết', '写', 'to write', 4],
    ['với', '和、同、跟', 'with', 4],
    ['xin', '请', 'please', 4],
    ['ăn tối', '吃晚饭', 'to have dinner', 5],
    ['ăn trưa', '吃午饭', 'to have lunch', 5],
    ['bận', '忙', 'to be busy', 5],
    ['bắt đầu', '开始', 'to start, to begin', 5],
    ['bao nhiêu', '多少', 'bao nhiêu', 5],
    ['bia', '啤酒', 'bia', 5],
    ['buổi', '某个时间段（早/中/晚）', 'session, period, time (of day)', 5],
    ['căn tin', '食堂、小卖部', 'canteen, cafeteria', 5],
    ['cà phê đen', '黑咖啡', 'coffee (black/milk/iced milk)', 5],
    ['cà phê sữa đá', '冰奶咖', 'coffee (black/milk/iced milk)', 5],
    ['chiều', '下午', 'afternoon, evening', 5],
    ['cũng vậy', '也一样', 'likewise, also, me too', 5],
    ['đêm', '夜间、深夜', 'night', 5],
    ['đi chơi', '去玩、出去逛', 'to go out (for fun), to hang out', 5],
    ['đi học', '去上学', 'to go to school', 5],
    ['đi ngủ', '去睡觉', 'to go to sleep', 5],
    ['đoàn', '团队、代表团', 'group, delegation, troupe', 5],
    ['đúng giờ', '准时（~点整）', "on time (~ o'clock)", 5],
    ['giờ', '小时、点（时间）', "hour, o'clock", 5],
    ['giỏi', '优秀、擅长', 'skillful, good at, clever', 5],
    ['học viên', '学员、学生', 'student, trainee, learner', 5],
    ['kém', '差（几点差几分）', 'bad (at time ~), poor (performance)', 5],
    ['khách', '客人', 'guest, customer, client', 5],
    ['khách sạn', '酒店、旅馆', 'hotel', 5],
    ['khó', '难', 'difficult', 5],
    ['khởi hành', '出发、启程', 'to depart, to set off', 5],
    ['lớn', '大=to', 'big, large, grown-up', 5],
    ['máy bay', '飞机', 'airplane, aircraft', 5],
    ['trễ', '迟、晚', 'late, delayed', 5],
    ['muộn', '迟、晚', 'late, delayed', 5],
    ['nay', '这（用于时间词后）', 'this (used after a term indicating time)', 5],
    ['ngày', '天', 'day', 5],
    ['ngày mai', '明天', 'tomorrow', 5],
    ['nghỉ trưa', '午休', 'lunch break', 5],
    ['nhà hàng', '餐厅', 'restaurant', 5],
    ['nhưng', '但是', 'but', 5],
    ['nó', '他/她/它', 'he/she/it', 5],
    ['phải', '必须', 'must, to have to', 5],
    ['phim', '电影', 'film', 5],
    ['phút', '分钟', 'minute', 5],
    ['rất', '非常', 'very', 5],
    ['rồi', '已经', 'already', 5],
    ['sách', '书', 'book', 5],
    ['sáng', '早上', 'morning', 5],
    ['sớm', '早，快', 'early, soon', 5],
    ['tại', '在（家，地点）', 'at (home, place)', 5],
    ['tại sao', '为什么', 'why', 5],
    ['thế à', '真的吗？（表确认）', 'really? (question for confirmation)', 5],
    ['thích', '喜欢', 'to like', 5],
    ['thường', '通常，经常', 'usually, often', 5],
    ['thức dậy', '起床', 'to get up, to wake up', 5],
    ['ti vi', '电视', 'television', 5],
    ['tiếng đồng hồ', '小时', 'hour', 5],
    ['tối', '晚上', 'evening', 5],
    ['từ', '从', 'from', 5],
    ['trưa', '中午', 'noon', 5],
    ['tuyến', '线路', 'line', 5],
    ['uống', '喝', 'to drink', 5],
    ['vì', '因为', 'because', 5],
    ['xe lửa', '火车', 'train', 5],
    ['xem', '看', 'to watch', 5],
    ['bản tin', '新闻报道', 'news report', 6],
    ['bến xe', '车站', 'station', 6],
    ['cô gái', '女孩', 'girl', 6],
    ['dạy', '教', 'to teach', 6],
    ['gia đình', '家庭', 'family', 6],
    ['hay', '好', 'good, well', 6],
    ['họ', '他们', 'they', 6],
    ['kênh', '频道', 'channel', 6],
    ['khách hàng', '客户', 'client, customer', 6],
    ['khoảng', '大约', 'about, approximately', 6],
    ['lâu quá', '太久', 'for long time', 6],
    ['lúc', '在（时间）', 'at (time)', 6],
    ['muốn', '想要', 'to want', 6],
    ['ngày kia', '后天', 'the day after tomorrow', 6],
    ['nhà thờ', '教堂', 'church', 6],
    ['nhà vệ sinh', '洗手间', 'rest room, W.C', 6],
    ['người Anh', '英国人/英语', 'English', 6],
    ['ngủ trưa', '午睡', 'take afternoon naps', 6],
    ['nói chuyện', '谈话', 'to talk, to chat', 6],
    ['phim hoạt hình', '动画片', 'cartoon', 6],
    ['quá', '太，非常', 'very, too', 6],
    ['quán', '店', 'shop', 6],
    ['sang', '去', 'to go', 6],
    ['sau đó', '然后', 'and then, after that', 6],
    ['tập thể dục', '做运动', 'to do physical exercise', 6],
    ['thế giới', '世界', 'world', 6],
    ['thợ điện', '电工', 'electrician', 6],
    ['tiếng nước ngoài', '外语', 'foreign language', 6],
    ['tin tức', '新闻=tin', 'news', 6],
    ['trong nước', '国内', 'domestic, within a country', 6],
    ['Anh văn', '英语', 'English language', 7],
    ['ban ngày', '白天', 'day time', 7],
    ['bao giờ', '何时', 'when?', 7],
    ['bao lâu', '多久', 'how long?', 7],
    ['biển', '海', 'sea', 7],
    ['bơi', '游泳', 'to swim', 7],
    ['buồn', '悲伤', 'sad', 7],
    ['chủ', '老板', 'boss', 7],
    ['chúc', '祝愿', 'word used to wish someone well', 7],
    ['chúng tôi', '我们（不包括听者）', 'we (excluding the listener)', 7],
    ['đã', '了（表过去）', 'word used to indicate s.th has happened in the past', 7],
    ['địa lý', '地理', 'geography', 7],
    ['đó', '那', 'that', 7],
    ['gọi điện thoại', '打电话', 'to call (telephone)', 7],
    ['gửi', '发送', 'to send', 7],
    ['hơi', '有点', 'somewhat, rather', 7],
    ['học bài', '复习功课', 'to revise a lesson', 7],
    ['hơn', '比……多', 'more than', 7],
    ['hỏi', '问', 'to ask', 7],
    ['ít', '少', 'few', 7],
    ['lần', '次，回', 'a time, a turn', 7],
    ['lịch sử', '历史', 'history', 7],
    ['lãnh', '收到=lĩnh', 'to receive', 7],
    ['lương', '工资', 'pay, salary', 7],
    ['mẹ', '妈妈', 'mother', 7],
    ['năm sau', '明年', 'next year', 7],
    ['này', '这', 'this', 7],
    ['nên', '所以', 'therefore', 7],
    ['ngoại ngữ', '外语', 'foreign language', 7],
    ['ngủ', '睡觉', 'to sleep', 7],
    ['nhận', '收到', 'to receive', 7],
    ['nhạc', '音乐', 'music', 7],
    ['nhanh', '快', 'fast, quickly', 7],
    ['nhớ', '想念，记得', 'to miss, to remember', 7],
    ['ở đây', '这里', 'here', 7],
    ['quà', '礼物', 'present, gift', 7],
    ['rỗi rảnh', '空闲', 'free, unoccupied', 7],
    ['rủ', '邀请', 'to invite', 7],
    ['sắp', '即将', 'soon (refers to the near future)', 7],
    ['sẽ', '将', 'will', 7],
    ['tất cả', '所有', 'all of', 7],
    ['tắm', '洗澡', 'to bathe/to take a bath', 7],
    ['tham quan', '参观', 'to visit', 7],
    ['tháng giêng', '一月', 'January', 7],
    ['tháng trước', '上个月', 'next month', 7],
    ['thi', '考试', 'to take an examination', 7],
    ['thời giờ', '时间（抽象概念）=thì giờ', 'time (abstract concept)', 7],
    ['thư', '信', 'letter', 7],
    ['thứ', '第……', 'word used before a number to form an ordinal number (-th)', 7],
    ['tiếc', '遗憾', 'to be sorry, to regret', 7],
    ['tiền', '钱', 'money', 7],
    ['trả', '支付', 'to pay', 7],
    ['trong', '在……里面', 'in', 7],
    ['trung tâm ngoại ngữ', '外语中心', 'foreign language center', 7],
    ['tuần', '周', 'week', 7],
    ['văn học/văn', '文学', 'literature', 7],
    ['vi tính', '电脑(máy~) ', 'computer', 7],
    ['việc', '事情', 'thing', 7],
    ['tháng sau', '下个月', 'last month', 8],
    ['bên cạnh', '旁边', 'next', 8],
    ['bên phải', '右边', 'on the right', 8],
    ['cây số', '公里', 'kilometer', 8],
    ['cảnh sát', '警察', 'police', 8],
    ['chỉ', '只，仅仅', 'just', 8],
    ['chỗ', '地方', 'place', 8],
    ['chưa', '还没', 'yet', 8],
    ['chúng ta', '我们（包括听者）', 'we (including the listener)', 8],
    ['có lẽ', '也许', 'perhaps, maybe', 8],
    ['có thể', '可能，能够', 'to be able to, possible', 8],
    ['dừng lại', '停止', 'to stop', 8],
    ['đầu tiên', '第一', 'first', 8],
    ['đắt', '昂贵的=mắc', 'expensive', 8],
    ['đạp', '踩踏板', 'to pedal', 8],
    ['đề nghị', '提议', 'to propose, to suggest', 8],
    ['đến nơi', '到达', 'to arrive', 8],
    ['đi bộ', '步行', 'to walk, to go on foot', 8],
    ['điện thoại công cộng', '公用电话', 'public telephone', 8],
    ['đối diện', '对面', 'across from, opposite', 8],
    ['đứng', '站', 'to stand', 8],
    ['gần', '近', 'next to, near', 8],
    ['gần đây', '附近', 'nearby, near here', 8],
    ['góc', '拐角 (~ đường)', 'corner', 8],
    ['hỏi thăm', '问候', 'to address someone,', 8],
    ['kêu', '叫，喊=gọi', 'to call, to order', 8],
    ['khá xa', '相当远', 'far away', 8],
    ['không ... đâu', '一点也不', 'not at all', 8],
    ['lắm', '很，非常', 'very, so', 8],
    ['lạc đường', '迷路', 'to lose the way', 8],
    ['làm ơn', '请，劳驾', 'please, could you', 8],
    ['mang', '拿，带', 'to bring', 8],
    ['mét', '米（距离）', 'meter (distance)', 8],
    ['mình', '我们（口语）', 'we', 8],
    ['mới', '刚刚（表示刚发生）', 'just (indicating immediate past)', 8],
    ['nặng', '重', 'heavy', 8],
    ['ngã tư', '十字路口', 'cross intersection', 8],
    ['ngon', '美味', 'delicious', 8],
    ['nhà hát', '剧院', 'music theatre', 8],
    ['nhà sách', '书店', 'bookshop', 8],
    ['nhẹ', '轻（重量）', 'light (in weight)', 8],
    ['nhỏ', '小', 'small', 8],
    ['nơi', '地方', 'place', 8],
    ['nữa', '再，又', 'more', 8],
    ['ừ', '是（应答声）', 'yes', 8],
    ['phía', '边，方向', 'side, direction', 8],
    ['rẽ', '转弯', 'to turn', 8],
    ['sau', '后面', 'after, behind', 8],
    ['tắc xi', '出租车', 'taxi', 8],
    ['thẳng', '直', 'straight', 8],
    ['thêm', '更多', 'more', 8],
    ['tiệm ăn', '餐馆', 'restaurant', 8],
    ['tiệm sửa xe', '修车铺', 'car or motorbike repair shop', 8],
    ['tốn tiền', '费钱，浪费钱', 'costly, to waste money', 8],
    ['từ ... đến ...', '从……到……', 'from ... to ...', 8],
    ['trạm xăng', '加油站', 'gas station', 8],
    ['trạm xe buýt', '公交车站', 'bus stop', 8],
    ['trả lời', '回答', 'to answer', 8],
    ['trái', '左', 'left', 8],
    ['trước', '在……之前，前面', 'before, in front of', 8],
    ['túi xách', '包，手提包', 'bag, handbag', 8],
    ['vào', '进入', 'to come in, to enter', 8],
    ['xa', '远', 'far', 8],
    ['xích lô', '三轮车', 'cyclo, pedicab', 8],
    ['bất tiện', '不方便', 'inconvenient', 9],
    ['bắc', '北', 'North', 9],
    ['bằng', '通过（方式）', 'by', 9],
    ['biển', '海', 'sea', 9],
    ['cách', '距离', 'distance from', 9],
    ['chậm', '慢', 'slow, slowly', 9],
    ['chỉ ... thôi', '只', 'only', 9],
    ['chạy', '跑，驾驶', 'to run, to drive', 9],
    ['chơi', '玩', 'to play', 9],
    ['chuyến', '趟（量词）', 'trip', 9],
    ['đẹp', '美丽，漂亮', 'beautiful, pretty', 9],
    ['đô la', '美元', 'dollar', 9],
    ['ga xe lửa', '火车站', 'train station', 9],
    ['giao thông', '交通', 'traffic', 9],
    ['giá', '价格', 'cost, price', 9],
    ['hãng hàng không', '航空公司', 'airline company', 9],
    ['khá', '相当，颇', 'rather, fairly, quite', 9],
    ['khách sạn 5 sao', '五星级酒店', 'five star hotel', 9],
    ['lâu', '久，长时间', 'long time', 9],
    ['lái', '驾驶', 'to drive', 9],
    ['mất', '花费（时间）', 'to take (time)', 9],
    ['mỗi', '每', 'each, every', 9],
    ['mua', '买', 'to buy', 9],
    ['nằm', '位于', 'to lay, to be located', 9],
    ['nên', '应该', 'should', 9],
    ['nếu', '如果 (. thì ..).', 'if; if ..., then ...', 9],
    ['như', '像，如同', 'like, as', 9],
    ['phòng bán vé', '售票处', 'ticket office', 9],
    ['rẻ', '便宜', 'cheap', 9],
    ['sinh nhật', '生日', 'birthday', 9],
    ['tàu thủy', '船', 'ship', 9],
    ['theo', '根据', 'according to', 9],
    ['thời gian', '时间', 'time', 9],
    ['tiện lợi', '方便', 'convenient', 9],
    ['tỷ phú', '亿万富翁', 'billionaire', 9],
    ['vậy', '那么（置于句末表疑问）', 'particle placed at the end of a question to ask more about something', 9],
    ['vé', '票', 'ticket', 9],
    ['vé khứ hồi', '往返票', 'round trip ticket', 9],
    ['vé một chiều', '单程票', 'one way ticket', 9],
    ['xe đạp', '自行车', 'bicycle', 9],
    ['xe đò/xe khách', '城际巴士', 'intercities bus', 9],
    ['xe máy', '摩托车', 'motorcycle', 9],
    ['anh trai', '哥哥', 'elder brother', 10],
    ['ba/bố', '爸爸', 'father', 10],
    ['bà nội', '奶奶', 'grandmother (paternal)', 10],
    ['bà ngoại', '外婆', 'grandmother (maternal)', 10],
    ['bất hạnh', '不幸', 'unhappy', 10],
    ['bạn thân', '亲密的朋友', 'close friend', 10],
    ['bán', '卖', 'to sell', 10],
    ['câu hỏi', '问题', 'question', 10],
    ['chăm chỉ', '努力，勤奋', 'hard, hard-working, industrious', 10],
    ['chị cả', '大姐=chị hai', 'eldest sister', 10],
    ['chị gái', '姐姐', 'elder sister', 10],
    ['chồng', '丈夫', 'husband', 10],
    ['chọn', '选择', 'to choose, to select', 10],
    ['chung', '共同', 'together', 10],
    ['công viên', '公园', 'park', 10],
    ['con', '孩子', 'child', 10],
    ['con cả', '第一个孩子，最大的', 'first child, oldest child', 10],
    ['con gái', '女儿', 'daughter', 10],
    ['con trai', '儿子', 'son', 10],
    ['con út', '最小的孩子', 'youngest child', 10],
    ['cùng', '一起，相同', 'together, same', 10],
    ['đã... chưa', '已经……了吗？', 'have... yet (used to form question)', 10],
    ['độc thân', '单身', 'single', 10],
    ['đông', '拥挤', 'crowded', 10],
    ['đứa', '孩子（量词）', 'a classifier used for children', 10],
    ['em trai', '弟弟', 'younger brother', 10],
    ['già', '老', 'old', 10],
    ['giàu', '富', 'rich', 10],
    ['hạnh phúc', '幸福', 'happy', 10],
    ['học sinh', '学生', 'pupil', 10],
    ['kinh tế', '经济', 'economics', 10],
    ['lập gia đình', '结婚', 'to get married', 10],
    ['lớn tuổi', '年老', 'aged', 10],
    ['mẹ', '妈妈=má', 'mother', 10],
    ['mình', '自己（反身代词）', '-self (a pronoun used to replace the subject pronoun)', 10],
    ['nghèo', '贫穷', 'poor', 10],
    ['người yêu', '爱人', 'lover', 10],
    ['nhỏ', '小，年轻', 'small, young', 10],
    ['ông nội', '爷爷', 'grandfather (paternal)', 10],
    ['quê', '乡下，故乡', 'countryside, hometown, fatherland', 10],
    ['quen', '熟悉的', 'known, familiar', 10],
    ['thức khuya', '熬夜', 'to stay up late', 10],
    ['từ điển', '字典', 'dictionary', 10],
    ['trái cây', '水果', 'fruit', 10],
    ['trẻ', '年轻的', 'young', 10],
    ['tuổi', '年龄', 'age, year(s) old', 10],
    ['vợ', '妻子', 'wife', 10],
    ['vui vẻ', '高兴的', 'joyful, glad', 10],
    ['xuống', '下去', 'down', 10],
    ['ông ngoại', '外公', 'grandfather (maternal)', 11],
    ['bánh xèo', '越式煎饼', 'VN-style pancake', 11],
    ['bánh tráng', '越式米纸', 'VN-style rice paper', 11],
    ['bào', '告诉', 'to tell', 11],
    ['bình dân', '大众的，便宜的', 'popular, cheap', 11],
    ['bò bít tết', '牛排', 'beefsteak', 11],
    ['bò tái chanh', '柠檬生牛肉', 'rare beef with lemon', 11],
    ['cá', '鱼', 'fish', 11],
    ['cả', '所有', 'all', 11],
    ['cả hai', '两者都', 'both', 11],
    ['chai', '瓶子', 'bottle', 11],
    ['chả giò', '春卷', 'spring roll', 11],
    ['chén', '碗=bát', 'bowl', 11],
    ['chỗ ngồi', '座位', 'seat', 11],
    ['cơm', '米饭', '(cooked) rice', 11],
    ['cua', '螃蟹', 'crab', 11],
    ['cửa hàng', '商店', 'store, shop', 11],
    ['tiệm', '店', 'store, shop', 11],
    ['do', '由于', 'by, due to (a person or thing)', 11],
    ['dĩa', '盘子', 'plate', 11],
    ['dùng', '吃，喝', 'to eat, to drink', 11],
    ['đặc biệt', '特别的', 'special', 11],
    ['đóng', '关闭', 'to close', 11],
    ['đôi', '双，对', 'pair', 11],
    ['đũa', '筷子', 'chopsticks', 11],
    ['gà', '鸡', 'chicken', 11],
    ['gì ... cũng ...', '一切/任何……', 'everything/anything', 11],
    ['gói', '包裹', 'package', 11],
    ['gởi tiền', '汇款', 'to send money', 11],
    ['hấp muối', '盐蒸', 'steamed and salted', 11],
    ['hút thuốc', '抽烟', 'to smoke (cigarettes)', 11],
    ['kem', '冰淇淋', 'ice cream', 11],
    ['khác', '不同的/其他', 'different/other', 11],
    ['khi', '当……时', 'when', 11],
    ['không ... gì ...', '一点也不', 'not at all', 11],
    ['khuyên', '建议', 'to advise', 11],
    ['loại', '种类', 'a kind, a sort', 11],
    ['lon', '罐', 'a can', 11],
    ['ly', '玻璃杯', 'a glass', 11],
    ['miền Nam', '南方地区', 'Southern region', 11],
    ['món ăn', '菜肴', 'dish', 11],
    ['món uống', '饮料', 'beverage', 11],
    ['mở', '打开', 'to open', 11],
    ['nấu', '烹饪', 'to cook', 11],
    ['nổi tiếng', '著名的', 'famous', 11],
    ['nước', '水', 'water', 11],
    ['nước cam', '橙汁', 'orange juice', 11],
    ['nước chanh', '柠檬汁', 'lemon juice', 11],
    ['nước ngọt', '软饮/汽水', 'soft drink/soda', 11],
    ['nước suối', '矿泉水', 'mineral water', 11],
    ['nước dừa', '椰子汁', 'coconut juice', 11],
    ['nóng', '热的', 'hot', 11],
    ['ướp lạnh', '冷藏', 'keep cold, refrigerated', 11],
    ['phở', '河粉汤', 'Vietnamese noodle soup', 11],
    ['rô ti', '烤', 'roasted', 11],
    ['rượu', '酒', 'wine, alcohol', 11],
    ['sang', '豪华的', 'luxurious', 11],
    ['say', '醉的', 'drunk', 11],
    ['sinh tố', '水果冰沙', 'fruit shake', 11],
    ['tất cả', '所有', 'all', 11],
    ['tây', '西式(món ăn ~)', 'western (~ food)', 11],
    ['thiếu', '缺乏', 'to lack', 11],
    ['thức ăn', '食物', 'dish, food', 11],
    ['thực đơn', '菜单', 'menu', 11],
    ['thịt', '肉', 'meat', 11],
    ['thịt bò', '牛肉', 'beef', 11],
    ['thịt gà', '鸡肉', 'chicken', 11],
    ['thịt heo', '猪肉', 'pork', 11],
    ['thử', '尝试', 'to try', 11],
    ['thuốc lá', '香烟', 'cigarette', 11],
    ['tính tiền', '结账', 'to calculate the bill', 11],
    ['tô', '大碗', 'big bowl', 11],
    ['tôm nướng', '烤虾', 'grilled shrimp', 11],
    ['trà đá', '冰茶', 'iced tea', 11],
    ['trẻ', '迟到', 'late', 11],
    ['xong', '完成', 'finish', 11],
    ['xúp', '汤', 'soup', 11],
    ['xúp cua', '蟹肉汤', 'crab soup', 11],
    ['ba mẹ', '父母=bố mẹ/ba má', 'parents', 12],
    ['chở', '运载，搬运', 'to carry, to haul', 12],
    ['cũ', '旧的（指物）', 'old (of things)', 12],
    ['cứ', '一直做某事', 'to take/to keep doing', 12],
    ['đau đầu', '头痛', 'headache', 12],
    ['nhức đầu', '头痛', 'headache', 12],
    ['đồng bằng', '三角洲', 'delta', 12],
    ['định', '打算', 'to intend', 12],
    ['đời', '型号', 'model', 12],
    ['đói', '饿', 'hungry', 12],
    ['em út', '最小的妹妹/弟弟', 'youngest sister/ ~ brother', 12],
    ['giúp', '帮助', 'to help', 12],
    ['hiểu', '理解', 'to understand', 12],
    ['hướng', '方向', 'direction', 12],
    ['làng', '村庄', 'village', 12],
    ['mát mẻ', '凉爽', 'cool', 12],
    ['môn', '科目 (~học)', 'subject', 12],
    ['mới', '新的', 'new', 12],
    ['ngã ba', '丁字路口', 'T junction', 12],
    ['người ta', '人们', 'people', 12],
    ['quẹo', '转弯', 'to make a turn', 12],
    ['ra', '出去，向北', 'to go out, to go North', 12],
    ['rồi', '离开', 'to leave', 12],
    ['sinh', '出生', 'to give birth to, to be born', 12],
    ['sợ', '害怕', 'to be afraid', 12],
    ['tỉnh', '省', 'province', 12],
    ['tháng chạp', '十二月', 'December', 12],
    ['toán', '数学', 'mathematics', 12],
    ['trên', '在……上面', 'on', 12],
    ['trước khi', '在……之前', 'before', 12],
    ['xe khách', '长途巴士', 'intercity bus', 12],
    ['xe máy', '摩托车', 'motorcycle', 12],
    ['yên tĩnh', '安静', 'quiet', 12],
];