var VN_VOCAB = VN_VOCAB || {};
VN_VOCAB['vsl2'] = [
  ["áo khoác", "外套 / 大衣", "coat", 1],
  ["áo sơ mi", "衬衫", "shirt", 1],
  ["bài hát", "歌曲", "song", 1],
  ["bảo hành", "保修 / 保质", "guarantee / warranty", 1],
  ["bền", "耐用", "durable", 1],
  ["bò", "牛", "bull, cow", 1],
  ["bưởi", "柚子", "pomelo, grapefruit", 1],
  ["chất lượng", "质量", "quality", 1],
  ["chôm chôm", "红毛丹", "rambutan", 1],
  ["chó", "狗", "dog", 1],
  ["chuối", "香蕉", "banana", 1],
  ["cỡ", "尺寸 / 号码", "size", 1],
  ["cuối cùng", "最后 / 最终", "finally, in the end", 1],
  ["dày", "厚", "thick", 1],
  ["dễ dùng", "易用", "easy to use", 1],
  ["dễ thương", "可爱", "lovely", 1],
  ["dép", "拖鞋", "slipper", 1],
  ["giày", "鞋子", "shoes", 1],
  ["giày cao gót", "高跟鞋", "high heels", 1],
  ["giày dép", "鞋袜 / 鞋类", "foot-wear", 1],
  ["giường", "床", "bed", 1],
  ["hao", "耗费 / 浪费", "to waste, be wasteful", 1],
  ["hiện đại", "现代", "modern", 1],
  ["hiệu", "品牌 / 牌子", "brand, mark", 1],
  ["kí / ki lô", "公斤 / 千克", "kilogram", 1],
  ["loại", "种类", "kind", 1],
  ["mặc", "穿", "to wear", 1],
  ["măng cụt", "山竹", "mangosteen", 1],
  ["màn hình", "屏幕", "screen", 1],
  ["màu", "颜色", "colour", 1],
  ["máy", "机器", "machine", 1],
  ["máy ảnh", "照相机", "camera", 1],
  ["máy cassette", "录音机", "cassette player", 1],
  ["máy giặt", "洗衣机", "washing machine", 1],
  ["máy lạnh", "空调", "air-conditioner", 1],
  ["mèo", "猫", "cat", 1],
  ["mũ", "帽子", "hat", 1],
  ["nâu", "棕色 / 褐色", "brown", 1],
  ["đầu tiên", "首先 / 第一", "first", 1],
  ["nải (~ chuối)", "（一）梳（香蕉）", "hand, bunch (~ of bananas)", 1],
  ["người bán", "卖方 / 售货员", "seller", 1],
  ["nhãn", "龙眼 / 桂圆", "longan", 1],
  ["nho", "葡萄", "grape", 1],
  ["điện", "电", "electricity", 1],
  ["điện tử", "电子", "electronic", 1],
  ["đồng hồ", "手表 / 钟", "watch, clock", 1],
  ["đồng ý", "同意", "to agree", 1],
  ["đỏ", "红色", "red", 1],
  ["nói thách", "漫天要价 / 虚报价格", "to say a price higher than the real price", 1],
  ["đủ", "足够", "enough", 1],
  ["phân", "厘米", "centimeter", 1],
  ["phòng", "房间", "room", 1],
  ["quần áo", "衣服", "clothes", 1],
  ["quạt máy", "电风扇", "fan", 1],
  ["rộng", "宽 / 广", "large, wide", 1],
  ["sầu riêng", "榴莲", "durian", 1],
  ["sản xuất", "生产", "to produce", 1],
  ["thấy", "看见", "to see", 1],
  ["thể thao", "体育 / 运动", "sports", 1],
  ["thơm", "香", "perfumed, aromatic, scented", 1],
  ["thời hạn", "期限", "term", 1],
  ["tím", "紫色", "violet", 1],
  ["trắng", "白色", "white", 1],
  ["triệu", "百万", "million", 1],
  ["tủ", "柜子", "closet", 1],
  ["tủ lạnh", "冰箱", "refrigerator", 1],
  ["vàng", "黄色", "yellow", 1],
  ["vịt", "鸭子", "duck", 1],
  ["xanh", "绿色 / 蓝色", "green, blue", 1],
  ["xám", "灰色", "grey", 1],
  ["xoài", "芒果", "mango", 1],
  ["bệnh (ốm)", "生病", "to be ill, be sick", 2],
  ["bệnh nhân / người bệnh", "病人", "patient", 2],
  ["bữa ăn", "餐 / 饭次", "meal", 2],
  ["buồn ngủ", "困倦 / 想睡", "to be sleepy", 2],
  ["buồn nôn", "恶心 / 想吐", "to feel nauseous", 2],
  ["cảm", "感冒", "cold, illness", 2],
  ["cảm thấy", "感觉", "to feel", 2],
  ["cho phép", "允许 / 许可", "to permit, to allow, to authorize", 2],
  ["chóng mặt", "头晕", "to feel dizzy", 2],
  ["dễ chịu", "舒服 / 缓解", "to feel better", 2],
  ["dối / ẩu", "草率 / 粗心", "careless, reckless", 2],
  ["dược sĩ", "药剂师", "pharmacist, chemist", 2],
  ["hết", "完 / 结束", "to finish, to end", 2],
  ["ho", "咳嗽", "to cough", 2],
  ["ít khi / hiếm khi", "很少 / 罕见", "rarely", 2],
  ["khó chịu", "难受 / 不舒服", "to feel bad, uncomfortable", 2],
  ["khỏi (~ bệnh)", "痊愈 / 病好了", "to recover from, to be cured, to get well", 2],
  ["kiểm tra", "检查", "to test, to examine", 2],
  ["kỹ / kỹ lưỡng", "仔细 / 彻底", "careful, thorough", 2],
  ["lầm / nhầm", "错 / 误", "to be wrong", 2],
  ["lo / lo lắng", "担心 / 焦虑", "to worry", 2],
  ["mệt mỏi", "疲劳 / 累", "to be tired", 2],
  ["một số", "一些 / 若干", "some, a number of", 2],
  ["mỏi", "（肌肉）酸累", "be tired", 2],
  ["đau", "疼 / 痛", "sore, ache, pain", 2],
  ["đau bụng", "肚子疼", "to have a stomachache, bellyache", 2],
  ["đau răng", "牙疼", "to have a toothache", 2],
  ["ngay (~ tức thì)", "马上 / 立即", "right away, immediately", 2],
  ["nghỉ", "休息", "to have a rest", 2],
  ["ngủ ngon", "睡得香 / 好眠", "to sleep well", 2],
  ["nha sĩ", "牙医", "dentist", 2],
  ["nhà riêng", "私宅 / 民房", "private house, residence", 2],
  ["đi khám bệnh", "去看病", "to go to the doctor", 2],
  ["nông dân", "农民", "farmer", 2],
  ["đỡ (~ đau, đói)", "缓解 / 减轻", "to relieve (one's pain, one's hunger)", 2],
  ["phòng khám tư (phòng mạch tư)", "私人诊所", "private clinic", 2],
  ["sốt", "发烧", "to have a fever", 2],
  ["sức khỏe", "健康", "health", 2],
  ["tai nạn", "事故 / 意外", "accident", 2],
  ["thở", "呼吸", "to breathe", 2],
  ["thuốc", "药", "medicines", 2],
  ["thuốc ho", "止咳药", "cough medicine", 2],
  ["thuốc ngủ", "安眠药", "sleeping-pill", 2],
  ["trông... có vẻ...", "看起来...", "to look like", 2],
  ["uống thuốc", "吃药", "to take medicines", 2],
  ["viêm họng", "咽喉炎 / 喉咙痛", "sore throat", 2],
  ["viên (~ thuốc)", "（药）粒 / 片", "tablet, pill", 2],
  ["X quang", "X光", "X - ray", 2],
  ["yếu", "虚弱 / 弱", "weak, feeble", 2],
  ["ca nhạc", "音乐表演 / 歌舞", "musical performance", 3],
  ["cần / cần phải", "需要 / 必须", "need, must", 3],
  ["cấp cứu", "急救", "emergency", 3],
  ["cá nhân", "个人", "individual", 3],
  ["chuông", "铃", "bell", 3],
  ["công an", "公安 / 警察", "policeman", 3],
  ["công cộng", "公共", "public", 3],
  ["cứu hỏa", "消防 / 救火", "fire fighting", 3],
  ["di động (điện thoại ~)", "移动（电话）/ 手机", "mobile (~ phone)", 3],
  ["dịch vụ", "服务", "services", 3],
  ["dự báo thời tiết", "天气预报", "to forecast (weather)", 3],
  ["giải đáp", "解答 / 解释", "to explain", 3],
  ["giáo sư", "教授", "professor", 3],
  ["gọi (~ điện / ~ điện thoại)", "打（电话）", "to phone, to call", 3],
  ["hình như", "好像 / 似乎", "to seem, to appear", 3],
  ["hợp đồng", "合同", "contract", 3],
  ["khoa", "科 / 系", "department, faculty", 3],
  ["khu vực (bưu điện ~)", "区域 / 地区（邮政 ~）", "local area (~ post)", 3],
  ["lần", "次 / 遍", "time occurance", 3],
  ["liên lạc", "联系", "contact", 3],
  ["lịch", "日历 / 挂历", "calendar, schedule", 3],
  ["lúc nãy / hồi nãy", "刚才", "a moment ago", 3],
  ["mặt hàng", "品种 / 货物", "article, item", 3],
  ["nhấc máy (~ điện thoại)", "拿起话筒 / 接电话", "to pick up the receiver", 3],
  ["nhắn / nhắn lại", "留言 / 转告", "to leave a message", 3],
  ["nhắn tin", "发短信", "to send a message", 3],
  ["điểm / địa điểm", "地点", "place, location", 3],
  ["đường dây", "线路", "line", 3],
  ["nói lại", "重说 / 转述", "to repeat", 3],
  ["quầy (~ sách báo)", "柜台（报刊亭）", "stall, kiosk (~newstand)", 3],
  ["quản lý", "管理", "to manage", 3],
  ["quên", "忘记", "to forget", 3],
  ["rạp", "剧院 / 电影院", "cinema / theatre", 3],
  ["reng / reo", "（铃）响", "to ring", 3],
  ["riêng", "私人的 / 单独的", "private", 3],
  ["thẻ điện thoại", "电话卡", "phone card", 3],
  ["thiết yếu", "必要 / 切要", "necessary, indispensable", 3],
  ["thông tin", "信息", "information", 3],
  ["tiền cước / cước phí", "费用 / 资费", "cost, fee, toll", 3],
  ["tự động", "自动", "automatic", 3],
  ["trung học", "中学", "high school", 3],
  ["tỷ giá hối đoái", "汇率", "rate of exchange", 3],
  ["văn hóa", "文化", "culture", 3],
  ["xây dựng", "建设 / 建筑", "to build, to construct", 3],
  ["xem lại", "再看 / 复查", "to reexamine, to review", 3],
  ["xin phép", "请假 / 请求许可", "to ask for permission", 3],
  ["xong", "完 / 好了", "to finish, be completed", 3],
  ["áo ấm", "毛衣 / 大衣", "sweater, jacket", 4],
  ["bạn gái", "女朋友", "girlfriend", 4],
  ["bà con", "亲戚", "relatives", 4],
  ["bãi biển", "海滩", "beach", 4],
  ["bảo vệ", "保卫 / 守护", "guard", 4],
  ["cao nguyên", "高原", "highland, plateau", 4],
  ["cảnh / thắng cảnh", "风景 / 名胜", "view, scenery", 4],
  ["chẳng", "不 / 并非", "not", 4],
  ["chính trị", "政治", "politics", 4],
  ["chương trình", "程式/程序/章程/节目", "program", 4],
  ["chuẩn bị", "准备", "to prepare", 4],
  ["cố đô", "古都", "old capital", 4],
  ["công nghiệp", "工业 / 工业的", "industry, industrial", 4],
  ["cuối (~năm)", "年末 / 最后", "at the end of (~ the year)", 4],
  ["dịp", "机会 / 时机", "occasion, chance", 4],
  ["giống", "像 / 相似", "like, similar to; to resemble", 4],
  ["hàng / hằng (~năm)", "每年 / 每", "every (~year)", 4],
  ["hành lý", "行李", "luggage", 4],
  ["hải cảng", "海港", "seaport", 4],
  ["hè", "夏天", "summer", 4],
  ["hồ", "湖", "lake", 4],
  ["hoa / bông", "花", "flower", 4],
  ["hướng dẫn", "指导 / 引导", "to guide", 4],
  ["hướng dẫn viên", "导游", "guide", 4],
  ["kéo dài", "延长 / 持续", "to prolong, to extend", 4],
  ["khán giả", "观众", "spectator, audience", 4],
  ["khu", "区域 / 地区", "zone, area", 4],
  ["ki lô mét / cây số", "公里", "kilometer", 4],
  ["Lào", "老挝", "Laos", 4],
  ["lý tưởng", "理想", "ideal", 4],
  ["mưa", "下雨", "to rain", 4],
  ["một mình", "独自 / 孤独", "be alone, lonely", 4],
  ["mực nước biển", "海平面", "sea-level", 4],
  ["mùa", "季节", "season", 4],
  ["năm ngoái", "去年", "last year", 4],
  ["đảo", "岛屿", "island, isle", 4],
  ["đều", "都 / 全部", "both, all", 4],
  ["ngạc nhiên", "惊讶", "be surprised", 4],
  ["nghỉ mát", "避暑 / 度假", "to take vacation", 4],
  ["nghe nói", "听说", "to hear that...", 4],
  ["người dân", "人民 / 居民", "people", 4],
  ["người Hoa", "华人 / 华裔", "Chinese", 4],
  ["nhóm", "小组 / 团体", "group", 4],
  ["độ cao", "高度", "height", 4],
  ["đoạn (~đường)", "路段", "section (of road)", 4],
  ["nơi", "地点 / 地方", "place", 4],
  ["nóng", "热", "hot", 4],
  ["ô-nhiễm", "污染 / 被污染的", "pollution, polluted", 4],
  ["ô tô", "汽车", "car", 4],
  ["phương tiện", "方式 / 工具 (交通工具)", "means", 4],
  ["phục vụ", "服务", "to serve", 4],
  ["quan trọng", "重要", "important", 4],
  ["quảng cáo", "广告", "advertisement", 4],
  ["sông", "河", "river", 4],
  ["tập trung", "集中", "to concentrate", 4],
  ["thân thiện", "友好", "friendly", 4],
  ["thật (~tuyệt vời)", "真的 (太棒了)", "really (~wonderful)", 4],
  ["thăm", "参观 / 拜访", "to visit", 4],
  ["Thái Lan", "泰国", "Thailand", 4],
  ["thu (mùa~)", "秋天", "autumn", 4],
  ["thủ đô", "首都", "capital", 4],
  ["thú vị", "有趣", "interesting, pleasant", 4],
  ["tổ chức", "组织", "to organize", 4],
  ["tuyệt", "极好的 / 绝佳的", "great, wonderful", 4],
  ["vẫn", "仍然", "still", 4],
  ["viện bảo tàng", "博物馆", "museum", 4],
  ["xe điện", "电车 / 有轨电车", "train (electric)", 4],
  ["xe điện ngầm", "地铁", "subway", 4],
  ["bờ biển", "海边 / 海岸", "seashore", 5],
  ["chìa khóa", "钥匙", "key", 5],
  ["cửa sổ", "窗户", "window", 5],
  ["cũ", "旧的 (物品)", "old (thing)", 5],
  ["du khách", "游客", "tourist", 5],
  ["du lịch ba lô", "背包客 (旅游)", "backpacker", 5],
  ["gần đây", "最近", "recently, these days", 5],
  ["giặt", "洗（衣服）", "to wash (~ clothes)", 5],
  ["giải thích", "解释", "to explain", 5],
  ["giùm / giúp / hộ", "帮 / 替", "do sth. for sb.", 5],
  ["hộ chiếu", "护照", "passport", 5],
  ["hóa đơn", "账单 / 发票", "bill, receipt", 5],
  ["khách", "客人", "guest", 5],
  ["miễn phí", "免费", "free", 5],
  ["đăng ký (~ vé)", "登记 / 订（票）", "to book (~ a ticket)", 5],
  ["đặt (~ phòng)", "预订（房间）", "to book, to reserve (~ a room)", 5],
  ["ngoài ra", "此外", "besides", 5],
  ["nhân tiện", "顺便", "by the way, at the same time", 5],
  ["nhà khách", "宾馆 / 招待所", "guesthouse", 5],
  ["nhà trọ", "旅店 / 客栈", "inn", 5],
  ["đổi", "换 / 兑换", "to change", 5],
  ["đủ", "足够", "enough", 5],
  ["phòng (~ đơn / ~ đôi)", "房间（单人间 / 双人间）", "room (single ~ / double ~)", 5],
  ["quyết định", "决定", "to decide", 5],
  ["rẻ", "便宜", "cheap", 5],
  ["sắp xếp", "安排", "to arrange", 5],
  ["sạch", "干净", "clean", 5],
  ["sẵn sàng", "准备就绪", "be ready", 5],
  ["sửa", "修理 / 修改", "to repair", 5],
  ["tầng", "层（楼层）", "floor", 5],
  ["tàu hỏa / xe lửa", "火车", "train", 5],
  ["thoải mái", "舒服 / 自在", "(to feel) at ease, be relaxed", 5],
  ["thoáng mát", "通风凉快", "airy / ventilated", 5],
  ["thuê", "租", "to rent", 5],
  ["tiện nghi", "设施便利 / 舒适", "comfortable / facilities", 5],
  ["tiếp tân", "接待 / 接待员", "reception, receptionist", 5],
  ["tìm đến", "寻访 / 找上门", "to ask how to get (a place)", 5],
  ["trống (phòng ~)", "空的（空房）", "vacant", 5],
  ["vì sao", "为什么", "why", 5],
  ["xe du lịch", "旅游巴士", "tour bus", 5],
  ["ấn tượng (trường phái~)", "印象（印象派）", "impressionist", 6],
  ["ảnh (bức ~)", "照片 / 图画", "picture, photo", 6],
  ["bộ (~ quần áo)", "套（一套衣服）", "a set (~ of clothes)", 6],
  ["bò sữa", "奶牛", "milk cow", 6],
  ["chụp (~ảnh)", "照相 / 拍摄", "to take photo of", 6],
  ["chủ", "主人 / 店主", "owner", 6],
  ["chuyện", "事情 / 故事", "matter / story", 6],
  ["cúm", "流感", "flu", 6],
  ["êm ả", "宁静 / 平静", "calm, peaceful", 6],
  ["hàng xóm", "邻居", "neighbor", 6],
  ["học tập", "学习", "to study", 6],
  ["hỏng / hư", "坏了", "be broken down / out of order", 6],
  ["khỏi", "痊愈 / 离开", "out of / recovered", 6],
  ["lâu đài", "城堡 / 宫殿", "palace, castle", 6],
  ["làm ăn", "做生意", "to do business", 6],
  ["lớn lên", "长大", "to grow up", 6],
  ["mọi (~người)", "每一 / 所有（所有人）", "every (~body)", 6],
  ["nhà cho thuê", "出租房", "house for rent", 6],
  ["nông trại", "农场", "farm", 6],
  ["nuôi", "养育 / 饲养", "to bring up, to feed", 6],
  ["quen thuộc", "熟悉", "familiar, well-known", 6],
  ["sinh (~ ra)", "出生", "be born", 6],
  ["sổ mũi", "流鼻涕", "to have a running nose", 6],
  ["tặng", "赠送", "to offer, to give", 6],
  ["tăng (~ giá)", "增加（涨价）", "increase (~ the price of)", 6],
  ["tài sản", "财产", "property", 6],
  ["thân ái", "亲爱 / 友好", "friendly / dear", 6],
  ["thay đổi", "改变 / 变化", "to change", 6],
  ["thương yêu", "亲爱 / 疼爱", "to love", 6],
  ["tôm nướng", "烤虾", "grilled shrimp", 6],
  ["tranh", "画 / 图画", "painting", 6],
  ["vài", "几个 / 一些", "some", 6],
  ["vườn", "花园 / 菜园", "garden", 6],
  ["vở", "练习本", "notebook", 6],
  ["xây", "建造", "to build", 6],
  ["yêu mến", "喜爱 / 钟爱", "to love, to like, to adore", 6],
  ["bất đắc dĩ", "不得已", "unwillingly", 7],
  ["bên cạnh", "旁边", "next to", 7],
  ["biệt thự", "别墅", "villa", 7],
  ["bồn tắm", "浴缸", "bathtub", 7],
  ["căn hộ", "公寓单元", "flat, apartment", 7],
  ["cao ốc", "大厦 / 摩天大楼", "building, sky-scraper", 7],
  ["cho thuê", "出租", "to rent", 7],
  ["chỗ", "地方 / 位置", "place, spot", 7],
  ["chung cư", "公寓楼", "apartment building", 7],
  ["chủ nhà", "房东 / 屋主", "owner of the house", 7],
  ["cứ", "尽管 / 持续", "to keep doing", 7],
  ["dọn", "搬（家）", "to move (to a house)", 7],
  ["dọn dẹp", "打扫 / 收拾", "to tidy up", 7],
  ["ga ra", "车库", "garage", 7],
  ["kế bên", "隔壁 / 旁边", "next to", 7],
  ["lầu", "楼 / 层", "floor", 7],
  ["lớp học", "教室", "classroom", 7],
  ["máy tắm nước nóng", "热水器（洗澡用）", "water heater (for taking a shower)", 7],
  ["ngoại ô", "郊区", "outskirts of town, suburbs", 7],
  ["nguyên căn", "整栋（租房用）", "the whole house", 7],
  ["nhà bếp", "厨房", "kitchen", 7],
  ["nhà cửa", "房屋 / 住宅", "housing", 7],
  ["nhà mặt tiền", "临街房 / 店面房", "street front property", 7],
  ["nhà đất", "房地产 / 土地房屋", "real estate", 7],
  ["nhà tắm", "浴室", "bathroom", 7],
  ["phòng ăn", "餐厅", "dining room", 7],
  ["phòng khách", "客厅", "living room", 7],
  ["phòng ngủ", "卧室", "bedroom", 7],
  ["quạt trần", "吊扇", "ceiling fan", 7],
  ["sân", "院子", "yard", 7],
  ["sân sau", "后院", "back yard", 7],
  ["sân thượng", "天台 / 露台", "terrace (on roof)", 7],
  ["sân trước", "前院", "front yard", 7],
  ["siêu thị", "超市", "supermarket", 7],
  ["tầng lầu", "楼层", "floor", 7],
  ["tất nhiên", "当然", "of course, certainly", 7],
  ["thuê nhà", "租房", "to rent a house", 7],
  ["tiếp / tiếp tục", "继续", "to continue", 7],
  ["trang bị", "装备 / 配备", "to equip", 7],
  ["trệt", "一楼 / 底层", "ground floor", 7],
  ["trừ", "除去 / 减", "except", 7],
  ["trường học", "学校", "school", 7],
  ["trước khi", "在...之前", "before", 7],
  ["tùy theo", "取决于 / 随着", "to depend on", 7],
  ["tuy nhiên", "然而 / 但是", "however", 7],
  ["vị trí", "位置", "position, location", 7],
  ["vừa ý", "满意 / 合心意", "be satisfied", 7],
  ["bận rộn", "忙碌", "be busy", 8],
  ["bạo lực", "暴力", "violent", 8],
  ["báo (tờ ~)", "报纸", "newspaper", 8],
  ["bộ phim", "电影", "film", 8],
  ["bỏ", "放弃 / 扔掉", "to give up, to throw away", 8],
  ["buổi tối", "晚上", "evening", 8],
  ["câu cá", "钓鱼", "to fish", 8],
  ["cây / cây số", "公里", "kilometer", 8],
  ["cãi nhau", "吵架", "to argue", 8],
  ["cá", "鱼", "fish", 8],
  ["chính", "亲自 / 主要", "oneself (to distinguish one from others)", 8],
  ["chúng mình", "我们", "we, us", 8],
  ["cụng (ly)", "碰杯", "to clink glasses", 8],
  ["cuộc sống", "生活", "life", 8],
  ["dậy", "起床 / 醒来", "to get up, to wake up", 8],
  ["giải trí", "娱乐", "entertainment", 8],
  ["hài lòng", "满意", "be satisfied", 8],
  ["không bao giờ", "从不", "never", 8],
  ["khóc", "哭", "to cry", 8],
  ["kinh doanh", "经营 / 商业", "business", 8],
  ["lấy", "拿 / 取", "to take", 8],
  ["luôn luôn", "总是", "always", 8],
  ["mượn", "借", "to borrow", 8],
  ["người bán hàng", "售货员 / 卖家", "seller", 8],
  ["điều", "事情 / 事项", "thing, fact, matter", 8],
  ["đúng giờ", "准时", "on time", 8],
  ["phim hài", "喜剧片", "comedy", 8],
  ["phim truyền hình", "电视剧", "TV movies, TV dramas", 8],
  ["rửa mặt", "洗脸", "to wash face", 8],
  ["sở thích", "爱好", "hobby, liking", 8],
  ["ta (người ~)", "人们 / 我们 (咱)", "people", 8],
  ["tâm lý", "心理", "psychology", 8],
  ["tập", "集 / 册", "episode", 8],
  ["thỉnh thoảng", "有时", "sometimes", 8],
  ["thư viện", "图书馆", "library", 8],
  ["thông minh", "聪明", "intelligent", 8],
  ["thói quen", "习惯", "habit", 8],
  ["thú thật", "老实说", "to be honest, to tell the truth", 8],
  ["tự hào", "自豪", "to be proud", 8],
  ["tự tin", "自信", "to be self-confident", 8],
  ["trò", "游戏 / 玩法", "game", 8],
  ["trước đây", "以前 / 之前", "previously, formerly...", 8],
  ["truyện", "故事 / 小说", "story, tale", 8],
  ["văn học", "文学", "literature", 8],
  ["xã hội", "社会", "society, social", 8],
  ["xuất nhập khẩu", "进出口", "import - export", 8],
  ["âm nhạc", "音乐", "music", 9],
  ["ảnh", "照片", "picture, photo", 9],
  ["ba lô", "背包", "backpack, rucksack", 9],
  ["bạn đọc", "读者", "reader", 9],
  ["bướm", "蝴蝶", "butterfly", 9],
  ["bóng đá", "足球", "football", 9],
  ["cắm hoa", "插花", "to arrange flowers", 9],
  ["canh chua", "酸汤 (越南特色菜)", "sour soup", 9],
  ["chăm", "勤奋", "hard-working, industrious", 9],
  ["chanh", "柠檬", "lemon (fruit)", 9],
  ["chẳng hạn", "例如", "for example, such as", 9],
  ["công chức", "公职人员 / 公务员", "government official", 9],
  ["công việc", "工作", "work, job", 9],
  ["dân ca", "民歌", "folk song", 9],
  ["dám", "敢", "to dare", 9],
  ["diễn viên", "演员", "actor/ actress", 9],
  ["đỏ", "红色", "red", 9],
  ["ghét", "讨厌 / 恨", "to hate", 9],
  ["giữ", "保持 / 保留", "to keep", 9],
  ["hồng (màu~)", "粉红色", "pink (colour)", 9],
  ["kế hoạch", "计划", "plan", 9],
  ["khiêu vũ", "跳舞", "to dance", 9],
  ["kinh tế", "经济", "economy", 9],
  ["mập", "胖", "fat", 9],
  ["một lát", "一会儿", "a while (indefinite period of time)", 9],
  ["món (~ ăn)", "菜肴", "dish", 9],
  ["múa rối nước", "水上木偶戏", "water puppet", 9],
  ["đầu (ban ~)", "最初 / 开头", "first", 9],
  ["nghỉ hưu", "退休", "to be retired", 9],
  ["nhật báo", "日报", "daily newspaper", 9],
  ["nhạc nhẹ", "轻音乐", "soft music", 9],
  ["đi dạo", "散步", "to have a walk", 9],
  ["điện ảnh", "电影（艺术/产业）", "movie", 9],
  ["đừng", "不要 / 别", "do not (imperative)", 9],
  ["ưa thích", "喜爱 / 偏好", "to like, to prefer", 9],
  ["ước muốn", "愿望 / 想要", "hope, wish", 9],
  ["phim buồn", "悲剧片 / 忧伤的电影", "sad movie", 9],
  ["phỏng vấn", "面试 / 采访", "to interview", 9],
  ["rau", "蔬菜", "vegetable", 9],
  ["rau sống", "生菜 / 鲜菜", "leafy vegetable", 9],
  ["sắc đẹp", "美丽 / 美貌", "beauty", 9],
  ["sữa", "牛奶", "milk", 9],
  ["sưu tập", "收集 / 收藏", "to collect", 9],
  ["thân (bạn ~)", "亲密的（好朋友）", "close (~friend)", 9],
  ["tham gia", "参加", "to participate", 9],
  ["thời trang", "时尚 / 时装", "fashion", 9],
  ["tiểu thuyết", "小说", "novel", 9],
  ["tưới", "浇（水）", "to water (a plant)", 9],
  ["trà", "茶", "tea", 9],
  ["trọn gói (du lịch ~)", "全包 / 拼团（跟团游）", "package (~ tour)", 9],
  ["truyện ngắn", "短篇小说", "short story", 9],
  ["xưởng phim", "电影制片厂", "movie studio", 9],
  ["ban đêm", "半夜 / 晚间", "night", 10],
  ["bán hàng", "卖货 / 销售", "to sell", 10],
  ["bánh mì", "面包（也是越南法棍）", "bread", 10],
  ["căng", "紧张 / 紧", "tense", 10],
  ["căng thẳng", "压力大 / 紧张", "be stressful, be uptight", 10],
  ["càu nhàu", "抱怨 / 唠叨", "to grunt, to grumble", 10],
  ["châu Âu", "欧洲", "Europe", 10],
  ["châu Mỹ", "美洲", "America", 10],
  ["chỗ làm", "工作地点 / 单位", "workplace", 10],
  ["chứng chỉ", "证书 / 证明", "certificate", 10],
  ["chuyển", "移动 / 转移", "to move", 10],
  ["chuyên môn", "专业 / 专门", "qualification, skill", 10],
  ["chuyên ngành", "专业 / 主修", "specialty, major", 10],
  ["có khi", "有时 / 或许", "sometimes", 10],
  ["cử nhân", "学士", "Bachelor (degree)", 10],
  ["cuộc họp", "会议", "meeting", 10],
  ["dễ tính", "随和 / 脾气好", "easy going", 10],
  ["doanh nghiệp", "企业", "business, company", 10],
  ["dọc", "沿着", "along", 10],
  ["giấc mơ", "梦想", "dream", 10],
  ["hàng tháng", "每月", "every month, monthly", 10],
  ["hợp", "适合 / 匹配", "to fit, appropriate", 10],
  ["hơn nữa", "此外 / 更加", "moreover, additionally", 10],
  ["kế toán", "会计", "accountant", 10],
  ["khả năng", "能力 / 可能性", "ability", 10],
  ["khó tính", "挑剔 / 脾气差", "difficult (personality)", 10],
  ["kinh nghiệm", "经验", "experience", 10],
  ["kỷ luật", "纪律", "discipline, rule", 10],
  ["lao động", "劳动", "to work / labor", 10],
  ["lương bổng", "薪水 / 待遇", "salary", 10],
  ["lý do", "理由 / 原因", "reason", 10],
  ["mẫu giáo", "幼儿园", "kindergarten", 10],
  ["mặc dù", "虽然", "though", 10],
  ["mức lương", "工资水平", "salary level", 10],
  ["nặng nhọc", "繁重 / 辛苦", "heavy, hard, tired", 10],
  ["ngành", "行业 / 类别", "branch / field", 10],
  ["nghĩ", "想 / 认为", "to think", 10],
  ["nhà máy", "工厂", "factory, plant", 10],
  ["nhàn", "闲暇 / 清闲", "unoccupied, not busy", 10],
  ["đôi khi", "有时", "sometimes", 10],
  ["đồng nghiệp", "同事", "colleague", 10],
  ["ưa", "喜爱", "to like", 10],
  ["phù hợp", "合适 / 符合", "suitable, appropriate", 10],
  ["quan hệ", "关系", "relationship", 10],
  ["quản trị kinh doanh", "工商管理", "business administration", 10],
  ["sự thật", "真相 / 事实", "truth", 10],
  ["thấp", "矮 / 低", "short", 10],
  ["thiếu nhi", "儿童 / 少儿", "children", 10],
  ["thương mại", "贸易", "trade", 10],
  ["thưởng", "奖励 / 赏赐", "to reward", 10],
  ["thỏa thuận", "协议 / 达成一致", "to agree, to consent", 10],
  ["tin học", "信息技术 / 计算机科学", "informatics", 10],
  ["tốt nghiệp", "毕业", "to graduate", 10],
  ["trưởng phòng", "部门经理 / 科长", "head of department", 10],
  ["vất vả", "辛苦 / 艰难", "hard", 10],
  ["vòng quanh", "环绕 / 周围", "around", 10],
  ["xảy ra", "发生", "to happen", 10],
  ["xe tải", "卡车 / 货车", "van, truck", 10],
  ["chúc mừng", "祝贺", "congratulations", 10],
  ["an ủi", "安慰", "to console", 11],
  ["bạn trai", "男朋友", "boyfriend", 11],
  ["béo", "胖", "fat", 11],
  ["cậu bé", "小男孩", "little boy", 11],
  ["cái nết", "性格 / 德行", "virtue", 11],
  ["cái đẹp", "美丽 / 美感", "beauty", 11],
  ["chà", "哎呀 (感叹词)", "oh, well", 11],
  ["chết", "死", "to die", 11],
  ["cổ", "脖子", "neck", 11],
  ["cố gắng", "努力 / 尝试", "to attempt", 11],
  ["cởi mở", "开朗 / 开放", "open-minded", 11],
  ["cuộc đời", "一生 / 寿命", "life", 11],
  ["da", "皮肤", "skin", 11],
  ["dài", "长", "long", 11],
  ["dáng", "身材 / 体态", "shape, form (of person)", 11],
  ["dễ thương", "可爱", "lovely, cute", 11],
  ["ế chồng", "嫁不出去 / 剩女", "to not get married (girl)", 11],
  ["gầy", "瘦", "thin", 11],
  ["giật", "抢 / 拽", "to grab", 11],
  ["giảng bài", "讲课", "to explain the lesson", 11],
  ["huýt sáo", "吹口哨", "to whistle", 11],
  ["ích kỷ", "自私", "selfish", 11],
  ["khắp nơi", "到处", "everywhere", 11],
  ["kịp", "来得及", "in time", 11],
  ["lỗi lầm", "错误 / 过错", "mistake, error", 11],
  ["lời khen", "称赞 / 评语", "compliment", 11],
  ["lùn", "矮", "short", 11],
  ["mặt", "脸", "face", 11],
  ["mí (mắt)", "眼皮", "eyelid", 11],
  ["miệng", "嘴", "mouth", 11],
  ["môi", "嘴唇", "lips", 11],
  ["mong", "希望 / 盼望", "to hope, to expect", 11],
  ["mũi", "鼻子", "nose", 11],
  ["đánh", "打", "to hit, to fight", 11],
  ["nết", "性情 / 品德", "virtue", 11],
  ["đẹp trai", "帅哥 / 帅气", "handsome fellow", 11],
  ["ngắn", "短", "short (thing)", 11],
  ["đi lạc", "迷路", "to lose one's way", 11],
  ["đối với", "对于 / 针对", "for, about, according to", 11],
  ["nữ sinh", "女学生", "schoolgirl", 11],
  ["đuổi theo", "追赶", "to pursue, to chase", 11],
  ["phàn nàn", "抱怨 / 投诉", "to complain", 11],
  ["quê hương", "故乡 / 家乡", "homeland", 11],
  ["ra đời", "出生 / 问世", "to be born", 11],
  ["răng", "牙齿", "teeth", 11],
  ["si mê", "痴迷 / 沉迷", "to love passionately", 11],
  ["tẹt (~ mũi)", "塌（鼻子）", "flat (~ nose)", 11],
  ["thất vọng", "失望", "be disappointed", 11],
  ["thanh niên", "青年", "young people / youth", 11],
  ["thái độ", "态度", "attitude", 11],
  ["thon thả", "苗条", "slim (figure)", 11],
  ["tiệm ăn", "小饭馆", "small restaurant", 11],
  ["tính tình", "性情 / 脾气", "personality", 11],
  ["tốt bụng", "好心 / 善良", "nice, kind", 11],
  ["từ điển", "词典", "dictionary", 11],
  ["tóc", "头发", "hair", 11],
  ["tục ngữ", "俗语 / 谚语", "proverb", 11],
  ["út", "最小（排行最末）", "youngest (child)", 11],
  ["vui tính", "幽默 / 性格开朗", "congenial / cheerful", 11],
  ["áo cưới", "婚纱", "wedding dress", 12],
  ["áo vét", "西装外套", "suit coat", 12],
  ["bài viết", "文章", "article", 12],
  ["bông hồng / hoa hồng", "玫瑰花", "rose", 12],
  ["bó", "束 / 捆", "bouquet, bunch", 12],
  ["cài", "插 / 别（花）", "to pin (a flower)", 12],
  ["cả hai", "两个都", "both", 12],
  ["chịu", "忍受 / 承受", "to undergo, to suffer", 12],
  ["chú rể", "新郎", "bridegroom", 12],
  ["cô dâu", "新娘", "bride", 12],
  ["cộng tác viên", "合作者 / 投稿人", "collaborator", 12],
  ["công trình", "工程 / 项目", "works", 12],
  ["cười", "笑", "to smile, to laugh", 12],
  ["cửa", "门", "door", 12],
  ["dành cho", "专门用于 / 留给", "to be reserved for", 12],
  ["diện tích", "面积", "area, surface", 12],
  ["diện tích sử dụng", "使用面积", "habitable area", 12],
  ["dự tuyển", "竞选 / 应聘", "to apply for", 12],
  ["dữ liệu", "数据", "data", 12],
  ["duyên dáng", "优雅 / 妩媚", "charming, gracious", 12],
  ["gạch", "砖", "brick", 12],
  ["ghi chép", "记录", "to take notes", 12],
  ["giấy phép", "执照 / 许可证", "license", 12],
  ["giảm giá", "减价 / 打折", "to discount", 12],
  ["giảng dạy", "教学", "teaching, to teach", 12],
  ["hàng hiên", "走廊 / 凉台", "veranda", 12],
  ["hát", "唱歌", "to sing", 12],
  ["hẻm", "小巷", "small lane", 12],
  ["hiện", "现在 / 目前", "now, at present", 12],
  ["họa sĩ", "画家", "painter (artist)", 12],
  ["hưởng", "享受", "to enjoy", 12],
  ["khu phố", "街区 / 坊", "quarter (part of a city)", 12],
  ["kiếng", "玻璃 / 镜子", "glass", 12],
  ["liên hệ", "联系", "to contact", 12],
  ["luật", "法律", "law", 12],
  ["mạng", "网络", "net", 12],
  ["mến", "喜爱", "to love, to like", 12],
  ["đám cưới", "婚礼", "wedding ceremony", 12],
  ["đeo (~ cà vạt)", "佩戴（领带）", "to wear (~ a tie)", 12],
  ["ngoại thương", "外贸", "foreign trade", 12],
  ["ngôn ngữ", "语言", "language", 12],
  ["nhận dạng", "辨认 / 识别", "figure (of a person)", 12],
  ["đồ chơi", "玩具", "toys", 12],
  ["độc giả", "读者", "reader", 12],
  ["nữ diễn viên", "女演员", "actress", 12],
  ["nữ giới", "女性", "women, females", 12],
  ["đóng cửa", "关门", "to close a door", 12],
  ["ôm", "抱 / 拥抱", "to carry / hug", 12],
  ["ồn", "吵闹", "noisy", 12],
  ["Pháp văn", "法语", "French (language)", 12],
  ["phim kinh dị", "恐怖片", "horror film", 12],
  ["phòng thu", "录音室", "audio studio", 12],
  ["sắt", "铁", "iron", 12],
  ["sơ cấp", "初级", "elementary level", 12],
  ["tài", "才能 / 天才", "talent, talented", 12],
  ["thông thạo", "精通 / 流利", "fluently", 12],
  ["thoáng", "通风的 / 开阔", "ventilated", 12],
  ["thời sự", "时事 / 新闻", "news", 12],
  ["tính tình", "性情 / 脾气", "personality", 12],
  ["tư vấn", "咨询 / 顾问", "to consult, to advise", 12],
  ["trật tự", "秩序", "order", 12],
  ["trình độ", "程度 / 水平", "level", 12],
  ["trung cấp", "中级", "intermediate level", 12],
  ["tuần trăng mật", "蜜月", "honeymoon", 12],
  ["xanh lơ", "浅蓝色 / 天蓝色", "(bright) blue", 12],
  ["xinh đẹp", "漂亮", "beautiful, pretty", 12],
];
