// Vietnamese Vocabulary Data - Auto-generated from vietnamese-vocab-updated.json

var VN_VOCAB = {
  starter: [
    ["như", "比如/好像/同/当", "as/like", 0],
    ["tô", "我", "I", 0],
    ["mình", "自己/我/身体", "self/me/body", 0],
    ["mà", "而/却/那个", "that/but/which", 0],
    ["ông", "祖父/先生/他", "grandfather/Sir", 0],
    ["là", "是", "is/am/are/to be", 0],
    ["cho", "给/为了/让", "for/give/let", 0],
    ["trên", "在...上/以上", "on/above", 0],
    ["là", "是", "is/be", 0],
    ["với", "和/与/向", "with/to", 0],
    ["họ", "他们/姓氏", "they/surname", 0],
    ["được", "被/可以/得到", "be (passive)/can/get", 0],
    ["tại", "在/由于", "at/in/because of", 0],
    ["một", "一/一个", "one/a", 0],
    ["có", "有/是", "have/yes", 0],
    ["này", "这/这个", "this", 0],
    ["từ", "从/词", "from/word", 0],
    ["bởi", "由于/由/被", "by/because", 0],
    ["nóng", "热", "hot", 0],
    ["từ", "从/词", "from/word", 0],
    ["nhưng", "但是", "but", 0],
    ["những gì", "什么/所...的事情", "what/things that", 0],
    ["một số", "一些/若干", "some/a number of", 0],
    ["là", "是", "is", 0],
    ["nó", "它", "it", 0],
    ["anh", "你/哥哥/英", "you/older brother/British", 0],
    ["hoặc", "或者", "or", 0],
    ["có", "有", "have/had", 0],
    ["các", "这些/各位", "these/the (plural)", 0],
    ["của", "的/属于", "of/belong to", 0],
    ["để", "为了/让/放", "to/in order to/let/put", 0],
    ["và", "和", "and", 0],
    ["một", "一个/一", "a/one", 0],
    ["trong", "在...里/清晰", "in/within/clear", 0],
    ["chúng tôi", "我们(不含对方)", "we", 0],
    ["có thể", "可以/可能", "can/maybe", 0],
    ["ra", "出/出去", "out/go out", 0],
    ["khác", "其他/不同", "other/different", 0],
    ["là", "是", "were/is", 0],
    ["mà", "哪个/但/而", "which/but/that", 0],
    ["làm", "做/制造/工作", "do/make/work", 0],
    ["của họ", "他们的", "their", 0],
    ["thời gian", "时间", "time", 0],
    ["nếu", "如果", "if", 0],
    ["sẽ", "将/会", "will/shall", 0],
    ["như thế nào", "如何/怎样", "how", 0],
    ["nói", "说", "say/speak", 0],
    ["một", "一个/一", "an/one", 0],
    ["môi", "唇", "lip", 0],
    ["mỗi", "每/每个", "each/every", 0],
    ["nói", "说/告诉", "say/tell", 0],
    ["không", "不/没有/零", "no/not/zero", 0],
    ["bộ", "部/套/步", "set/department", 0],
    ["ba", "三/爸爸", "three/father", 0],
    ["muốn", "想/想要", "want", 0],
    ["không khí", "空气", "air", 0],
    ["cũng", "也/同样", "also/too", 0],
    ["chơi", "玩", "play", 0],
    ["nhỏ", "小", "small/little", 0],
    ["cuối", "末尾/最后", "end/last", 0],
    ["đặt", "放/放置/订购", "put/place/order", 0],
    ["nhà", "家/房屋", "home/house", 0],
    ["đọc", "读/阅读", "read", 0],
    ["tay", "手", "hand", 0],
    ["cổng", "门/门口/港口", "gate/port", 0],
    ["lớn", "大", "large/big", 0],
    ["chính tả", "拼写", "spelling", 0],
    ["thêm", "增加/更多", "add/more", 0],
    ["thậm chí", "甚至", "even", 0],
    ["đất", "土地/国家/土", "land/earth", 0],
    ["ở đây", "这里", "here", 0],
    ["phải", "必须/右边/正确", "must/right", 0],
    ["lớn", "大", "big", 0],
    ["cao", "高", "high/tall", 0],
    ["như vậy", "这样/如此", "such/so", 0],
    ["theo", "跟随/根据", "follow/according to", 0],
    ["hành động", "行为/行动", "act/action", 0],
    ["lý do tại sao", "为什么/理由", "why/reason why", 0],
    ["xin", "请/请求", "please/ask for", 0],
    ["người đàn ông", "男人", "man", 0],
    ["thay đổi", "改变/找零", "change", 0],
    ["đi", "去/走", "go/went", 0],
    ["ánh sáng", "光/明亮", "light", 0],
    ["loại", "类型/种类", "kind/type", 0],
    ["tắt", "关/熄灭", "off/turn off", 0],
    ["cần", "需要", "need", 0],
    ["nhà", "家/房子", "home/house", 0],
    ["hình ảnh", "图像/图片", "image/picture", 0],
    ["thử", "尝试/试验", "try/test", 0],
    ["chúng tôi", "我们", "us/we", 0],
    ["một lần nữa", "再次", "again/once more", 0],
    ["động vật", "动物", "animal", 0],
    ["điểm", "分/点/观点", "point/score", 0],
    ["mẹ", "母亲/妈妈", "mother/Mom", 0],
    ["thế giới", "世界", "world", 0],
    ["gần", "近/靠近", "near/close", 0],
    ["xây dựng", "建造/建设", "build/construct", 0],
    ["tự", "自/自己", "self", 0],
    ["đất", "地球/土地", "earth/land", 0],
    ["cha", "父亲/爸爸", "father", 0],
    ["bất kỳ", "任何", "any", 0],
    ["mới", "新/才", "new/just", 0],
    ["công việc", "工作", "work/job", 0],
    ["một phần", "部分", "part", 0],
    ["có", "有/在那儿", "have/take", 0],
    ["được", "被/得到/行", "get/be/can", 0],
    ["nơi", "地方/场所", "place", 0],
    ["thực hiện", "执行/制作", "made/perform", 0],
    ["sống", "居住/活", "live/living", 0],
    ["nơi", "哪里/地方", "where/place", 0],
    ["sau khi", "之后", "after", 0],
    ["trở lại", "返回/回来", "back/return", 0],
    ["ít", "少/一点", "little/few", 0],
    ["ch chỉ", "只/仅仅/指针", "only/just/point", 0],
    ["chung quanh", "周围/大约", "around", 0],
    ["người đàn ông", "男人", "man", 0],
    ["năm", "年/五", "year/five", 0],
    ["đến", "来/到", "come/arrive", 0],
    ["chương trình", "节目/计划/程序", "show/program", 0],
    ["mỗi", "每/每个", "every/each", 0],
    ["tốt", "好", "good", 0],
    ["tôi", "我(宾格)", "me/I", 0],
    ["cung cấp", "提供/给", "give/supply", 0],
    ["của chúng tôi", "我们的", "our", 0],
    ["dưới", "下/下面", "under/below", 0],
    ["tên", "名字/姓名", "name", 0],
    ["rất", "非常", "very", 0],
    ["thông qua", "通过", "through", 0],
    ["chỉ", "只是/刚", "just/only", 0],
    ["hình thức", "形式/形状", "form/shape", 0],
    ["câu", "句子", "sentence", 0],
    ["tuyệt vời", "伟大/极好", "great/wonderful", 0],
    ["nghĩ", "想/思考", "think", 0],
    ["nghi", "怀疑", "doubt/suspect", 0],
    ["nói", "说", "say/speak", 0],
    ["giúp", "帮助", "help", 0],
    ["thấp", "低/矮", "low/short", 0],
    ["dòng", "行/流/线条", "line/current/stream", 0],
    ["khác nhau", "不同", "different", 0],
    ["lần lượt", "依次/轮流", "turn/in turn", 0],
    ["nguyên nhân", "原因", "cause/reason", 0],
    ["nhiều", "多", "much/many", 0],
    ["có nghĩa là", "意思是", "means", 0],
    ["trước", "前/以前", "before/front", 0],
    ["di chuyển", "移动/搬家", "move", 0],
    ["ngay", "立刻/就/直接", "right/immediately", 0],
    ["cậu bé", "男孩", "boy", 0],
    ["cũ", "旧/老", "old", 0],
    ["quá", "太/过分/也", "too/over", 0],
    ["như nhau", "同样/相同", "same", 0],
    ["cô", "她/姑姑/老师", "she/Miss/aunt", 0],
    ["tất cả", "全部/所有", "all", 0],
    ["có", "有/在那儿", "there/have", 0],
    ["khi", "当...时", "when", 0],
    ["lên", "上", "up/go up", 0],
    ["sử dụng", "使用", "use", 0],
    ["của bạn", "你的", "your", 0],
    ["cách", "方式/距离", "way/distance", 0],
    ["về", "回/关于", "about/return", 0],
    ["nhiều", "多", "many/much", 0],
    ["sau đó", "然后/之后", "then/after that", 0],
    ["họ", "他们/姓", "them/they/surname", 0],
    ["viết", "写", "write", 0],
    ["sẽ", "将/会", "would/will", 0],
    ["như", "如同/像", "like/as", 0],
    ["để", "为了/让/让", "so/to/let", 0],
    ["các", "这些/各位", "these/the", 0],
    ["cô", "她/她的", "her/she", 0],
    ["lâu", "久/长久", "long/for a long time", 0],
    ["làm", "做/制造", "make/do", 0],
    ["điều", "事物/条", "thing/clause", 0],
    ["thấy", "看见/觉得", "see/feel", 0],
    ["anh", "他/你/哥哥", "him/you/brother", 0],
    ["hai", "二", "two", 0],
    ["có", "有", "has/have", 0],
    ["xem", "看/观察", "look/watch/see", 0],
    ["hơn", "比/更/超过", "more/than", 0],
    ["ngày", "天/日", "day", 0],
    ["có thể", "可以/可能", "could/maybe", 0],
    ["đi", "去", "go", 0],
    ["đến", "来/到", "come/arrive", 0],
    ["đã làm", "做了", "did", 0],
    ["số", "号码/数字", "number", 0],
    ["âm thanh", "声音", "sound", 0],
    ["không có", "没有", "no/not have", 0],
    ["nhất", "最/第一", "most/best", 0],
    ["nhân dân", "人民", "people", 0],
    ["của tôi", "我的", "my/mine", 0],
    ["hơn", "比/超过/结束", "over/than", 0],
    ["biết", "知道", "know", 0],
    ["nước", "水/国家", "water/country", 0],
    ["hơn", "比", "than", 0],
    ["gọi", "叫/称呼/打电话", "call", 0],
    ["đầu tiên", "第一", "first", 0],
    ["người", "人/谁", "person/who", 0],
    ["có thể", "可能", "maybe/may", 0],
    ["xuống", "下/向下", "down", 0],
    ["bên", "侧/边/方", "side/beside", 0],
    ["được", "被/得到/行", "been/get/can", 0],
    ["bây giờ", "现在", "now", 0],
    ["tìm", "找", "find", 0],
    ["đầu", "头/首", "head", 0],
    ["đứng", "站立", "stand", 0],
    ["riêng", "私/各自/单独", "own/private", 0],
    ["trang", "页", "page", 0],
    ["nên", "应该/所以", "should/so", 0],
    ["nước", "国家/水", "country/water", 0],
    ["tìm thấy", "找到/发现", "found", 0],
    ["câu trả lời", "答案/回答", "answer", 0],
    ["trường", "学校", "school", 0],
    ["phát triển", "发展/生长", "grow/develop", 0],
    ["nghiên cứu", "研究/学习", "study/research", 0],
    ["vẫn", "仍然", "still", 0],
    ["học", "学/学习", "learn/study", 0],
    ["nhà máy", "工厂", "factory/plant", 0],
    ["bìa", "封面/覆盖", "cover", 0],
    ["thực phẩm", "食物", "food", 0],
    ["ánh nắng mặt trời", "阳光", "sunshine", 0],
    ["bốn", "四", "four", 0],
    ["giữa", "之间/中间", "between/middle", 0],
    ["nhà nước", "国家/政府/状态", "state/government", 0],
    ["giữ", "保持/留", "keep/hold", 0],
    ["mắt", "眼睛", "eye", 0],
    ["không bao giờ", "绝不/从不", "never", 0],
    ["cuối cùng", "最后/最终", "last/final", 0],
    ["cho phép", "允许/让", "let/allow", 0],
    ["nghĩ", "想", "thought/think", 0],
    ["thành phố", "城市", "city", 0],
    ["cây", "树", "tree", 0],
    ["qua", "经过/过", "cross/pass", 0],
    ["trang trại", "农场", "farm", 0],
    ["cứng", "硬/努力/难", "hard", 0],
    ["bắt đầu", "开始", "start/begin", 0],
    ["might", "可能/也许", "might", 0],
    ["câu chuyện", "故事", "story", 0],
    ["cưa", "锯", "saw", 0],
    ["đến nay", "至今/远", "far/so far", 0],
    ["biển", "海", "sea", 0],
    ["vẽ", "画", "draw", 0],
    ["còn lại", "剩余", "left/remaining", 0],
    ["cuối", "晚/末", "late/end", 0],
    ["chạy", "跑", "run", 0],
    ["không", "不", "don’t/no", 0],
    ["trong khi", "当...时/虽然", "while", 0],
    ["báo chí", "报刊/新闻界/按", "press/journalism", 0],
    ["gần", "近/靠近/关", "close/near", 0],
    ["đêm", "夜晚", "night", 0],
    ["thực", "真实/实在", "real/true", 0],
    ["cuộc sống", "生活/生命", "life", 0],
    ["số", "数量/数字/很少", "few/number", 0],
    ["phía bắc", "北方", "north", 0],
    ["cuốn sách", "书", "book", 0],
    ["thực hiện", "执行/携带", "carry/perform", 0],
    ["mất", "丢/丢失/花费", "took/lost", 0],
    ["khoa học", "科学", "science", 0],
    ["ăn", "吃", "eat", 0],
    ["phòng", "房间/防备", "room/prevent", 0],
    ["người bạn", "朋友", "friend", 0],
    ["bắt đầu", "开始", "began/start", 0],
    ["ý tưởng", "想法/主意", "idea", 0],
    ["cá", "鱼", "fish", 0],
    ["núi", "山", "mountain", 0],
    ["ngăn chặn", "阻止/防止", "stop/prevent", 0],
    ["một lần", "一次/曾经", "once", 0],
    ["cơ sở", "基础/根据", "base/foundation", 0],
    ["nghe", "听", "hear/listen", 0],
    ["ngựa", "马", "horse", 0],
    ["cắt", "切/剪", "cut", 0],
    ["chắc chắn", "肯定/当然", "sure/certain", 0],
    ["xem", "看/观察", "watch/see", 0],
    ["màu", "颜色", "color", 0],
    ["khuôn mặt", "脸", "face", 0],
    ["gỗ", "木/木头", "wood", 0],
    ["chính", "主/主要", "main/chief", 0],
    ["mở", "开/打开", "open", 0],
    ["dường như", "似乎", "seems", 0],
    ["cùng", "同/一起", "together/same", 0],
    ["tiếp theo", "下一个/接着", "next", 0],
    ["trắng", "白", "white", 0],
    ["trẻ em", "孩子们", "children", 0],
    ["bắt đầu", "开始", "begin", 0],
    ["có", "有/得到", "got/have", 0],
    ["đi bộ", "走路/步行", "walk", 0],
    ["ví dụ", "例子/例如", "example", 0],
    ["giảm bớt", "减少/减轻/缓解", "ease/decrease", 0],
    ["giấy", "纸", "paper", 0],
    ["nhóm", "组/群/团体", "group", 0],
    ["luôn luôn", "总是/老是", "always", 0],
    ["nhạc", "乐/音乐", "music", 0],
    ["những", "这些/那些", "those/these", 0],
    ["cả hai", "两者/都", "both", 0],
    ["đánh dấu", "标记/符号", "mark", 0],
    ["thường", "常/经常", "often", 0],
    ["thư", "信/字母", "letter", 0],
    ["cho đến khi", "直到", "until", 0],
    ["dặm", "英里", "mile", 0],
    ["sông", "河", "river", 0],
    ["xe", "车", "car", 0],
    ["chân", "脚/腿", "foot/leg", 0],
    ["chăm sóc", "照看/照顾", "care/take care of", 0],
    ["thứ hai", "第二/星期一", "second/Monday", 0],
    ["đủ", "够/足够", "enough", 0],
    ["đồng bằng", "平原", "plain", 0],
    ["cô gái", "女孩", "girl", 0],
    ["thông thường", "通常", "usual", 0],
    ["trẻ", "年轻/幼", "young", 0],
    ["sẵn sàng", "准备就绪", "ready", 0],
    ["trên đây", "以上", "above", 0],
    ["bao giờ", "曾经/何时", "ever", 0],
    ["màu đỏ", "红", "red", 0],
    ["danh sách", "名单/列表", "list", 0],
    ["mặc dù", "虽然/尽管", "though", 0],
    ["cảm thấy", "感觉/觉得", "feel", 0],
    ["nói chuyện", "谈话/聊天", "talk", 0],
    ["chim", "鸟", "bird", 0],
    ["sớm", "早/快", "soon/early", 0],
    ["cơ thể", "身体", "body", 0],
    ["con chó", "狗", "dog", 0],
    ["gia đình", "家/家庭", "family", 0],
    ["trực tiếp", "直接", "direct", 0],
    ["đặt ra", "提出/摆出", "pose/set out", 0],
    ["lại", "再/又", "again", 0],
    ["bài hát", "歌/歌曲", "song", 0],
    ["đo lường", "测量", "measure", 0],
    ["cửa", "门", "door", 0],
    ["sản phẩm", "产品", "product", 0],
    ["đen", "黑", "black", 0],
    ["ngắn", "短", "short", 0],
    ["chữ số", "数字", "numeral/digit", 0],
    ["lớp", "课/班级/层", "class/layer", 0],
    ["gió", "风", "wind", 0],
    ["câu hỏi", "问题", "question", 0],
    ["xảy ra", "发生", "happen", 0],
    ["hoàn thành", "完成", "complete", 0],
    ["tàu", "船/火车", "ship/train", 0],
    ["khu vực", "区域", "area", 0],
    ["một nửa", "一半", "half", 0],
    ["đá", "石/冰", "rock/stone/ice", 0],
    ["để", "为了/让", "order/to/let", 0],
    ["lửa", "火", "fire", 0],
    ["nam", "南/男", "south/male", 0],
    ["vấn đề", "问题/事务", "problem/issue", 0],
    ["mảnh", "片/块", "piece", 0],
    ["nói", "说", "told/say", 0],
    ["biết", "知道", "knew/know", 0],
    ["vượt qua", "通过/超过", "pass", 0],
    ["từ", "自从/从", "since/from", 0],
    ["đầu", "头/顶", "top/head", 0]
    ["đứng", "站立/站着", "stand/stood", 0],
    ["riêng", "私人的/各自的/自己的", "private/own", 0],
    ["trang", "页", "page", 0],
    ["nên", "应该/所以", "should/so", 0],
    ["nước", "国家/水", "country/water", 0],
    ["tìm thấy", "找到/发现", "found", 0],
    ["câu trả lời", "答案/回答", "answer", 0],
    ["trường", "学校/领域", "school/field", 0],
    ["phát triển", "发展/生长", "develop/grow", 0],
    ["nghiên cứu", "研究/学习", "study/research", 0],
    ["vẫn", "仍然", "still", 0],
    ["học", "学/学习", "learn/study", 0],
    ["nhà máy", "工厂/植物", "factory/plant", 0],
    ["bìa", "封面/覆盖", "cover", 0],
    ["thực phẩm", "食物", "food", 0],
    ["ánh nắng mặt trời", "阳光", "sunshine", 0],
    ["bốn", "四", "four", 0],
    ["giữa", "之间/中间", "between/middle", 0],
    ["nhà nước", "国家/政府", "state/government", 0],
    ["giữ", "保持/留/抓住", "keep/hold", 0],
    ["mắt", "眼睛", "eye", 0],
    ["không bao giờ", "绝不/从不", "never", 0],
    ["cuối cùng", "最后/最终", "last/final", 0],
    ["cho phép", "允许/让", "allow/let", 0],
    ["nghĩ", "想/思考/想法", "think/thought", 0],
    ["thành phố", "城市", "city", 0],
    ["cây", "树", "tree", 0],
    ["qua", "经过/过/通过", "pass/via/cross", 0],
    ["trang trại", "农场", "farm", 0],
    ["cứng", "硬/努力/难", "hard", 0],
    ["bắt đầu", "开始", "start/begin/began", 0],
    ["might", "可能/也许", "might", 0],
    ["câu chuyện", "故事", "story", 0],
    ["cưa", "锯", "saw", 0],
    ["đến nay", "至今/到目前为止", "so far/up to now", 0],
    ["biển", "海", "sea", 0],
    ["vẽ", "画", "draw", 0],
    ["còn lại", "剩余/剩下/左边", "remaining/left", 0],
    ["cuối", "末尾/最后/晚", "end/last/late", 0],
    ["chạy", "跑", "run", 0],
    ["không", "不/没有/不是", "no/not/don't", 0],
    ["trong khi", "在...期间/虽然/尽管", "while/during", 0],
    ["báo chí", "报纸/新闻界", "press/journalism", 0],
    ["gần", "近/靠近/关闭", "near/close", 0],
    ["đêm", "夜晚", "night", 0],
    ["thực", "真实/实在", "real/true", 0],
    ["cuộc sống", "生活/生命", "life", 0],
    ["số", "数字/数量/号码/很少", "number/few", 0],
    ["phía bắc", "北方", "north", 0],
    ["cuốn sách", "书", "book", 0],
    ["thực hiện", "执行/履行/携带", "perform/carry", 0],
    ["mất", "丢/丢失/花费/采取", "lost/took", 0],
    ["khoa học", "科学", "science", 0],
    ["ăn", "吃", "eat", 0],
    ["phòng", "房间/预防", "room/prevent", 0],
    ["người bạn", "朋友", "friend", 0],
    ["ý tưởng", "主意/想法", "idea", 0],
    ["cá", "鱼", "fish", 0],
    ["núi", "山", "mountain", 0],
    ["ngăn chặn", "阻止/防止/停止", "stop/prevent", 0],
    ["một lần", "一次/曾经", "once", 0],
    ["cơ sở", "基础/根据", "base/foundation", 0],
    ["nghe", "听/听到", "hear/listen/heard", 0],
    ["ngựa", "马", "horse", 0],
    ["cắt", "切/剪", "cut", 0],
    ["chắc chắn", "肯定/当然", "sure/certain", 0],
    ["xem", "看/观察/手表", "see/watch", 0],
    ["màu", "颜色", "color", 0],
    ["khuôn mặt", "脸", "face", 0],
    ["gỗ", "木头/木材", "wood", 0],
    ["chính", "主要/正确/正", "main/chief/correct", 0],
    ["mở", "开/打开", "open", 0],
    ["dường như", "似乎", "seems", 0],
    ["cùng", "同/一起", "together/same", 0],
    ["tiếp theo", "下一个/接着", "next", 0],
    ["trắng", "白/白色", "white", 0],
    ["trẻ em", "孩子们", "children", 0],
    ["có", "有/得到", "have/has/got", 0],
    ["đi bộ", "走路/步行", "walk", 0],
    ["Ví dụ", "例子/例如", "example", 0],
    ["giảm bớt", "减轻/减少/缓解", "ease/decrease", 0],
    ["giấy", "纸", "paper", 0],
    ["nhóm", "组/群/团体", "group", 0],
    ["luôn luôn", "总是/老是", "always", 0],
    ["nhạc", "乐/音乐", "music", 0],
    ["những", "这些/那些", "these/those", 0],
    ["cả hai", "两者/都", "both", 0],
    ["đánh dấu", "标记/打钩", "mark/tick", 0],
    ["thường", "常/经常", "often", 0],
    ["thư", "信/字母", "letter", 0],
    ["cho đến khi", "直到", "until", 0],
    ["dặm", "英里", "mile", 0],
    ["sông", "河/江", "river", 0],
    ["xe", "车", "car/vehicle", 0],
    ["chân", "脚/腿", "foot/feet/leg", 0],
    ["chăm sóc", "照顾/关心", "care/take care of", 0],
    ["thứ hai", "第二/星期一", "second/Monday", 0],
    ["đủ", "够/足够", "enough", 0],
    ["đồng bằng", "平原", "plain", 0],
    ["cô gái", "女孩", "girl", 0],
    ["thông thường", "通常/平常", "usual/normally", 0],
    ["trẻ", "年轻/幼", "young", 0],
    ["sẵn sàng", "准备就绪", "ready", 0],
    ["trên đây", "以上/多于", "above", 0],
    ["bao giờ", "曾经/何时", "ever", 0],
    ["màu đỏ", "红/红色", "red", 0],
    ["danh sách", "列表/名单", "list", 0],
    ["mặc dù", "虽然/尽管", "though", 0],
    ["cảm thấy", "感觉/觉得", "feel", 0],
    ["nói chuyện", "谈话/聊天", "talk", 0],
    ["chim", "鸟", "bird", 0],
    ["sớm", "早/快/很快", "soon/early", 0],
    ["cơ thể", "身体", "body", 0],
    ["con chó", "狗", "dog", 0],
    ["gia đình", "家庭/家", "family", 0],
    ["trực tiếp", "直接", "direct", 0],
    ["đặt ra", "提出/摆出/姿势/出发", "pose/set out", 0],
    ["lại", "再/又/回来/再次", "again/back", 0],
    ["bài hát", "歌/歌曲", "song", 0],
    ["đo lường", "测量/衡量/措施", "measure/measurement", 0],
    ["cửa", "门", "door", 0],
    ["sản phẩm", "产品", "product", 0],
    ["đen", "黑/黑色", "black", 0],
    ["ngắn", "短", "short", 0],
    ["chữ số", "数字", "numeral/digits", 0],
    ["lớp", "班级/课/层", "class/layer", 0],
    ["gió", "风", "wind", 0],
    ["câu hỏi", "问题", "question", 0],
    ["xảy ra", "发生", "happen", 0],
    ["hoàn thành", "完成/完全的", "complete/done", 0],
    ["tàu", "船/舰/火车", "ship/train", 0],
    ["kh vực", "区域", "area", 0],
    ["một nửa", "一半", "half", 0],
    ["đá", "石/石头/冰/岩石", "stone/rock/ice", 0],
    ["để", "为了/让/让", "to/in order to/let", 0],
    ["lửa", "火", "fire", 0],
    ["nam", "南/男性/男", "south/male", 0],
    ["vấn đề", "问题/事务", "problem/issue", 0],
    ["mảnh", "片/块", "piece", 0],
    ["nói", "说/告诉", "say/speak/told", 0],
    ["biết", "知道", "know/knew", 0],
    ["vượt qua", "通过/克服/经过", "pass/overcome", 0],
    ["từ", "从/自从/词", "from/since/word", 0],
    ["đầu", "头/首/顶部/早期", "head/top/early", 0],
    ["toàn bộ", "全部/整个", "whole", 0],
    ["vua", "国王", "king", 0],
    ["đường phố", "街道", "street", 0],
    ["inch", "英寸", "inch", 0],
    ["nhân", "乘/倍增/核/人", "multiply/core", 0],
    ["không có gì", "没什么", "nothing", 0],
    ["Tất nhiên", "当然", "Of course", 0],
    ["ở lại", "停留/留在", "stay", 0],
    ["bánh xe", "车轮/轮子", "wheel", 0],
    ["đầy đủ", "充分/满的", "full", 0],
    ["lực", "力/力量", "force", 0],
    ["màu xanh", "蓝色的/绿色的", "blue/green", 0],
    ["đối tượng", "对象/目的/物体", "object", 0],
    ["quyết định", "决定", "decide/decision", 0],
    ["bề mặt", "表面", "surface", 0],
    ["sâu", "深", "deep", 0],
    ["mặt trăng", "月亮", "moon", 0],
    ["đảo", "岛/岛屿", "island", 0],
    ["hệ thống", "系统", "system", 0],
    ["bận rộn", "忙碌", "busy", 0],
    ["kiểm tra", "检查/测试/查看", "check/test", 0],
    ["ghi", "记录/记下/写下", "record/take note", 0],
    ["thuyền", "船/小船", "boat", 0],
    ["phổ biến", "普遍/常见/流行", "common/popular", 0],
    ["vàng", "黄/黄色/金子", "yellow/gold", 0],
    ["có thể", "可能/可以", "possible/can", 0],
    ["máy bay", "飞机", "plane", 0],
    ["thay", "换/代替", "replace/stead", 0],
    ["khô", "干/干燥", "dry", 0],
    ["tự hỏi", "想知道/纳闷", "wonder", 0],
    ["cười", "笑", "laugh", 0],
    ["ngàn", "千", "thousand", 0],
    ["ran", "跑", "ran", 0],
    ["trò chơi", "游戏", "game", 0],
    ["hình dạng", "形状", "shape", 0],
    ["đánh đồng", "等同/使相等", "equate", 0],
    ["nóng", "热", "hot", 0],
    ["bỏ lỡ", "错过/想念", "miss", 0],
    ["mang", "带/携带/带来", "carry/bring/brought", 0],
    ["nhiệt", "热/温度", "heat", 0],
    ["tuyết", "雪", "snow", 0],
    ["lốp xe", "轮胎", "tire", 0],
    ["mang lại", "带来", "bring", 0],
    ["vâng", "是的/好", "yes", 0],
    ["xa", "远/遥远", "far/distant", 0],
    ["điền", "填写/充满", "fill", 0],
    ["đông", "东/东方/冬天/拥挤", "east/winter/crowded", 0],
    ["sơn", "漆/画/油漆", "paint", 0],
    ["ngôn ngữ", "语言", "language", 0],
    ["trong", "在...里/之中/清晰", "in/among/clear", 0],
    ["đơn vị", "单位/单元", "unit", 0],
    ["điện", "电/力量", "electricity/power", 0],
    ["thị trấn", "城镇/镇", "town", 0],
    ["tốt", "好/美好", "good/fine", 0],
    ["nhất định", "一定/确定/肯定", "certain", 0],
    ["bay", "飞/飞行", "fly", 0],
    ["giảm", "减少/下降/落下", "reduce/fall", 0],
    ["dẫn", "引导/带领", "lead/guide", 0],
    ["kêu", "叫/哭/喊", "call/cry", 0],
    ["tối", "暗/黑暗/晚上", "dark/evening", 0],
    ["máy", "机器", "machine", 0],
    ["đợi", "等/等待", "wait", 0],
    ["kế hoạch", "计划", "plan", 0],
    ["con số", "数字/图表/人物", "figure/number", 0],
    ["sao", "星/星星", "star", 0],
    ["hộp", "盒子/箱子", "box", 0],
    ["danh từ", "名词", "noun", 0],
    ["lĩnh vực", "领域/场地", "field", 0],
    ["phần còn lại", "剩余部分/休息", "the rest/remainder", 0],
    ["chính xác", "准确/正确/确切", "exact/correct", 0],
    ["thể", "能/可以/体", "able/can", 0],
    ["bảng", "表/表格/板/磅", "table/board/pound", 0],
    ["Xong", "做完/搞定", "done", 0],
    ["vẻ đẹp", "美丽/美", "beauty", 0],
    ["ổ đĩa", "驱动/驾驶", "drive", 0],
    ["chứa", "包含/容纳", "contain", 0],
    ["dạy", "教/教学", "teach", 0],
    ["tuần", "周/星期", "week", 0],
    ["thức", "醒/方式/识/最终", "awake/final", 0],
    ["đã", "已经/曾经/满足", "already/gave", 0],
    ["màu xanh lá cây", "绿/绿色", "green", 0],
    ["oh", "哦", "oh", 0],
    ["nhanh chóng", "快/快速", "quick/fast", 0],
    ["đại dương", "海洋", "ocean", 0],
    ["ấm áp", "温暖", "warm", 0],
    ["miễn phí", "免费/自由", "free", 0],
    ["phút", "分钟", "minute", 0],
    ["mạnh mẽ", "强壮/强大", "strong", 0],
    ["đặc biệt", "特别/特殊", "special", 0],
    ["tâm", "心/思想/头脑", "mind/heart", 0],
    ["sau", "在...后/以后", "after/behind", 0],
    ["đuôi", "尾巴", "tail", 0],
    ["sản xuất", "生产/制造", "produce/manufacture", 0],
    ["thực tế", "事实/现实/实际", "fact/reality", 0],
    ["không gian", "空间/太空", "space", 0],
    ["tốt nhất", "最好", "best", 0],
    ["giờ", "小时/时间", "hour/time", 0],
    ["tốt hơn", "更好", "better", 0],
    ["đúng", "对/正确/真实", "true/correct", 0],
    ["trăm", "百", "hundred", 0],
    ["nhớ", "记/记住/想念", "remember/miss", 0],
    ["bước", "步/步骤", "step", 0],
    ["giư", "保持/持有", "hold", 0],
    ["tây", "西/西方", "west", 0],
    ["mặt đất", "地面", "ground", 0],
    ["quan tâm", "关心/兴趣", "care/interest", 0],
    ["đạt", "达到/抵达/获得", "reach/obtain", 0],
    ["động từ", "动词", "verb", 0],
    ["hát", "唱/唱歌", "sing", 0],
    ["lắng nghe", "听/倾听", "listen", 0],
    ["sáu", "六", "six", 0],
    ["du lịch", "旅行/旅游", "travel", 0],
    ["buổi sáng", "早上/早晨", "morning", 0],
    ["mười", "十", "ten", 0],
    ["đơn giản", "简单", "simple", 0],
    ["nguyên âm", "元音", "vowel", 0],
    ["hướng", "朝向/方向", "toward/direction", 0],
    ["chiến tranh", "战争", "war", 0],
    ["chống lại", "反对/对抗", "against", 0],
    ["mô hình", "模型/模式/图案", "model/pattern", 0],
    ["chậm", "慢/缓慢", "slow", 0],
    ["trung tâm", "中心", "center", 0],
    ["tình yêu", "爱/恋爱", "love", 0],
    ["tiền", "钱", "money", 0],
    ["phục vụ", "服务", "serve", 0],
    ["xuất hiện", "出现", "appear", 0],
    ["đường", "路/街道/糖", "road/street/way", 0],
    ["Bản đồ", "地图", "map", 0],
    ["mưa", "雨", "rain", 0],
    ["quy tắc", "规则", "rule", 0],
    ["phối", "配合/协调/分配", "coordinate/govern", 0],
    ["kéo", "拉/拖", "pull/drag", 0],
    ["lạnh", "冷/寒冷", "cold", 0],
    ["thông báo", "通知/公告/注意", "notice/notification", 0],
    ["giọng nói", "声音/嗓音", "voice", 0]
]
basic: [
    ["năng lượng", "能量/能源/活力", "energy", 0],
    ["săn", "打猎/狩猎", "hunt", 0],
    ["có thể xảy ra", "可能发生/可能的", "probable", 0],
    ["giường", "床", "bed", 0],
    ["anh trai", "哥哥/兄弟", "brother", 0],
    ["trứng", "蛋/鸡蛋", "egg", 0],
    ["đi xe", "骑/乘车", "ride", 0],
    ["pin", "电池", "cell/battery", 0],
    ["tin", "相信/信任/消息", "believe/news", 0],
    ["có lẽ", "也许/或许", "perhaps/maybe", 0],
    ["chọn", "选择/挑选", "pick/choose/select", 0],
    ["đột ngột", "突然的/骤然", "sudden", 0],
    ["tính", "计算/数数/性质", "count/calculate/nature", 0],
    ["vuông", "正方形/平方", "square", 0],
    ["lý do", "原因/理由", "reason", 0],
    ["chiều dài", "长度", "length", 0],
    ["đại diện", "代表", "represent", 0],
    ["nghệ thuật", "艺术", "art", 0],
    ["Tiêu đề", "标题/题目/主题", "subject/title", 0],
    ["khu", "区域/地区", "region/area", 0],
    ["kích thước", "尺寸/大小", "size", 0],
    ["khác nhau", "不同/差异", "vary/differ/different", 0],
    ["giải quyết", "解决/处理/定居", "settle/solve", 0],
    ["nói", "说/说话/告诉", "speak/say/said/told/spoke", 0],
    ["trọng lượng", "重量", "weight", 0],
    ["chung", "共同的/一般的/总的", "general/common", 0],
    ["băng", "冰/胶带", "ice/tape", 0],
    ["vấn đề", "问题/事情/物质", "matter/problem/issue", 0],
    ["vòng tròn", "圆圈/环", "circle", 0],
    ["đôi", "双/对/一对", "pair/double", 0],
    ["bao gồm", "包括/包含", "include", 0],
    ["chia", "划分/分开/除", "divide", 0],
    ["âm tiết", "音节", "syllable", 0],
    ["cảm thấy", "感觉/觉得", "felt/feel", 0],
    ["lớn", "大的/大声的/盛大的", "large/big/grand/loud", 0],
    ["bóng", "球/影子", "ball/shadow", 0],
    ["nhưng", "但是/然而/但", "but/yet", 0],
    ["sóng", "波/浪", "wave", 0],
    ["rơi", "落下/跌落", "drop/fall/fell", 0],
    ["tim", "心/心脏", "heart", 0],
    ["là", "是/成为", "am/is/are/was/were/be", 0],
    ["hiện nay", "现在/当前/展示", "present/now/current", 0],
    ["nặng", "重的", "heavy", 0],
    ["khiêu vũ", "跳舞/舞蹈", "dance", 0],
    ["động cơ", "引擎/动机", "engine/motive", 0],
    ["vị trí", "位置/地点", "position/location", 0],
    ["cánh tay", "手臂", "arm", 0],
    ["rộng", "宽的/广阔的", "wide/broad", 0],
    ["buồm", "帆/航行", "sail", 0],
    ["tài liệu", "材料/资料/文档", "material/document", 0],
    ["phần", "部分/分数/章节", "part/fraction/section/segment", 0],
    ["rừng", "森林", "forest", 0],
    ["ngồi", "坐", "sit/sat", 0],
    ["cuộc đua", "比赛/种族", "race", 0],
    ["cửa sổ", "窗户", "window", 0],
    ["cửa hàng", "商店/店铺", "store/shop", 0],
    ["mùa hè", "夏天", "summer", 0],
    ["đào tạo", "培训/训练/锻炼", "train/exercise", 0],
    ["ngủ", "睡觉", "sleep", 0],
    ["chứng minh", "证明", "prove", 0],
    ["đơn độc", "孤独的/唯一的", "lone/single", 0],
    ["chân", "脚/腿", "leg/foot/feet", 0],
    ["tập thể dục", "锻炼/练习", "exercise", 0],
    ["tường", "墙", "wall", 0],
    ["bắt", "抓住/捕捉", "catch/caught", 0],
    ["mount", "山/登上", "mount", 0],
    ["muốn", "想要/希望", "want/wish", 0],
    ["bầu trời", "天空", "sky", 0],
    ["hội đồng quản trị", "董事会/木板", "board", 0],
    ["niềm vui", "快乐/喜悦", "joy/glad", 0],
    ["mùa đông", "冬天", "winter", 0],
    ["bằng văn bản", "书面的/以书写形式", "written", 0],
    ["hoang dã", "野生的/荒野", "wild", 0],
    ["cụ", "工具/乐器", "instrument/tool", 0],
    ["giữ", "保持/保留/抓住", "keep/kept/hold/held", 0],
    ["kính", "玻璃/镜子/眼镜", "glass", 0],
    ["cỏ", "草", "grass", 0],
    ["bò", "牛/爬行", "cow/crawl", 0],
    ["công việc", "工作/职业", "job/work", 0],
    ["cạnh", "边缘/侧面", "edge/side", 0],
    ["dấu hiệu", "标志/符号/手势", "sign", 0],
    ["lần", "次/回/访问", "visit/times", 0],
    ["qua", "经过/通过/过去", "past/through/cross/via", 0],
    ["mềm", "柔软的", "soft", 0],
    ["vui vẻ", "快乐/乐趣", "fun/happy", 0],
    ["sáng", "明亮的/早晨", "bright/morning", 0],
    ["khí", "气体/空气", "gas/air", 0],
    ["thời tiết", "天气", "weather", 0],
    ["tháng", "月/月份", "month", 0],
    ["triệu", "百万", "million", 0],
    ["chịu", "承受/熊", "bear", 0],
    ["kết thúc", "结束/完成", "finish/end", 0],
    ["hạnh phúc", "幸福/快乐", "happy", 0],
    ["hy vọng", "希望", "hope", 0],
    ["hoa", "花", "flower", 0],
    ["mặc", "穿/戴/衣服", "wear/clothe/dress", 0],
    ["lạ", "奇怪的/陌生的", "strange", 0],
    ["ra đi", "离开/去世/消失", "gone/leave", 0],
    ["thương mại", "贸易/商业", "trade/commercial", 0],
    ["giai điệu", "旋律/音调", "melody/tone", 0],
    ["chuyến đi", "旅行/行程", "trip/journey", 0],
    ["văn phòng", "办公室", "office", 0],
    ["nhận", "收到/接收", "receive/get", 0],
    ["hàng", "行/排/货物", "row/line/goods", 0],
    ["miệng", "嘴", "mouth", 0],
    ["chính xác", "精确/准确/确切", "exact/correct", 0],
    ["biểu tượng", "象征/符号/图标", "symbol", 0],
    ["chết", "死/死亡/死的", "die/death/dead", 0],
    ["nhất", "最/第一/至少", "most/first/least", 0],
    ["rắc rối", "麻烦/烦恼", "trouble", 0],
    ["hét lên", "喊叫/尖叫", "shout", 0],
    ["trừ", "除外/减去", "except/subtract", 0],
    ["đã viết", "写了(write过去式)", "wrote", 0],
    ["hạt giống", "种子", "seed", 0],
    ["tham gia", "参加/加入", "join", 0],
    ["đề nghị", "建议/提议", "suggest/offer", 0],
    ["sạch", "干净/清洁", "clean", 0],
    ["nghỉ", "休息/打破", "break/rest", 0],
    ["phụ nữ", "女人/女性/女士", "lady/women/woman", 0],
    ["sân", "院子/庭院/场地", "yard/pitch", 0],
    ["tăng", "上升/增加/增长", "rise/raise/grew/rose", 0],
    ["xấu", "坏的/差的", "bad", 0],
    ["đòn", "吹/打击", "blow", 0],
    ["dầu", "油", "oil", 0],
    ["máu", "血/血液", "blood", 0],
    ["chạm", "触碰/接触", "touch", 0],
    ["phần trăm", "百分比/分", "cent/percent", 0],
    ["trộn", "混合", "mix", 0],
    ["đội", "团队/队伍", "team", 0],
    ["dây", "绳索/电线/金属丝", "wire/rope/string", 0],
    ["chi phí", "费用/成本", "cost/charge", 0],
    ["thua", "输/丢失", "lost/lose", 0],
    ["nâu", "棕色", "brown", 0],
    ["vườn", "花园", "garden", 0],
    ["như nhau", "相同/相等/平等", "equal/same", 0],
    ["gửi", "发送/寄", "send/sent", 0],
    ["giảm", "减少/下降/降低", "reduce/decrease", 0],
    ["phù hợp với", "适合/匹配/套装", "fit/suit/match", 0],
    ["chảy", "流动", "flow", 0],
    ["công bằng", "公平/公正", "fair", 0],
    ["ngân hàng", "银行/岸", "bank", 0],
    ["thu thập", "收集/聚集", "collect/gather", 0],
    ["lưu", "保存/节省/救", "save", 0],
    ["kiểm soát", "控制", "control", 0],
    ["số thập phân", "小数", "decimal", 0],
    ["tai", "耳朵", "ear", 0],
    ["khác", "其他/别的", "else/other", 0],
    ["khá", "相当/很/漂亮", "quite/pretty", 0],
    ["đã phá vỡ", "打破了/坏了", "broke", 0],
    ["khi", "当...时/案件/情况", "when/case", 0],
    ["trung", "中间/中央", "middle/center", 0],
    ["giết", "杀/杀害", "kill", 0],
    ["con trai", "儿子/男孩", "son/boy", 0],
    ["hồ", "湖/湖泊", "lake", 0],
    ["thời điểm", "时刻/片刻", "moment", 0],
    ["quy mô", "规模/比例/秤", "scale", 0],
    ["mùa xuân", "春天/泉/弹簧", "spring", 0],
    ["quan sát", "观察", "observe", 0],
    ["con", "孩子/儿子/女儿", "child/son", 0],
    ["thẳng", "直的/直接", "straight", 0],
    ["phụ âm", "辅音", "consonant", 0],
    ["quốc gia", "国家/民族", "nation/country", 0],
    ["từ điển", "字典/词典", "dictionary", 0],
    ["sưa", "牛奶", "milk", 0],
    ["tốc độ", "速度", "speed", 0],
    ["phương pháp", "方法", "method", 0],
    ["cơ quan", "器官/机构", "organ/agency", 0],
    ["trả", "支付/还", "pay/reply", 0],
    ["tuổi", "年龄/岁", "age", 0],
    ["váy", "裙子/礼服", "dress", 0],
    ["điện toán đám mây", "云计算/云", "cloud", 0],
    ["bất ngờ", "意外/惊喜/突然", "surprise", 0],
    ["yên tĩnh", "安静/宁静", "quiet", 0],
    ["đá", "石头/冰/岩石", "stone/ice/rock/kick", 0],
    ["nhỏ", "小的/微小的", "small/little/tiny/baby", 0],
    ["lên cao", "爬/上升", "climb/rise", 0],
    ["mát mẻ", "凉爽/酷", "cool", 0],
    ["thiết kế", "设计", "design", 0],
    ["người nghèo", "穷人/贫穷的", "poor", 0],
    ["rất nhiều", "很多", "lot/many/much", 0],
    ["thí nghiệm", "实验", "experiment", 0],
    ["dưới", "在...下面/底部", "under/below/bottom", 0],
    ["chính", "主要/钥匙/关键", "main/key/major/chief", 0],
    ["sắt", "铁", "iron", 0],
    ["đơn", "单/简单/单位", "single/simple/unit", 0],
    ["thanh", "棒/条/酒吧", "stick/bar", 0],
    ["phẳng", "平坦的/平的", "flat", 0],
    ["hai mươi", "二十", "twenty", 0],
    ["da", "皮肤/皮", "skin", 0],
    ["nụ cười", "微笑", "smile", 0],
    ["nếp", "折痕/褶皱", "crease", 0],
    ["lỗ", "洞/孔", "hole", 0],
    ["nhảy", "跳/跳跃", "jump", 0],
    ["bé", "婴儿/小的", "baby/small", 0],
    ["tám", "八", "eight", 0],
    ["làng", "村庄", "village", 0],
    ["đáp ứng", "满足/遇见/答复", "meet/reply", 0],
    ["gốc", "根/起源/根本", "root", 0],
    ["mua", "买/购买", "buy/bought", 0],
    ["nâng cao", "提高/提升", "raise/improve", 0],
    ["kim loại", "金属", "metal", 0],
    ["liệu", "是否/材料/材料", "whether/material", 0],
    ["đẩy", "推", "push", 0],
    ["bảy", "七", "seven", 0],
    ["đoạn", "段落/片段", "paragraph/segment", 0],
    ["thứ ba", "第三/周二", "third/Tuesday", 0],
    ["có trách nhiệm", "应当/负责", "shall", 0],
    ["được tổ chức", "举行/举办/握住", "held", 0],
    ["lông", "毛/头发", "hair/fur", 0],
    ["mô tả", "描述/形容", "describe", 0],
    ["nấu ăn", "煮/烹饪/厨师", "cook", 0],
    ["sàn", "地板/地面", "floor", 0],
    ["hoặc", "或者", "or/either", 0],
    ["kết quả", "结果", "result", 0],
    ["ghi", "记录/记下/烧", "record/take note/burn", 0],
    ["đồi", "小山/丘陵", "hill", 0],
    ["an toàn", "安全", "safe", 0],
    ["mèo", "猫", "cat", 0],
    ["thế kỷ", "世纪", "century", 0],
    ["xem xét", "考虑/审议", "consider", 0],
    ["loại", "种类/类型", "kind/type", 0],
    ["pháp luật", "法律", "law", 0],
    ["bit", "一点/位/少量", "bit", 0],
    ["bờ biển", "海岸/海滨", "coast/shore", 0],
    ["bản sao", "副本/复制", "copy", 0],
    ["cụm từ", "短语/词组", "phrase", 0],
    ["im lặng", "沉默/安静", "silent/quiet", 0],
    ["cao", "高/高的", "high/tall", 0],
    ["cát", "沙/沙子", "sand", 0],
    ["đất", "土地/土壤/地球", "land/soil/earth", 0],
    ["cuộn", "卷/滚动", "roll", 0],
    ["nhiệt độ", "温度", "temperature", 0],
    ["ngón tay", "手指", "finger", 0],
    ["ngành công nghiệp", "工业/行业", "industry", 0],
    ["giá trị", "价值", "value", 0],
    ["cuộc chiến", "战斗/斗争", "fight/war", 0],
    ["lời nói dối", "谎言/说谎/躺", "lie", 0],
    ["đánh bại", "击败/打", "beat/hit", 0],
    ["kích thích", "刺激/激发/兴奋", "excite", 0],
    ["tự nhiên", "自然/天然", "natural/nature", 0],
    ["xem", "看/看法/视图", "look/watch/view", 0],
    ["ý nghĩa", "意义/意思/感官", "sense/mean/meaning", 0],
    ["vốn", "资本/首都/原本", "capital/original", 0],
    ["sẽ không", "不会/将不", "won’t", 0],
    ["ghế", "椅子/座位", "chair/seat", 0],
    ["nguy hiểm", "危险", "danger", 0],
    ["trái cây", "水果", "fruit", 0],
    ["giàu", "富有/丰盛", "rich", 0],
    ["dày", "厚的/浓的", "thick", 0],
    ["người lính", "士兵", "soldier", 0],
    ["quá trình", "过程/进程", "process", 0],
    ["hoạt động", "操作/运行/活动", "operate/activity", 0],
    ["thực hành", "实践/练习", "practice", 0],
    ["riêng biệt", "分开/独立/个别", "separate/particular", 0],
    ["khó khăn", "困难/难", "difficult/hard", 0],
    ["bác sĩ", "医生", "doctor", 0],
    ["xin vui lòng", "请", "please", 0],
    ["bảo vệ", "保护", "protect", 0],
    ["trưa", "中午", "noon", 0],
    ["cây trồng", "庄稼/作物", "crop", 0],
    ["hiện đại", "现代", "modern", 0],
    ["yếu tố", "元素/要素", "element", 0],
    ["nhấn", "按/压/打击", "press/hit", 0],
    ["sinh viên", "学生/大学生", "student", 0],
    ["góc", "角落/角", "corner", 0],
    ["bên", "旁边/方面/党/派对", "side/party", 0],
    ["cung cấp", "提供/供应", "supply/provide/offer", 0],
    ["có", "有/拥有/得到", "have/has/had/got/take/whose", 0],
    ["xác định vị trí", "定位/查找", "locate", 0],
    ["vòng", "戒指/圆/环", "ring/round", 0],
    ["nhân vật", "角色/字符/性格", "character", 0],
    ["côn trùng", "昆虫", "insect", 0],
    ["thời gian", "时间/时期", "time/period", 0],
    ["chỉ ra", "指出/表明", "indicate", 0],
    ["radio", "无线电/收音机", "radio", 0],
    ["nguyên tử", "原子", "atom", 0],
    ["con người", "人类/人", "human/person/people", 0],
    ["lịch sử", "历史", "history", 0],
    ["hiệu lực", "效果/影响/效力", "effect", 0],
    ["điện", "电", "electric/power/electricity", 0],
    ["mong đợi", "期待/期望", "expect", 0],
    ["xương", "骨头", "bone", 0],
    ["đường sắt", "铁路/轨道", "rail", 0],
    ["tưởng tượng", "想象", "imagine", 0],
    ["đồng ý", "同意", "agree", 0],
    ["do đó", "因此/所以", "thus/so", 0],
    ["nhẹ nhàng", "温柔/轻柔", "gentle", 0],
    ["người phụ nữ", "女人", "woman", 0],
    ["đội trưởng", "队长/船长", "captain", 0],
    ["đoán", "猜测", "guess", 0],
    ["cần thiết", "必要/必须", "necessary/must", 0],
    ["sắc nét", "锋利/尖锐", "sharp", 0],
    ["cánh", "翅膀/翼", "wing", 0],
    ["tạo", "创造/制作", "create/make", 0],
    ["hàng xóm", "邻居", "neighbor", 0],
    ["rửa", "洗", "wash", 0],
    ["bat", "蝙蝠/球棒", "bat", 0],
    ["thay", "代替/而不是", "instead/rather", 0],
    ["đám đông", "人群", "crowd", 0],
    ["ngô", "玉米", "corn", 0],
    ["so sánh", "比较", "compare", 0],
    ["bài thơ", "诗", "poem", 0],
    ["chuông", "钟/铃", "bell", 0],
    ["phụ thuộc", "依赖/取决于", "depend", 0],
    ["thịt", "肉", "meat", 0],
    ["chà", "擦/摩擦", "rub", 0],
    ["ống", "管子/导管", "tube", 0],
    ["nổi tiếng", "著名/有名", "famous", 0],
    ["đồng đô la", "美元", "dollar", 0],
    ["sông", "河/溪/江", "river/stream", 0],
    ["sợ hãi", "恐惧/害怕", "fear/afraid", 0],
    ["cảnh", "风景/景象/视力", "sight/view/scene", 0],
    ["mỏng", "薄/瘦", "thin", 0],
    ["tam giác", "三角形", "triangle", 0],
    ["hành tinh", "行星", "planet", 0],
    ["nhanh", "快/迅速/匆忙", "fast/quick/hurry", 0],
    ["thu thuộc địa", "殖民地", "colony", 0],
    ["đồng hồ", "钟表/手表", "clock/watch", 0],
    ["tôi", "我/我的/矿", "I/me/my/mine", 0],
    ["cà vạt", "领带/系", "tie", 0],
    ["nhập", "进入/输入", "enter", 0],
    ["tươi", "新鲜", "fresh", 0],
    ["tìm kiếm", "搜索/寻找", "search/find", 0],
    ["vàng", "金子/黄色", "gold/yellow", 0],
    ["súng", "枪", "gun", 0],
    ["cho phép", "允许/让", "allow/let", 0],
    ["in", "打印/印刷", "print", 0],
    ["tại chỗ", "现场/点/斑点", "spot", 0],
    ["sa mạc", "沙漠", "desert", 0],
    ["thang máy", "电梯/举起", "lift", 0],
    ["đến", "来/到达", "arrive/come", 0],
    ["chủ", "主人/掌握", "master", 0],
    ["theo dõi", "追踪/轨道", "track", 0],
    ["mẹ", "母亲/家长", "mother/parent", 0],
    ["bờ", "岸/边缘", "shore/edge", 0],
    ["phân chia", "划分/除法", "division/divide", 0],
    ["tờ", "张/页/床单", "sheet/page", 0],
    ["chất", "物质/品质", "substance/quality", 0],
    ["ủng hộ", "支持/赞成/青睐", "favor/support", 0],
    ["kết nối", "连接", "connect", 0],
    ["bài", "邮寄/职位/帖子/课", "post/lesson", 0],
    ["chi tiêu", "花费/消费", "spend", 0],
    ["hợp âm", "和弦", "chord", 0],
    ["chất béo", "脂肪/肥胖", "fat", 0],
    ["ban đầu", "最初/原始", "original", 0],
    ["chia sẻ", "分享", "share", 0],
    ["trạm", "站/车站", "station", 0],
    ["cha", "父亲/爸爸", "father/dad", 0],
    ["bánh mì", "面包", "bread", 0],
    ["thích hợp", "合适/恰当", "proper/fit", 0],
    ["phục vụ", "服务/提供", "serve/offer", 0],
    ["phân khúc", "段/细分", "segment", 0],
    ["nô lệ", "奴隶", "slave", 0],
    ["vịt", "鸭子", "duck", 0],
    ["ngay lập tức", "立即/马上", "instant/immediately", 0],
    ["thị trường", "市场", "market", 0],
    ["mức độ", "程度/等级", "degree/level", 0],
    ["cư", "居住/填充", "populate", 0],
    ["gà", "鸡/小鸡", "chick/chicken", 0],
    ["thân yêu", "亲爱的", "dear", 0],
    ["kẻ thù", "敌人", "enemy", 0],
    ["ly", "杯子/喝", "glass/drink", 0],
    ["xảy ra", "发生/出现", "happen/occur", 0],
    ["hỗ trợ", "支持", "support", 0],
    ["bài phát biểu", "演讲/话语", "speech", 0],
    ["thiên nhiên", "自然/本性", "nature", 0],
    ["phạm vi", "范围", "range", 0],
    ["hơi nước", "蒸汽", "steam", 0],
    ["chuyển động", "运动/移动", "motion/move", 0],
    ["con đường", "道路/路径", "path/way/road", 0],
    ["chất lỏng", "液体", "liquid", 0],
    ["đăng nhập", "登录/日志", "log", 0],
    ["có nghĩa là", "意思是", "mean/meant", 0],
    ["thương", "商数/爱/伤", "quotient/love", 0],
    ["răng", "牙齿", "teeth/tooth", 0],
    ["vỏ", "壳/皮/吠", "shell/bark", 0],
    ["cổ", "脖子/古老", "neck/ancient", 0],
    ["oxy", "氧气", "oxygen", 0],
    ["đường", "糖/道路/街道", "sugar/road/street/way", 0],
    ["kỹ năng", "技能/技巧", "skill", 0],
    ["mùa", "季节", "season", 0],
    ["giải pháp", "解决方案/溶液", "solution", 0],
    ["nam châm", "磁铁", "magnet", 0],
    ["bạc", "银", "silver", 0],
    ["cảm ơn", "谢谢", "thank", 0],
    ["chi nhánh", "分支/分店", "branch", 0],
    ["trận đấu", "比赛/匹配", "match", 0],
    ["hậu tố", "后缀", "suffix", 0],
    ["đặc biệt là", "尤其是/特别", "especially", 0],
    ["sung", "无花果/如图", "fig", 0],
    ["to", "大的/巨大", "huge/big", 0],
    ["em gái", "妹妹/姐姐", "sister", 0],
    ["thép", "钢/钢铁", "steel", 0],
    ["thảo luận", "讨论", "discuss", 0],
    ["về phía trước", "向前", "forward", 0],
    ["tương tự", "相似/类似", "similar", 0],
    ["hướng dẫn", "指导/指南", "guide", 0],
    ["kinh nghiệm", "经验/历练", "experience", 0],
    ["điểm", "分数/点/得分", "point/score", 0],
    ["táo", "苹果", "apple", 0],
    ["dẫn", "引导/带领", "lead/led/guide", 0],
    ["áo", "衣服/外套", "coat/shirt", 0],
    ["khối lượng", "体积/质量/大量", "mass/volume", 0],
    ["thẻ", "卡片", "card", 0],
    ["ban nhạc", "乐队/带子", "band", 0],
    ["trượt", "滑/滑动", "slip/slide", 0],
    ["giành chiến thắng", "赢/获胜", "win", 0],
    ["mơ", "梦/梦想", "dream", 0],
    ["buổi tối", "晚上/傍晚", "evening", 0],
    ["điều kiện", "条件/状况", "condition", 0],
    ["thức ăn chăn nuôi", "饲料/喂养", "feed", 0],
    ["tổng số", "总数/全部", "total", 0],
    ["cơ bản", "基础/基本", "basic", 0],
    ["mùi", "味道/闻", "smell", 0],
    ["thung lũng", "山谷", "valley", 0],
    ["cũng không", "也不", "nor", 0],
    ["tiếp tục", "继续", "continue", 0],
    ["khối", "块/阻碍/大楼", "block", 0],
    ["biểu đồ", "图表", "chart", 0],
    ["mũ", "帽子", "hat", 0],
    ["bán", "卖/销售", "sell", 0],
    ["thành công", "成功", "success", 0],
    ["công ty", "公司", "company", 0],
    ["sự kiện", "事件/活动", "event", 0],
    ["riêng", "私人的/各自的/自己的", "private/own/particular", 0],
    ["thỏa thuận", "协议/交易", "deal/agree", 0],
    ["bơi", "游泳", "swim", 0],
    ["hạn", "期限/学期/术语", "term", 0],
    ["ngược lại", "相反", "opposite", 0],
    ["vợ", "妻子", "wife", 0],
    ["giày", "鞋子", "shoe", 0],
    ["vai", "肩膀", "shoulder", 0],
    ["lây lan", "传播/展开", "spread", 0],
    ["sắp xếp", "安排/整理", "arrange", 0],
    ["trại", "营地/营", "camp", 0],
    ["phát minh", "发明", "invent", 0],
    ["bông", "棉花/花", "cotton", 0],
    ["Sinh", "出生", "born", 0],
    ["xác định", "确定/决定", "determine", 0],
    ["lít", "升", "liter/quart", 0],
    ["chín", "九/成熟", "nine/ripe", 0],
    ["xe tải", "卡车", "truck", 0],
    ["tiếng ồn", "噪音", "noise", 0],
    ["mức", "水平/等级", "level/rate", 0],
    ["cơ hội", "机会", "chance", 0],
    ["căng ra", "拉伸/伸展", "stretch", 0],
    ["ném", "扔/投", "throw", 0],
    ["tỏa sáng", "闪耀/照耀", "shine", 0],
    ["tài sản", "财产/资产/属性", "property", 0],
    ["cột", "柱子/栏", "column", 0],
    ["phân tử", "分子", "molecule", 0],
    ["sai", "错误", "wrong", 0],
    ["màu xám", "灰色", "gray", 0],
    ["lặp lại", "重复", "repeat", 0],
    ["yêu cầu", "要求/需要", "require", 0],
    ["chuẩn bị", "准备", "prepare", 0],
    ["muối", "盐", "salt", 0],
    ["mui", "鼻子/盖子", "nose", 0],
    ["số nhiều", "复数", "plural", 0],
    ["tức giận", "愤怒/生气", "anger/angry", 0],
    ["xin", "请求/宣称/问", "ask/claim/please", 0],
    ["lục", "大陆/绿色/记录", "continent/green/record", 0]
    ["kiểm tra", "检查/核对", "check", 0],
    ["trò chơi", "游戏", "game", 0],
    ["hình dạng", "形状", "shape", 0],
    ["đánh đồng", "等同/混为一谈", "equate", 0],
    ["nóng", "热", "hot", 0],
    ["bỏ lỡ", "错过", "miss", 0],
    ["mang", "携带/带来", "brought", 0],
    ["nhiệt", "热/热量", "heat", 0],
    ["tuyết", "雪", "snow", 0],
    ["lốp xe", "轮胎", "tire", 0],
    ["mang lại", "带来", "bring", 0],
    ["vâng", "是/答应", "yes", 0],
    ["xa", "远", "distant", 0],
    ["điền", "填写/填充", "fill", 0],
    ["đông", "东/拥挤", "east", 0],
    ["sơn", "油漆/绘画", "paint", 0],
    ["ngôn ngữ", "语言", "language", 0],
    ["trong", "在...之内/清晰", "among", 0],
    ["đơn vị", "单位", "unit", 0],
    ["điện", "电", "power", 0],
    ["thị trấn", "市镇", "town", 0],
    ["tốt", "好", "fine", 0],
    ["nhất định", "肯定/一定", "certain", 0],
    ["bay", "飞", "fly", 0],
    ["giảm", "减少/下降", "fall", 0],
    ["dẫn", "引导/带领", "lead", 0],
    ["kêu", "叫/喊", "cry", 0],
    ["tối", "黑暗/晚上", "dark", 0],
    ["máy", "机器", "machine", 0],
    ["ghi", "记录/登记", "note", 0],
    ["đợi", "等待", "wait", 0],
    ["kế hoạch", "计划", "plan", 0],
    ["con số", "数字", "figure", 0],
    ["sao", "星星", "star", 0],
    ["hộp", "盒子", "box", 0],
    ["danh từ", "名词", "noun", 0],
    ["lĩnh vực", "领域", "field", 0],
    ["phần còn lại", "剩余部分", "rest", 0],
    ["chính xác", "准确/精确", "correct", 0],
    ["thể", "能够/身体", "able", 0],
    ["bảng", "表格/桌子", "pound", 0],
    ["Xong", "完成", "done", 0],
    ["vẻ đẹp", "美丽", "beauty", 0],
    ["ổ đĩa", "驱动器", "drive", 0],
    ["đứng", "站立", "stood", 0],
    ["chứa", "包含/容纳", "contain", 0],
    ["trước", "之前/前面", "front", 0],
    ["dạy", "教", "teach", 0],
    ["tuần", "星期/周", "week", 0],
    ["thức", "醒悟/最终", "final", 0],
    ["đã", "已经", "gave", 0],
    ["màu xanh lá cây", "绿色", "green", 0],
    ["oh", "哦", "oh", 0],
    ["nhanh chóng", "快速", "quick", 0],
    ["phát triển", "发展", "develop", 0],
    ["đại dương", "海洋", "ocean", 0],
    ["ấm áp", "温暖", "warm", 0],
    ["miễn phí", "免费/自由", "free", 0],
    ["phút", "分钟", "minute", 0],
    ["mạnh mẽ", "强大/强壮", "strong", 0],
    ["đặc biệt", "特别", "special", 0],
    ["tâm", "心/脑", "mind", 0],
    ["sau", "之后/后面", "behind", 0],
    ["đuôi", "尾巴", "tail", 0],
    ["sản xuất", "生产", "produce", 0],
    ["thực tế", "现实/事实", "fact", 0],
    ["không gian", "空间", "space", 0],
    ["nghe", "听", "heard", 0],
    ["tốt nhất", "最好", "best", 0],
    ["giờ", "小时/时间", "hour", 0],
    ["tốt hơn", "更好", "better", 0],
    ["đúng", "对/正确", "true", 0],
    ["trong khi", "当...之时", "during", 0],
    ["trăm", "百", "hundred", 0],
    ["năm", "年/五", "five", 0],
    ["nhớ", "记得/想念", "remember", 0],
    ["bước", "步", "step", 0],
    ["đầu", "头/开始", "early", 0],
    ["giư", "保持/持有", "hold", 0],
    ["tây", "西/西方", "west", 0],
    ["mặt đất", "地面", "ground", 0],
    ["quan tâm", "关心/兴趣", "interest", 0],
    ["đạt", "达到", "reach", 0],
    ["động từ", "动词", "verb", 0],
    ["hát", "唱", "sing", 0],
    ["lắng nghe", "倾听", "listen", 0],
    ["sáu", "六", "six", 0],
    ["du lịch", "旅游/旅行", "travel", 0],
    ["ít", "少", "less", 0],
    ["buổi sáng", "早晨", "morning", 0],
    ["mười", "十", "ten", 0],
    ["đơn giản", "简单", "simple", 0],
    ["nhiều", "多/许多", "several", 0],
    ["nguyên âm", "元音", "vowel", 0],
    ["hướng", "方向", "toward", 0],
    ["chiến tranh", "战争", "war", 0],
    ["đặt", "放/安置", "lay", 0],
    ["chống lại", "反对/抗争", "against", 0],
    ["mô hình", "模型/图案", "pattern", 0],
    ["chậm", "慢", "slow", 0],
    ["trung tâm", "中心", "center", 0],
    ["tình yêu", "爱情", "love", 0],
    ["người", "人", "person", 0],
    ["tiền", "钱", "money", 0],
    ["phục vụ", "服务/提供", "serve", 0],
    ["xuất hiện", "出现", "appear", 0],
    ["đường", "路/糖", "road", 0],
    ["Bản đồ", "地图", "map", 0],
    ["mưa", "雨", "rain", 0],
    ["quy tắc", "规则", "rule", 0],
    ["phối", "配合/治理", "govern", 0],
    ["kéo", "拉", "pull", 0],
    ["lạnh", "冷", "cold", 0],
    ["thông báo", "通知", "notice", 0],
    ["giọng nói", "声音", "voice", 0],
    ["năng lượng", "能量", "energy", 0],
    ["săn", "打猎", "hunt", 0],
    ["có thể xảy ra", "可能", "probable", 0],
    ["giường", "床", "bed", 0],
    ["anh trai", "哥哥/兄弟", "brother", 0],
    ["trứng", "蛋", "egg", 0],
    ["đi xe", "骑车", "ride", 0],
    ["pin", "电池/细胞", "cell", 0],
    ["tin", "相信/消息", "believe", 0],
    ["có lẽ", "也许", "perhaps", 0],
    ["chọn", "选择/挑选", "pick", 0],
    ["đột ngột", "突然", "sudden", 0],
    ["tính", "计算/性质", "count", 0],
    ["vuông", "正方形", "square", 0],
    ["lý do", "原因", "reason", 0],
    ["chiều dài", "长度", "length", 0],
    ["đại diện", "代表", "represent", 0],
    ["nghệ thuật", "艺术", "art", 0],
    ["Tiêu đề", "标题/主题", "subject", 0],
    ["khu", "区域", "region", 0],
    ["kích thước", "尺寸", "size", 0],
    ["khác nhau", "不同", "vary", 0],
    ["giải quyết", "解决/定居", "settle", 0],
    ["nói", "说", "speak", 0],
    ["trọng lượng", "重量", "weight", 0],
    ["chung", "一般/共同", "general", 0],
    ["băng", "冰/胶带", "ice", 0],
    ["vấn đề", "问题/事情", "matter", 0],
    ["vòng tròn", "圆圈", "circle", 0],
    ["đôi", "一对/双", "pair", 0],
    ["bao gồm", "包括", "include", 0],
    ["chia", "划分/分享", "divide", 0],
    ["âm tiết", "音节", "syllable", 0],
    ["cảm thấy", "感觉", "felt", 0],
    ["lớn", "大", "grand", 0],
    ["bóng", "球/影子", "ball", 0],
    ["nhưng", "但是", "yet", 0],
    ["sóng", "波/浪", "wave", 0],
    ["rơi", "落下", "drop", 0],
    ["tim", "心", "heart", 0],
    ["là", "是", "am", 0],
    ["hiện nay", "现在/呈现", "present", 0],
    ["nặng", "重", "heavy", 0],
    ["khiêu vũ", "舞蹈/跳舞", "dance", 0],
    ["động cơ", "发动机/引擎", "engine", 0],
    ["vị trí", "位置", "position", 0],
    ["cánh tay", "手臂", "arm", 0],
    ["rộng", "宽", "wide", 0],
    ["buồm", "帆", "sail", 0],
    ["tài liệu", "资料/材料", "material", 0],
    ["phần", "部分/分数", "fraction", 0],
    ["rừng", "森林", "forest", 0],
    ["ngồi", "坐", "sit", 0],
    ["cuộc đua", "竞赛/种族", "race", 0],
    ["cửa sổ", "窗户", "window", 0],
    ["cửa hàng", "商店/店铺", "store", 0],
    ["mùa hè", "夏天", "summer", 0],
    ["đào tạo", "培训", "train", 0],
    ["ngủ", "睡觉", "sleep", 0],
    ["chứng minh", "证明", "prove", 0],
    ["đơn độc", "孤独", "lone", 0],
    ["chân", "脚/腿", "leg", 0],
    ["tập thể dục", "锻炼/练习", "exercise", 0],
    ["tường", "墙", "wall", 0],
    ["bắt", "捕捉/抓", "catch", 0],
    ["mount", "山/登上", "mount", 0],
    ["muốn", "想要/希望", "wish", 0],
    ["bầu trời", "天空", "sky", 0],
    ["hội đồng quản trị", "董事会/木板", "board", 0],
    ["niềm vui", "喜悦", "joy", 0],
    ["mùa đông", "冬天", "winter", 0],
    ["bằng văn bản", "书面", "written", 0],
    ["hoang dã", "荒野/野生", "wild", 0],
    ["cụ", "工具/乐器", "instrument", 0],
    ["giữ", "保持/保留", "kept", 0],
    ["kính", "玻璃/镜片", "glass", 0],
    ["cỏ", "草", "grass", 0],
    ["bò", "牛/爬", "cow", 0],
    ["công việc", "工作", "job", 0],
    ["cạnh", "边缘", "edge", 0],
    ["dấu hiệu", "符号/迹象", "sign", 0],
    ["lần", "次数/访问", "visit", 0],
    ["qua", "经过/过去", "past", 0],
    ["mềm", "软", "soft", 0],
    ["vui vẻ", "快乐/乐趣", "fun", 0],
    ["sáng", "亮/早晨", "bright", 0],
    ["khí", "气体/气", "gas", 0],
    ["thời tiết", "天气", "weather", 0],
    ["tháng", "月", "month", 0],
    ["triệu", "百万", "million", 0],
    ["chịu", "承受/熊", "bear", 0],
    ["kết thúc", "结束", "finish", 0],
    ["hạnh phúc", "幸福", "happy", 0],
    ["hy vọng", "希望", "hope", 0],
    ["hoa", "花", "flower", 0],
    ["mặc", "穿/戴", "clothe", 0],
    ["lạ", "奇怪", "strange", 0],
    ["ra đi", "离去/逝世", "gone", 0],
    ["thương mại", "贸易", "trade", 0],
    ["giai điệu", "旋律/语气", "melody", 0],
    ["chuyến đi", "旅行/行程", "trip", 0],
    ["văn phòng", "办公室", "office", 0],
    ["nhận", "收到/认识", "receive", 0],
    ["hàng", "行/列/货物", "row", 0],
    ["miệng", "嘴", "mouth", 0],
    ["biểu tượng", "象征/符号", "symbol", 0],
    ["chết", "死", "die", 0],
    ["nhất", "最/第一", "least", 0],
    ["rắc rối", "麻烦", "trouble", 0],
    ["hét lên", "尖叫/喊", "shout", 0],
    ["trừ", "减/除非", "except", 0],
    ["đã viết", "写了", "wrote", 0],
    ["hạt giống", "种子", "seed", 0],
    ["tham gia", "参加", "join", 0],
    ["đề nghị", "建议/提议", "suggest", 0],
    ["sạch", "干净", "clean", 0],
    ["nghỉ", "休息", "break", 0],
    ["phụ nữ", "女性/女士", "lady", 0],
    ["sân", "院子/球场", "yard", 0],
    ["tăng", "增加/上升", "rise", 0],
    ["xấu", "坏/丑", "bad", 0],
    ["đòn", "打击", "blow", 0],
    ["dầu", "油", "oil", 0],
    ["máu", "血", "blood", 0],
    ["chạm", "碰/触摸", "touch", 0],
    ["phần trăm", "百分比", "cent", 0],
    ["trộn", "混合", "mix", 0],
    ["đội", "队伍/团队", "team", 0],
    ["dây", "线/绳", "wire", 0],
    ["chi phí", "成本/费用", "cost", 0],
    ["thua", "输/丢失", "lost", 0],
    ["nâu", "棕色", "brown", 0],
    ["vườn", "花园", "garden", 0],
    ["như nhau", "同样/相等", "equal", 0],
    ["gửi", "寄/发", "sent", 0],
    ["phù hợp với", "适合/套装", "fit", 0],
    ["chảy", "流", "flow", 0],
    ["công bằng", "公平", "fair", 0],
    ["ngân hàng", "银行", "bank", 0],
    ["thu thập", "收集", "collect", 0],
    ["lưu", "保存/节省", "save", 0],
    ["kiểm soát", "控制", "control", 0],
    ["số thập phân", "小数", "decimal", 0],
    ["tai", "耳朵", "ear", 0],
    ["khác", "另外/其他", "else", 0],
    ["khá", "相当/挺", "quite", 0],
    ["đã phá vỡ", "打破了", "broke", 0],
    ["khi", "当时/当", "case", 0],
    ["trung", "中/中间", "middle", 0],
    ["giết", "杀", "kill", 0],
    ["con trai", "儿子", "son", 0],
    ["hồ", "湖", "lake", 0],
    ["thời điểm", "时刻", "moment", 0],
    ["quy mô", "规模", "scale", 0],
    ["mùa xuân", "春天", "spring", 0],
    ["quan sát", "观察", "observe", 0],
    ["con", "子女/孩子", "child", 0],
    ["thẳng", "直", "straight", 0],
    ["phụ âm", "辅音", "consonant", 0],
    ["quốc gia", "国家", "nation", 0],
    ["từ điển", "字典", "dictionary", 0],
    ["sưa", "牛奶", "milk", 0],
    ["tốc độ", "速度", "speed", 0],
    ["phương pháp", "方法", "method", 0],
    ["cơ quan", "机关/器官", "organ", 0],
    ["trả", "付/还", "pay", 0],
    ["tuổi", "年龄", "age", 0],
    ["váy", "裙子", "dress", 0],
    ["điện toán đám mây", "云计算", "cloud", 0],
    ["bất ngờ", "意外/惊喜", "surprise", 0],
    ["yên tĩnh", "安静", "quiet", 0],
    ["đá", "石头/踢", "stone", 0],
    ["nh nhỏ", "微小", "tiny", 0],
    ["lên cao", "攀登", "climb", 0],
    ["mát mẻ", "凉快", "cool", 0],
    ["thiết kế", "设计", "design", 0],
    ["người nghèo", "穷人", "poor", 0],
    ["rất nhiều", "很多", "lot", 0],
    ["thí nghiệm", "实验", "experiment", 0],
    ["dưới", "在下", "bottom", 0],
    ["chính", "主要/正式", "key", 0],
    ["sắt", "铁", "iron", 0],
    ["đơn", "单/简单", "single", 0],
    ["thanh", "条/棒", "stick", 0],
    ["phẳng", "平坦", "flat", 0],
    ["hai mươi", "二十", "twenty", 0],
    ["da", "皮肤", "skin", 0],
    ["nụ cười", "微笑", "smile", 0],
    ["nếp", "折痕/皱褶", "crease", 0],
    ["lỗ", "洞/孔", "hole", 0],
    ["nhảy", "跳", "jump", 0],
    ["bé", "婴儿/小", "baby", 0],
    ["tám", "八", "eight", 0],
    ["làng", "村庄", "village", 0],
    ["đáp ứng", "满足/回应", "meet", 0],
    ["gốc", "根/源", "root", 0],
    ["mua", "买", "buy", 0],
    ["nâng cao", "提升/提高", "raise", 0],
    ["kim loại", "金属", "metal", 0],
    ["liệu", "材料/是否", "whether", 0],
    ["đẩy", "推", "push", 0],
    ["bảy", "七", "seven", 0],
    ["đoạn", "段落/片段", "paragraph", 0],
    ["thứ ba", "第三", "third", 0],
    ["có trách nhiệm", "负责", "shall", 0],
    ["được tổ chức", "被组织/举办", "held", 0],
    ["lông", "毛", "hair", 0],
    ["mô tả", "描述", "describe", 0],
    ["nấu ăn", "烹饪", "cook", 0],
    ["sàn", "地板", "floor", 0],
    ["hoặc", "或者", "either", 0],
    ["kết quả", "结果", "result", 0],
    ["đồi", "山丘", "hill", 0],
    ["an toàn", "安全", "safe", 0],
    ["mèo", "猫", "cat", 0],
    ["thế kỷ", "世纪", "century", 0],
    ["xem xét", "考虑/审阅", "consider", 0],
    ["loại", "类型/种类", "type", 0],
    ["pháp luật", "法律", "law", 0],
    ["bit", "位/一点", "bit", 0],
    ["bờ biển", "海岸", "coast", 0],
    ["bản sao", "副本/拷贝", "copy", 0],
    ["cụm từ", "短语", "phrase", 0],
    ["im lặng", "沉默", "silent", 0],
    ["cao", "高", "tall", 0],
    ["cát", "沙", "sand", 0],
    ["đất", "土地/土壤", "soil", 0],
    ["cuộn", "卷", "roll", 0],
    ["nhiệt độ", "温度", "temperature", 0],
    ["ngón tay", "手指", "finger", 0],
    ["ngành công nghiệp", "工业", "industry", 0],
    ["giá trị", "价值", "value", 0],
    ["cuộc chiến", "战斗", "fight", 0],
    ["lời nói dối", "谎言", "lie", 0],
    ["đánh bại", "击败", "beat", 0],
    ["kích thích", "刺激/兴奋", "excite", 0],
    ["tự nhiên", "自然", "natural", 0],
    ["xem", "看/视图", "view", 0],
    ["ý nghĩa", "意义", "sense", 0],
    ["vốn", "资本/原本", "capital", 0],
    ["sẽ không", "将不", "won’t", 0],
    ["ghế", "椅子/座位", "chair", 0],
    ["nguy hiểm", "危险", "danger", 0],
    ["trái cây", "水果", "fruit", 0],
    ["giàu", "富有", "rich", 0],
    ["dày", "厚", "thick", 0],
    ["người lính", "士兵", "soldier", 0],
    ["quá trình", "过程", "process", 0],
    ["hoạt động", "活动/操作", "operate", 0],
    ["thực hành", "练习/实践", "practice", 0],
    ["riêng biệt", "分别/单独", "separate", 0],
    ["khó khăn", "困难", "difficult", 0],
    ["bác sĩ", "医生", "doctor", 0],
    ["xin vui lòng", "请", "please", 0],
    ["bảo vệ", "保护", "protect", 0],
    ["trưa", "中午", "noon", 0],
    ["cây trồng", "庄稼", "crop", 0],
    ["hiện đại", "现代", "modern", 0],
    ["yếu tố", "因素", "element", 0],
    ["nhấn", "按/打", "hit", 0],
    ["sinh viên", "学生", "student", 0],
    ["góc", "角", "corner", 0],
    ["bên", "旁边/派系", "party", 0],
    ["cung cấp", "提供/供应", "supply", 0],
    ["có", "有/谁的", "whose", 0],
    ["xác định vị trí", "定位", "locate", 0],
    ["vòng", "环/戒指", "ring", 0],
    ["nhân vật", "角色/性格", "character", 0],
    ["côn trùng", "昆虫", "insect", 0],
    ["thời gian", "时间/时期", "period", 0],
    ["chỉ ra", "指出/表明", "indicate", 0],
    ["radio", "广播/收音机", "radio", 0],
    ["nguyên tử", "原子", "atom", 0],
    ["con người", "人类", "human", 0],
    ["lịch sử", "历史", "history", 0],
    ["hiệu lực", "效果/效力", "effect", 0],
    ["điện", "电", "electric", 0],
    ["mong đợi", "期望", "expect", 0],
    ["xương", "骨头", "bone", 0],
    ["đường sắt", "铁路", "rail", 0],
    ["tưởng tượng", "想象", "imagine", 0],
    ["cho", "给/提供", "provide", 0],
    ["đồng ý", "同意", "agree", 0],
    ["do đó", "因此", "thus", 0],
    ["nhẹ nhàng", "轻柔", "gentle", 0],
    ["người phụ nữ", "女人", "woman", 0],
    ["đội trưởng", "队长", "captain", 0],
    ["đoán", "猜", "guess", 0],
    ["cần thiết", "必要", "necessary", 0],
    ["sắc nét", "尖锐/锋利", "sharp", 0],
    ["cánh", "翅膀", "wing", 0],
    ["tạo", "创造/产生", "create", 0],
    ["hàng xóm", "邻居", "neighbor", 0],
    ["rửa", "洗", "wash", 0],
    ["bat", "蝙蝠/球棒", "bat", 0],
    ["thay", "代替/相当", "rather", 0],
    ["đám đông", "人群", "crowd", 0],
    ["ngô", "玉米", "corn", 0],
    ["so sánh", "比较", "compare", 0],
    ["bài thơ", "诗", "poem", 0],
    ["chuỗi", "链/字符串", "string", 0],
    ["chuông", "钟/铃", "bell", 0],
    ["phụ thuộc", "依赖", "depend", 0],
    ["thịt", "肉", "meat", 0],
    ["chà", "擦/刷", "rub", 0],
    ["ống", "管", "tube", 0],
    ["nổi tiếng", "著名", "famous", 0],
    ["đồng đô la", "美元", "dollar", 0],
    ["sông", "江/河", "stream", 0],
    ["sợ hãi", "害怕", "fear", 0],
    ["cảnh", "景色/场景", "sight", 0],
    ["mỏng", "薄", "thin", 0],
    ["tam giác", "三角形", "triangle", 0],
    ["hành tinh", "行星", "planet", 0],
    ["nhanh", "快/匆忙", "hurry", 0],
    ["trưởng", "首领/首席", "chief", 0],
    ["thuộc địa", "殖民地", "colony", 0],
    ["đồng hồ", "表/钟", "clock", 0],
    ["tôi", "我/我的", "mine", 0],
    ["cà vạt", "领带", "tie", 0],
    ["nhập", "进入/输入", "enter", 0],
    ["chính", "主要/关键", "major", 0],
    ["tươi", "新鲜", "fresh", 0],
    ["tìm kiếm", "寻找", "search", 0],
    ["vàng", "金/黄色", "yellow", 0],
    ["súng", "枪", "gun", 0],
    ["cho phép", "允许", "allow", 0],
    ["in", "印/打印", "print", 0],
    ["tại chỗ", "在场/斑点", "spot", 0],
    ["sa mạc", "沙漠", "desert", 0],
    ["hiện tại", "现在/当前", "current", 0],
    ["thang máy", "电梯/举起", "lift", 0],
    ["đến", "来/到达", "arrive", 0],
    ["chủ", "主人/掌握", "master", 0],
    ["theo dõi", "追踪", "track", 0],
    ["mẹ", "母亲/家长", "parent", 0],
    ["bờ", "岸/支撑", "shore", 0],
    ["phân chia", "划分/分配", "division", 0],
    ["tờ", "张/页", "sheet", 0],
    ["chất", "物质/质量", "substance", 0],
    ["ủng hộ", "拥护/支持", "favor", 0],
    ["kết nối", "连接", "connect", 0],
    ["bài", "文章/帖子/邮政", "post", 0],
    ["chi tiêu", "花费", "spend", 0],
    ["hợp âm", "和弦", "chord", 0],
    ["chất béo", "脂肪/肥", "fat", 0],
    ["vui", "开心", "glad", 0],
    ["ban đầu", "原本/最初", "original", 0],
    ["chia sẻ", "分享", "share", 0],
    ["trạm", "站", "station", 0],
    ["cha", "父亲/爸爸", "dad", 0],
    ["bánh mì", "面包", "bread", 0],
    ["phí", "费用", "charge", 0],
    ["thích hợp", "合适", "proper", 0],
    ["thanh", "酒吧/条", "bar", 0],
    ["phân khúc", "部分/切片", "segment", 0],
    ["nô lệ", "奴隶", "slave", 0],
    ["vịt", "鸭", "duck", 0],
    ["ngay lập tức", "立即", "instant", 0],
    ["thị trường", "市场", "market", 0],
    ["mức độ", "程度", "degree", 0],
    ["cư", "居住/填充", "populate", 0],
    ["gà", "鸡", "chick", 0],
    ["thân yêu", "亲爱", "dear", 0],
    ["kẻ thù", "敌人", "enemy", 0],
    ["trả lời", "回答", "reply", 0],
    ["ly", "杯子/喝", "drink", 0],
    ["xảy ra", "发生", "occur", 0],
    ["hỗ trợ", "支持/辅佐", "support", 0],
    ["bài phát biểu", "演说/发言", "speech", 0],
    ["thiên nhiên", "大自然", "nature", 0],
    ["phạm vi", "范围", "range", 0],
    ["hơi nước", "水汽", "steam", 0],
    ["chuyển động", "运动/移动", "motion", 0],
    ["con đường", "道路/小径", "path", 0],
    ["chất lỏng", "液体", "liquid", 0],
    ["đăng nhập", "登录/日志", "log", 0],
    ["có nghĩa là", "意味着", "meant", 0],
    ["thương", " thương/除法商", "quotient", 0],
    ["răng", "牙齿", "teeth", 0],
    ["vỏ", "壳/皮", "shell", 0],
    ["cổ", "脖子/古老", "neck", 0],
    ["oxy", "氧气", "oxygen", 0],
    ["khá", "相当/漂亮", "pretty", 0],
    ["kỹ năng", "技能", "skill", 0],
    ["mùa", "季节", "season", 0],
    ["giải pháp", "方案/解决", "solution", 0],
    ["nam châm", "磁铁", "magnet", 0],
    ["bạc", "银", "silver", 0],
    ["cảm ơn", "谢谢", "thank", 0],
    ["chi nhánh", "分支/分店", "branch", 0],
    ["trận đấu", "比赛", "match", 0],
    ["hậu tố", "后缀", "suffix", 0],
    ["đặc biệt là", "特别是", "especially", 0],
    ["sung", "无花果", "fig", 0],
    ["sợ", "怕/害怕", "afraid", 0],
    ["to", "大", "huge", 0],
    ["em gái", "妹妹", "sister", 0],
    ["thép", "钢", "steel", 0],
    ["thảo luận", "讨论", "discuss", 0],
    ["về phía trước", "向前", "forward", 0],
    ["tương tự", "类似", "similar", 0],
    ["hướng dẫn", "指引/说明书", "guide", 0],
    ["kinh nghiệm", "经验", "experience", 0],
    ["điểm", "分数/点", "score", 0],
    ["táo", "苹果", "apple", 0],
    ["áo", "衣服/外套", "coat", 0],
    ["khối lượng", "质量/体积", "mass", 0],
    ["thẻ", "卡/标签", "card", 0],
    ["ban nhạc", "乐队", "band", 0],
    ["trượt", "滑", "slip", 0],
    ["giành chiến thắng", "赢得", "win", 0],
    ["mơ", "梦", "dream", 0],
    ["buổi tối", "晚上", "evening", 0],
    ["điều kiện", "条件", "condition", 0],
    ["thức ăn chăn nuôi", "饲料", "feed", 0],
    ["công cụ", "工具", "tool", 0],
    ["tổng số", "总计", "total", 0],
    ["cơ bản", "基础", "basic", 0],
    ["mùi", "味道", "smell", 0],
    ["thung lũng", "山谷", "valley", 0],
    ["cũng không", "也不", "nor", 0],
    ["tiếp tục", "继续", "continue", 0],
    ["khối", "块/堵塞", "block", 0],
    ["biểu đồ", "图表", "chart", 0],
    ["mũ", "帽", "hat", 0],
    ["bán", "卖", "sell", 0],
    ["thành công", "成功", "success", 0],
    ["công ty", "公司", "company", 0],
    ["sự kiện", "事件", "event", 0],
    ["riêng", "私有/特别", "particular", 0],
    ["thỏa thuận", "协议/交易", "deal", 0],
    ["bơi", "游", "swim", 0],
    ["hạn", "期限/术语", "term", 0],
    ["ngược lại", "相反", "opposite", 0],
    ["vợ", "妻子", "wife", 0],
    ["giày", "鞋", "shoe", 0],
    ["vai", "肩", "shoulder", 0],
    ["lây lan", "传播/展开", "spread", 0],
    ["sắp xếp", "排列/布置", "arrange", 0],
    ["trại", "营/营地", "camp", 0],
    ["phát minh", "发明", "invent", 0],
    ["bông", "棉花/花朵", "cotton", 0],
    ["Sinh", "出生", "born", 0],
    ["xác định", "确定", "determine", 0],
    ["lít", "升", "quart", 0],
    ["chín", "九/成熟", "nine", 0],
    ["xe tải", "卡车", "truck", 0],
    ["tiếng ồn", "噪音", "noise", 0],
    ["mức", "水平/级别", "level", 0],
    ["cơ hội", "机会", "chance", 0],
    ["căng ra", "拉伸", "stretch", 0],
    ["ném", "扔/投", "throw", 0],
    ["tỏa sáng", "发光", "shine", 0],
    ["tài sản", "财产", "property", 0],
    ["cột", "柱/列", "column", 0],
    ["phân tử", "分子", "molecule", 0],
    ["sai", "错", "wrong", 0],
    ["màu xám", "灰色", "gray", 0],
    ["lặp lại", "重复", "repeat", 0],
    ["yêu cầu", "要求", "require", 0],
    ["chuẩn bị", "准备", "prepare", 0],
    ["muối", "盐", "salt", 0],
    ["mui", "鼻子", "nose", 0],
    ["số nhiều", "复数", "plural", 0],
    ["tức giận", "愤怒", "anger", 0],
    ["xin", "请/申请", "claim", 0],
    ["lục", "大陆/绿色", "continent", 0],
  ],
};

